# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Fri May 29 11:00:11 2020
# ------------------------------------------------

package:
    name: vtk
    version: 8.2.0
source:
    fn: VTK-8.2.0.tar.gz
    patches:
        - 0001-Link-libpython-optionally-make-vtkPython-dep-compile.patch
        - 0002-VTKGenerateExportHeader-Prefer-dumpversion-over-vers.patch
        - 0003-py38.patch
    sha256: 34c3dc775261be5e45a8049155f7228b6bd668106c72a3c435d95730d17d57bb
    url: http://www.vtk.org/files/release/8.2/VTK-8.2.0.tar.gz
build:
    number: '218'
    string: py37h359a0f6_218
requirements:
    build:
        - cmake 3.17.0 he025d50_0
        - ninja 1.10.0 h1ad3211_0
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - vs2017_win-64 19.16.27038 h2e3bad8_2
        - vswhere 2.7.1 h21ff451_0
    host:
        - boost-cpp 1.72.0 h0caebb8_0
        - bzip2 1.0.8 hfa6e2cd_2
        - ca-certificates 2020.4.5.1 hecc5488_0
        - curl 7.69.1 h1dcc11c_0
        - expat 2.2.9 he025d50_2
        - freetype 2.9.1 h563cfd7_1006
        - hdf4 4.2.13 hf8e6fe8_1003
        - hdf5 1.10.6 nompi_ha405e13_100
        - jpeg 9c hfa6e2cd_1001
        - jsoncpp 1.8.4 h1ad3211_1002
        - krb5 1.17.1 hdd46e55_0
        - libcurl 7.69.1 h1dcc11c_0
        - libiconv 1.15 hfa6e2cd_1006
        - libnetcdf 4.7.4 nompi_h256d12c_104
        - libpng 1.6.37 hfe6a214_1
        - libssh2 1.9.0 h3235a2c_2
        - libtiff 4.1.0 h885aae3_6
        - libxml2 2.9.10 h5d81f1c_1
        - lz4-c 1.9.2 h62dcd97_1
        - openssl 1.1.1g he774522_0
        - python 3.7.6 h60c2a47_5_cpython
        - python_abi 3.7 1_cp37m
        - sqlite 3.30.1 hfa6e2cd_0
        - tbb 2019.9 he980bc4_1
        - tbb-devel 2019.9 he980bc4_1
        - tk 8.6.10 hfa6e2cd_0
        - vc 14.1 h869be7e_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - xz 5.2.5 h2fa13f4_0
        - zlib 1.2.11 h2fa13f4_1006
        - zstd 1.4.4 h9f78265_3
    run:
        - expat >=2.2.9,<2.3.0a0
        - expat >=2.2.9,<2.3.0a0
        - freetype >=2.9.1,<3.0a0
        - freetype >=2.9.1,<3.0a0
        - future
        - hdf5 >=1.10.6,<1.10.7.0a0
        - jpeg >=9c,<10a
        - jpeg >=9c,<10a
        - jsoncpp >=1.8.4,<1.8.5.0a0
        - jsoncpp >=1.8.4,<1.8.5.0a0
        - libnetcdf >=4.7.4,<4.7.5.0a0
        - libpng >=1.6.37,<1.7.0a0
        - libpng >=1.6.37,<1.7.0a0
        - libtiff >=4.1.0,<5.0a0
        - libtiff >=4.1.0,<5.0a0
        - libxml2 >=2.9.10,<2.10.0a0
        - libxml2 >=2.9.10,<2.10.0a0
        - lz4-c >=1.9.2,<1.9.3.0a0
        - lz4-c >=1.9.2,<1.9.3.0a0
        - python >=3.7,<3.8.0a0
        - python_abi 3.7.* *_cp37m
        - tbb >=2019.9
        - tk >=8.6.10,<8.7.0a0
        - tk >=8.6.10,<8.7.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
    run_constrained:
        - paraview ==9999999999
test:
    imports:
        - vtk
        - vtk.vtkChartsCore
        - vtk.vtkCommonCore
        - vtk.vtkFiltersCore
        - vtk.vtkFiltersGeneric
        - vtk.vtkFiltersHybrid
        - vtk.vtkGeovisCore
        - vtk.vtkIOCore
        - vtk.vtkImagingCore
        - vtk.vtkInfovisCore
        - vtk.vtkInteractionWidgets
        - vtk.vtkRenderingCore
        - vtk.vtkRenderingVolume
        - vtk.vtkViewsCore
        - vtk.vtkWebGLExporter
        - vtkmodules
        - vtkmodules.vtkChartsCore
        - vtkmodules.vtkCommonCore
        - vtkmodules.vtkFiltersCore
        - vtkmodules.vtkFiltersGeneric
        - vtkmodules.vtkFiltersHybrid
        - vtkmodules.vtkGeovisCore
        - vtkmodules.vtkIOCore
        - vtkmodules.vtkImagingCore
        - vtkmodules.vtkInfovisCore
        - vtkmodules.vtkInteractionWidgets
        - vtkmodules.vtkRenderingCore
        - vtkmodules.vtkRenderingVolume
        - vtkmodules.vtkViewsCore
    requires:
        - setuptools
about:
    home: http://www.vtk.org/
    license: BSD-3-Clause
    license_file: Copyright.txt
    summary: 'The Visualization Toolkit (VTK) is an open-source, freely available
        software system for 3D computer graphics, modeling, image processing, volume
        rendering, scientific visualization, and information visualization.

        '
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - Maxyme
        - ccordoba12
        - dfroger
        - downiec
        - grlee77
        - jasonb5
        - marcelotrevisani
        - msarahan
        - muryanto1
        - patricksnape
        - tadeu
        - xylar
