# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Fri Oct  9 19:47:22 2020
# ------------------------------------------------

package:
    name: qtawesome
    version: 1.0.1
source:
    sha256: d612a313e531966d17f5a8fb7604faba961cf7ce3c77a9168c6f60e60140b767
    url: https://pypi.io/packages/source/q/qtawesome/QtAwesome-1.0.1.tar.gz
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/qtawesome_1602272867890/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py_0
requirements:
    build:
        - libdrm-cos6-x86_64 2.4.65 hd39d64f_0
        - libx11-common-cos6-x86_64 1.6.4 h023ea50_0
        - libx11-cos6-x86_64 1.6.4 h64a1553_0
        - mesa-libgl-cos6-x86_64 11.0.7 h045e36e_0
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1h h7b6447c_0
        - pip 20.2.3 py38_0
        - python 3.8.5 h7579374_1
        - readline 8.0 h7b6447c_0
        - setuptools 50.3.0 py38hb0f4dca_1
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python
        - qtpy
test:
    imports:
        - qtawesome
    requires:
        - mesa-libgl-devel-cos6-x86_64
        - pyqt
about:
    home: https://github.com/spyder-ide/qtawesome
    license: MIT
    license_file: LICENSE.txt
    summary: Iconic fonts in PyQt and PySide applications
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - SylvainCorlay
        - ccordoba12
        - dalthviz
