# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# C:\ci\containers\000016i26a3\tmp\build\80754af9\combined_recipe, last modified Sat Nov 28 16:39:54 2020
# ------------------------------------------------

package:
    name: ninja
    version: 1.10.2
source:
    fn: v1.10.2.tar.gz
    sha256: ce35865411f0490368a8fc383f29071de6690cbadc27704734978221f25e2bed
    url: https://github.com/ninja-build/ninja/archive/v1.10.2.tar.gz
build:
    ignore_run_exports:
        - vc
    number: '0'
    string: py37h6d14046_0
requirements:
    build:
        - vs2017_win-64 19.16.27032.1 hb4161e2_3
        - vswhere 2.7.1 h21ff451_0
    host:
        - ca-certificates 2020.10.14 0
        - openssl 1.1.1h he774522_0
        - python 3.7.9 h60c2a47_0
        - sqlite 3.33.0 h2a8f88b_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - zlib 1.2.11 h62dcd97_4
    run:
        - python >=3.7,<3.8.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    commands:
        - ninja --version
about:
    dev_url: https://github.com/ninja-build/ninja
    doc_source_url: https://github.com/ninja-build/ninja/tree/master/doc
    doc_url: https://ninja-build.org/manual.html
    home: https://ninja-build.org/
    license: Apache 2.0
    license_family: Apache
    license_file: COPYING
    summary: A small build system with a focus on speed
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - frol
