# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00003fjorlp\tmp\build\80754af9\rsync-recipes\pyyaml-5.3.1-python_3.7-on-winbuilder, last modified Thu Jun 25 23:35:13 2020
# ------------------------------------------------

package:
    name: pyyaml
    version: 5.3.1
source:
    patches:
        - 0001-Ensure-we-do-not-end-up-wih-CRLF-line-endings-on-tes.patch
    sha256: b8eac752c5e14d3eca0e6dd9199cd627518cb5ec06add0de9d32baeee6fe645d
    url: https://pypi.io/packages/source/P/PyYAML/PyYAML-5.3.1.tar.gz
build:
    number: '1'
    script:
        - python setup.py --with-libyaml build_ext --include-dirs="%LIBRARY_INC%"
            --library-dirs="%LIBRARY_LIB%"
        - python setup.py install
        - python setup.py test
    string: py37he774522_1
requirements:
    build:
        - vs2017_win-64 19.16.27032.1 hb4161e2_2
        - vswhere 2.7.1 h21ff451_0
    host:
        - ca-certificates 2020.1.1 0
        - certifi 2020.6.20 py37_0
        - cython 0.29.20 py37ha925a31_0
        - openssl 1.1.1g he774522_0
        - python 3.7.7 h81c818b_4
        - setuptools 47.3.1 py37_0
        - sqlite 3.32.3 h2a8f88b_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_2
        - wincertstore 0.2 py37_0
        - yaml 0.2.5 he774522_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - python >=3.7,<3.8.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
        - yaml >=0.2.5,<0.3.0a0
test:
    imports:
        - yaml
about:
    description: 'YAML is a data serialization format designed for human readability
        and interaction with

        scripting languages.

        '
    dev_url: https://github.com/yaml/pyyaml
    doc_source_url: http://pyyaml.org/browser/pyyaml/trunk/README
    doc_url: http://pyyaml.org/wiki/PyYAMLDocumentation
    home: http://pyyaml.org/wiki/PyYAML
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: YAML parser and emitter for Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - msarahan
        - ocefpaf
        - pelson
