# This file created by conda-build 3.17.8
# ------------------------------------------------

package:
    name: libcurl
    version: 7.71.1
source:
    sha256: 9d52a4d80554f9b0d460ea2be5d7be99897a1a9f681ffafe739169afd6b4f224
    url: http://curl.haxx.se/download/curl-7.71.1.tar.bz2
build:
    number: 1
    run_exports:
        - libcurl >=7.71.1,<8.0a0
    string: h2a8f88b_1
requirements:
    build:
        - vs2017_win-64 19.16.27032.1 hb4161e2_3
        - vswhere 2.7.1 h21ff451_0
    host:
        - ca-certificates 2020.6.24 0
        - krb5 1.18.2 hc04afaa_0
        - libssh2 1.9.0 h7a1dbc1_1
        - openssl 1.1.1g he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - zlib 1.2.11 h62dcd97_4
    run:
        - krb5 >=1.18.2,<1.19.0a0
        - libssh2 >=1.9.0,<2.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
        - zlib >=1.2.11,<1.3.0a0
about:
    description: 'Curl is an open source command line tool and library for transferring
        data

        with URL syntax. It is used in command lines or scripts to transfer data.

        '
    dev_url: https://github.com/curl/curl
    doc_source_url: https://github.com/curl/curl/tree/master/docs
    doc_url: https://curl.haxx.se/docs/
    home: http://curl.haxx.se/
    license: MIT/X derivate (http://curl.haxx.se/docs/copyright.html)
    license_family: MIT
    license_file: COPYING
    summary: tool and library for transferring data with URL syntax
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mingwandroid
        - msarahan
        - ocefpaf
        - xylar
