# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Tue Aug  4 19:07:17 2020
# ------------------------------------------------

package:
    name: occt
    version: 7.4.0
source:
    fn: occt-7.4.0.tar.gz
    patches:
        - cmake_policy.patch
        - fix-brepblend.patch
        - fix-private-linking.patch
        - no-xmu.patch
    sha256: 9614c2075cef53e30b25317fc8fcfb71d60a69181d562e1c56469ed8e54ad758
    url: http://git.dev.opencascade.org/gitweb/?p=occt.git;a=snapshot;h=V7_4_0;sf=tgz
build:
    number: '7'
    string: h3ad41be_7
requirements:
    build:
        - cmake 3.16.5 he025d50_0
        - ninja 1.10.0 h1ad3211_0
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - vs2017_win-64 19.16.27038 h2e3bad8_2
        - vswhere 2.7.1 h21ff451_0
    host:
        - bzip2 1.0.8 hfa6e2cd_2
        - ca-certificates 2020.6.20 hecda079_0
        - curl 7.65.3 h4496350_0
        - expat 2.2.9 he025d50_2
        - fontconfig 2.13.1 hdcb13c4_1002
        - freeimage 3.18.0 h33f27b4_0
        - freetype 2.9.1 h563cfd7_1006
        - future 0.18.2 py37hc8dfbb8_1
        - hdf4 4.2.13 hf8e6fe8_1003
        - hdf5 1.10.5 nompi_ha405e13_1104
        - icu 67.1 h33f27b4_0
        - jpeg 9d he774522_0
        - jsoncpp 1.8.4 h1ad3211_1002
        - krb5 1.16.3 h038dc86_1000
        - libcurl 7.65.3 h4496350_0
        - libiconv 1.15 hfa6e2cd_1006
        - libnetcdf 4.7.4 nompi_hc957ea6_101
        - libpng 1.6.37 hfe6a214_1
        - libssh2 1.8.0 hd619d38_4
        - libtiff 4.1.0 h885aae3_6
        - libxml2 2.9.10 h5d81f1c_2
        - lz4-c 1.9.2 h62dcd97_1
        - openssl 1.0.2t vc14h62dcd97_0
        - python 3.7.1 h9460c21_1003
        - python_abi 3.7 1_cp37m
        - tbb 2019.9 he980bc4_1
        - tbb-devel 2019.9 he980bc4_1
        - tk 8.6.10 hfa6e2cd_0
        - vc 14.1 h869be7e_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - vtk 8.2.0 py37h48b3497_214
        - xz 5.2.5 h62dcd97_1
        - zlib 1.2.11 h2fa13f4_1006
        - zstd 1.4.5 h1f3a1b7_2
    run:
        - fontconfig >=2.13.1,<3.0a0
        - fontconfig >=2.13.1,<3.0a0
        - freeimage >=3.18.0,<3.19.0a0
        - freetype >=2.9.1,<3.0a0
        - freetype >=2.9.1,<3.0a0
        - tbb >=2019.9
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012
        - vtk >=8.2.0,<8.2.1.0a0
test:
    commands:
        - cmake -G "Ninja" .
    files:
        - CMakeLists.txt
    requires:
        - cmake
        - ninja
about:
    description: 'Open Cascade Technology (OCCT), formerly called CAS.CADE

        is an open source software development platform for 3D CAD,

        CAM, CAE, etc. that is developed and supported by Open Cascade SAS.

        '
    dev_url: http://git.dev.opencascade.org/gitweb/?p=occt.git
    doc_url: https://www.opencascade.com/content/documentation
    home: https://www.opencascade.com/
    license: LGPL-2.1
    license_family: LGPL
    license_file: LICENSE_LGPL_21.txt
    summary: this is the occ (opencascade) CAD-Kernel
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - looooo
