# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Fri Oct  9 08:05:14 2020
# ------------------------------------------------

package:
    name: nodejs
    version: 14.13.1
source:
    fn: node-v14.13.1.tar.gz
    sha256: a9d590f54a8e384c250e1c40f291b7367e1fdabfed4e9112eece0f8bec97609e
    url: https://nodejs.org/dist/v14.13.1/node-v14.13.1-win-x64.zip
build:
    detect_binary_files_with_prefix: false
    number: '0'
    string: '0'
requirements:
    host:
        - vs2015_runtime 14.16.27012 h30e32a0_2
    run:
        - vs2015_runtime
test:
    commands:
        - node -h
        - node -v
        - npm version
        - npm install -h
        - npm config get prefix -g
about:
    home: https://nodejs.org/
    license: MIT
    license_file: LICENSE
    summary: a platform for easily building fast, scalable network applications
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - blink1073
        - minrk
        - msarahan
        - pelson
        - xhochy
