# This file created by conda-build 3.20.2
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Fri Sep 18 14:31:37 2020
# ------------------------------------------------

package:
    name: bleach
    version: 3.2.1
source:
    sha256: 52b5919b81842b1854196eaae5ca29679a2f2e378905c346d3ca8227c2c66080
    url: https://pypi.io/packages/source/b/bleach/bleach-3.2.1.tar.gz
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/bleach_1600439572647/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
        -m pip install . -vvv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py36_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.2.2 py36_0
        - python 3.6.12 hcff3b4d_2
        - readline 8.0 h7b6447c_0
        - setuptools 49.6.0 py36_0
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - packaging
        - python
        - setuptools
        - six
        - webencodings
test:
    commands:
        - pip check
    imports:
        - bleach
    requires:
        - pip
about:
    description: 'Bleach is an allowed-list-based HTML sanitizing library that escapes
        or

        strips markup and attributes.

        '
    dev_url: https://github.com/mozilla/bleach
    doc_source_url: https://github.com/mozilla/bleach/blob/master/docs/index.rst
    doc_url: https://bleach.readthedocs.io/
    home: https://github.com/mozilla/bleach
    license: Apache-2.0
    license_family: Apache
    license_file: LICENSE
    summary: Easy, whitelist-based HTML-sanitizing tool
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - minrk
        - ocefpaf
