# This file created by conda-build 3.20.2
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Fri Sep 25 17:17:07 2020
# ------------------------------------------------

package:
    name: toolz
    version: 0.11.1
source:
    sha256: c7a47921f07822fe534fb1c01c9931ab335a4390c782bd28c6bcc7c2f71f3fbf
    url: https://pypi.io/packages/source/t/toolz/toolz-0.11.1.tar.gz
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/toolz_1601054250827/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
        -m pip install . -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1h h7b6447c_0
        - pip 20.2.2 py38_0
        - python 3.8.5 h7579374_1
        - readline 8.0 h7b6447c_0
        - setuptools 49.6.0 py38_0
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=3.5
test:
    imports:
        - toolz
        - toolz.curried
        - toolz.functoolz
        - toolz.sandbox
about:
    description: 'Toolz provides a set of utility functions for iterators, functions,
        and

        dictionaries. These functions interoperate well and form the building

        blocks of common data analytic operations. They extend the standard

        libraries itertools and functools and borrow heavily from the standard

        libraries of contemporary functional languages.

        '
    dev_url: https://github.com/pytoolz/toolz
    doc_source_url: https://github.com/pytoolz/toolz/blob/master/doc/source/index.rst
    doc_url: http://toolz.readthedocs.org/en/latest/
    home: http://toolz.readthedocs.org/
    license: BSD-3-Clause
    license_file: LICENSE.txt
    summary: A functional standard library for Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - eriknw
        - jakirkham
        - jcrist
        - mrocklin
        - ocefpaf
