# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/soupsieve-2.0.1-on-linux_64, last modified Thu May 21 17:12:22 2020
# ------------------------------------------------

package:
    name: soupsieve
    version: 2.0.1
source:
    sha256: a59dc181727e95d25f781f0eb4fd1825ff45590ec8ff49eadfd7f1a537cc0232
    url: https://pypi.io/packages/source/s/soupsieve/soupsieve-2.0.1.tar.gz
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/soupsieve_1590081250293/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
        -m pip install . --no-deps -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.1 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.3 he6710b0_1
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.0.2 py38_3
        - python 3.8.3 hcff3b4d_0
        - readline 8.0 h7b6447c_0
        - setuptools 46.4.0 py38_0
        - sqlite 3.31.1 h62c20be_1
        - tk 8.6.8 hbc83047_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=3.5
test:
    imports:
        - soupsieve
about:
    home: http://facelessuser.github.io/soupsieve
    license: MIT
    license_file: LICENSE.md
    summary: A modern CSS selector implementation for BeautifulSoup
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jschueller
