# This file created by conda-build 3.20.2
# meta.yaml template originally from:
# C:\ci\containers\0000160bt4e\tmp\build\80754af9\rsync-recipes\zeromq-4.3.2-on-winbuilder, last modified Thu Sep 10 12:31:16 2020
# ------------------------------------------------

package:
    name: zeromq
    version: 4.3.2
source:
    fn: zeromq-4.3.2.tar.gz
    patches:
        - 0003-windows-install.patch
        - rm-clang-format.patch
    sha256: ebd7b5c830d6428956b67a0454a7f8cbed1de74b3b01e5c33c5378e22740f763
    url: https://github.com/zeromq/libzmq/releases/download/v4.3.2/zeromq-4.3.2.tar.gz
build:
    number: '3'
    run_exports:
        - zeromq >=4.3.2,<4.3.3.0a0
    string: ha925a31_3
requirements:
    build:
        - cmake 3.17.2 h33f27b4_0
        - m2-msys2-runtime 2.5.0.17080.65c939c 3
        - m2-patch 2.7.5 2
        - msys2-conda-epoch 20160418 1
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - vs2017_win-64 19.16.27032.1 hb4161e2_3
        - vswhere 2.7.1 h21ff451_0
    host:
        - libsodium 1.0.18 h62dcd97_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
    run:
        - libsodium >=1.0.18,<1.0.19.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    commands:
        - if exist %LIBRARY_LIB%\libzmq-mt-s-4_3_2.lib (exit 0) else (exit 1)
        - if exist %LIBRARY_BIN%\libzmq-mt-4_3_2.dll (exit 0) else (exit 1)
        - if exist %LIBRARY_LIB%\libzmq-mt-4_3_2.lib (exit 0) else (exit 1)
        - if exist %LIBRARY_BIN%\libzmq.dll (exit 0) else (exit 1)
        - if exist %LIBRARY_LIB%\libzmq.lib (exit 0) else (exit 1)
        - if exist %LIBRARY_PREFIX%\cmake\ZeroMQ\ZeroMQConfig.cmake (exit 0) else
            (exit 1)
        - if exist %LIBRARY_PREFIX%\cmake\ZeroMQ\ZeroMQConfigVersion.cmake (exit 0)
            else (exit 1)
about:
    home: http://zeromq.org
    license: LGPL 3
    license_file: COPYING.LESSER
    summary: A high-performance asynchronous messaging library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - JohanMabille
        - SylvainCorlay
        - jakirkham
        - minrk
