CI: azure
c_compiler: vs2017
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: vs2017
extend_keys:
- ignore_version
- pin_run_as_build
- ignore_build_only_deps
- extend_keys
fortran_compiler: gfortran
ignore_build_only_deps:
- numpy
- python
libcurl: '7'
libtiff: 4.1.0
lua: '5'
numpy: '1.11'
perl: 5.26.0
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  libcurl:
    max_pin: x
  libtiff:
    max_pin: x
  sqlite:
    max_pin: x
python: '3.6'
r_base: '3.4'
sqlite: '3'
target_platform: win-64
vc: '14'
