# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Fri Jul 17 18:14:06 2020
# ------------------------------------------------

package:
    name: proj
    version: 7.0.0
source:
    -   sha256: ee0e14c1bd2f9429b1a28999240304c0342ed739ebaea3d4ff44c585b1097be8
        url: http://download.osgeo.org/proj/proj-7.0.0.tar.gz
build:
    number: '5'
    run_exports:
        - proj >=7.0.0,<7.0.1.0a0
    string: haa36216_5
requirements:
    build:
        - cmake 3.17.0 he025d50_0
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - vs2017_win-64 19.16.27038 h2e3bad8_2
        - vswhere 2.7.1 h21ff451_0
    host:
        - ca-certificates 2020.6.20 hecda079_0
        - jpeg 9d he774522_0
        - krb5 1.17.1 hc04afaa_1
        - libcurl 7.71.1 h4b64cdc_2
        - libssh2 1.9.0 hb06d900_4
        - libtiff 4.1.0 h885aae3_6
        - lz4-c 1.9.2 h62dcd97_1
        - openssl 1.1.1g he774522_0
        - sqlite 3.32.3 he774522_1
        - tk 8.6.10 hfa6e2cd_0
        - vc 14.1 h869be7e_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - xz 5.2.5 h62dcd97_1
        - zlib 1.2.11 h2fa13f4_1006
        - zstd 1.4.4 h9f78265_3
    run:
        - libcurl >=7.71.1,<8.0a0
        - libcurl >=7.71.1,<8.0a0
        - libtiff >=4.1.0,<5.0a0
        - libtiff >=4.1.0,<5.0a0
        - sqlite >=3.32.3,<4.0a0
        - sqlite >=3.32.3,<4.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012
    run_constrained:
        - proj4 ==999999999999
test:
    commands:
        - if not exist %LIBRARY_LIB%\\proj.lib exit 1
        - echo -105 40 | proj +proj=utm +zone=13 +ellps=WGS84
        - echo -117 30 | cs2cs +proj=latlong +datum=NAD27 +to +proj=latlong +datum=NAD83
        - echo -105 40 | cs2cs +init=epsg:4326 +to +init=epsg:2975
about:
    home: https://proj.org/
    license: MIT
    license_file: COPYING
    summary: Cartographic Projections and Coordinate Transformations Library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - hobu
        - msarahan
        - mwtoews
        - ocefpaf
        - pelson
        - snowman2
        - xylar
