# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Sun Nov 10 16:42:09 2019
# ------------------------------------------------

package:
    name: hdf4
    version: 4.2.13
source:
    patches:
        - max_files.patch
    sha256: 55d3a42313bda0aba7b0463687caf819a970e0ba206f5ed2c23724f80d2ae0f3
    url: http://www.hdfgroup.org/ftp/HDF/HDF_Current/src/hdf-4.2.13.tar.bz2
build:
    number: '1003'
    run_exports:
        - hdf4 >=4.2.13,<4.2.14.0a0
    string: hf8e6fe8_1003
requirements:
    build:
        - cmake 3.15.5 he025d50_0
        - vs2015_runtime 14.16.27012 hf0eaf9b_0
        - vs2015_win-64 14.0.25420 h55c1224_11
    host:
        - jpeg 9c hfa6e2cd_1001
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_0
        - zlib 1.2.11 h2fa13f4_1006
    run:
        - jpeg >=9c,<10a
        - jpeg >=9c,<10a
        - vc >=14.1,<15.0a0
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
about:
    home: http://www.hdfgroup.org/HDF4/
    license: BSD-3-Clause
    license_family: BSD
    license_file: COPYING
    summary: Library and multi-object file format for storing and managing data between
        machines
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - groutr
        - msarahan
        - ocefpaf
