# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00002ar8gim\tmp\build\80754af9\rsync-recipes\kiwisolver-1.2.0-python_3.7-on-winbuilder, last modified Sun May  3 23:34:43 2020
# ------------------------------------------------

package:
    name: kiwisolver
    version: 1.2.0
source:
    sha256: 247800260cd38160c362d211dcaf4ed0f7816afb5efe56544748b21d6ad6d17f
    url: https://pypi.io/packages/source/k/kiwisolver/kiwisolver-1.2.0.tar.gz
build:
    number: '0'
    script: C:\\ci\\kiwisolver_1588545644894\\_h_env\\python.exe -m pip install .
        --no-deps --ignore-installed --no-cache-dir -vvv
    string: py37h74a9793_0
requirements:
    build:
        - vs2017_win-64 19.16.27032.1 hb8d98e7_1
        - vswhere 2.7.1 h21ff451_0
    host:
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.1 py37_0
        - cppy 1.1.0 py_0
        - openssl 1.1.1g he774522_0
        - pip 20.0.2 py37_1
        - python 3.7.7 h60c2a47_2
        - setuptools 46.1.3 py37_0
        - sqlite 3.31.1 h2a8f88b_1
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
        - wheel 0.34.2 py37_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - python >=3.7,<3.8.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    imports:
        - kiwisolver
about:
    description: 'Kiwi is an implementation of the algorithm based on the seminal

        Cassowary paper.It is not a refactoring of the original C++ solver.

        Kiwi has been designed from the ground up to be lightweight and fast.

        '
    dev_url: https://github.com/nucleic/kiwi
    doc_source_url: https://github.com/nucleic/kiwi/blob/master/README.rst
    doc_url: https://pypi.python.org/pypi/kiwisolver
    home: https://github.com/nucleic/kiwi
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: An efficient C++ implementation of the Cassowary constraint solver
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - MatthieuDartiailh
        - blink1073
        - ericdill
        - licode
        - ocefpaf
        - sccolbert
        - tacaswell
