# This file created by conda-build 3.20.0
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/jupyter_console-6.2.0-on-linux_64, last modified Mon Aug 31 14:33:39 2020
# ------------------------------------------------

package:
    name: jupyter_console
    version: 6.2.0
source:
    sha256: 7f6194f4f4692d292da3f501c7f343ccd5e36c6a1becf7b7515e23e66d6bf1e9
    url: https://pypi.io/packages/source/j/jupyter_console/jupyter_console-6.2.0.tar.gz
build:
    entry_points:
        - jupyter-console = jupyter_console.app:main
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/jupyter_console_1598884538475/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.2.2 py38_0
        - python 3.8.5 hcff3b4d_0
        - readline 8.0 h7b6447c_0
        - setuptools 49.6.0 py38_0
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - ipykernel
        - ipython
        - jupyter_client
        - prompt_toolkit >=2.0.0,<3.1.0,!=3.0.0,!=3.0.1
        - pygments
        - python >=3.6
test:
    commands:
        - jupyter-console -h
    imports:
        - jupyter_console
about:
    description: 'Jupyter console is a terminal frontend for kernels using the Jupyter
        protocol.

        '
    dev_url: https://github.com/jupyter/jupyter_console
    doc_source_url: https://github.com/jupyter/jupyter_console/blob/master/docs/index.rst
    doc_url: http://jupyter-console.readthedocs.org/
    home: http://jupyter.org
    license: BSD-3-Clause
    license_file: COPYING.md
    summary: Jupyter terminal console
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - Carreau
        - SylvainCorlay
        - blink1073
        - jakirkham
        - minrk
        - ocefpaf
        - pelson
        - takluyver
