# This file created by conda-build 3.18.10
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Wed Oct 30 11:41:14 2019
# ------------------------------------------------

package:
    name: double-conversion
    version: 3.1.5
source:
    fn: double-conversion-3.1.5.tar.gz
    sha256: a63ecb93182134ba4293fd5f22d6e08ca417caafa244afaa751cbfddf6415b13
    url: https://github.com/google/double-conversion/archive/v3.1.5.tar.gz
build:
    detect_binary_files_with_prefix: true
    number: '2'
    run_exports:
        - double-conversion >=3.1.5,<3.2.0a0
    string: h6538335_2
requirements:
    build:
        - cmake 3.15.4 he025d50_0
        - m2w64-gcc-libgfortran 5.3.0 6
        - m2w64-gcc-libs 5.3.0 7
        - m2w64-gcc-libs-core 5.3.0 7
        - m2w64-gmp 6.1.0 2
        - m2w64-libwinpthread-git 5.0.0.4634.697f757 2
        - make 4.2.1 h301d43c_2004
        - msys2-conda-epoch 20160418 1
        - vs2015_runtime 14.16.27012 hf0eaf9b_0
        - vs2015_win-64 14.0.25420 h55c1224_11
    host:
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_0
    run:
        - vc >=14,<15.0a0
test:
    files:
        - test.cc
    requires:
        - vs2015_win-64
about:
    description: 'double-conversion provides binary-decimal and decimal-binary routines
        for IEEE doubles.

        The library consists of efficient conversion routines that have been extracted
        from

        the V8 JavaScript engine. The code has been refactored and improved so that
        it can be

        used more easily in other projects.

        '
    dev_url: https://github.com/google/double-conversion
    doc_url: https://github.com/google/double-conversion
    home: http://github.com/google/double-conversion
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Efficient binary-decimal and decimal-binary conversion routines for IEEE
        doubles.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pearu
        - xhochy
        - xmnlab
