# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Thu Dec 31 18:22:32 2020
# ------------------------------------------------

package:
    name: pyside2
    version: 5.13.2
source:
    fn: pyside-setup-everywhere-src-5.13.2.tar.xz
    patches:
        - 0001-Make-pyside2-uic-executable-by-windows-shell.patch
        - 0001-shiboken-Support-Clang-version-10.patch
        - 0002-Fix-Python-3.8-problems.patch
        - 0003-Optimize-the-Python-3.8-refcount-fix-a-tiny-bit.patch
        - 0004-make-compilation-work-after-backporting.patch
        - 6294578.patch
        - pyi.patch
    sha256: 3e255d64df08880d0281ebe86009d5ea45f24332b308954d967c33995f75e543
    url: https://download.qt.io/official_releases/QtForPython/pyside2/PySide2-5.13.2-src/pyside-setup-opensource-src-5.13.2.tar.xz
build:
    detect_binary_files_with_prefix: true
    number: '4'
    string: py37h760f651_4
requirements:
    build:
        - clang 11.0.0 h57928b3_2
        - clang-11 11.0.0 default_h5c34c98_2
        - clang-tools 11.0.0 default_h5c34c98_2
        - clangdev 11.0.0 default_h5c34c98_2
        - clangxx 11.0.0 default_h5c34c98_2
        - cmake 3.19.2 h39d44d4_0
        - libclang 11.0.0 default_h5c34c98_2
        - libclang-cpp 11.0.0 default_h5c34c98_2
        - libllvm11 11.0.0 h5dfd299_0
        - llvm-tools 11.0.0 h5dfd299_0
        - llvmdev 11.0.0 h5dfd299_0
        - vc 14.2 hb210afc_2
        - vs2015_runtime 14.28.29325 h5e1d092_0
        - vs2017_win-64 19.16.27038 h2e3bad8_2
        - vswhere 2.7.1 h21ff451_0
        - zlib 1.2.11 h62dcd97_1010
    host:
        - ca-certificates 2020.12.5 h5b45459_0
        - icu 68.1 h0e60522_0
        - jpeg 9d h8ffe710_0
        - libclang 11.0.0 default_h5c34c98_2
        - libiconv 1.16 he774522_0
        - libpng 1.6.37 h1d00b33_2
        - libxml2 2.9.10 hf5bbc77_3
        - libxslt 1.1.33 h65864e5_2
        - openssl 1.1.1i h8ffe710_0
        - python 3.7.9 h7840368_0_cpython
        - qt 5.12.9 h5909a2a_2
        - sqlite 3.34.0 h8ffe710_0
        - vc 14.2 hb210afc_2
        - vs2015_runtime 14.28.29325 h5e1d092_0
        - zlib 1.2.11 h62dcd97_1010
    run:
        - libxml2 >=2.9.10,<2.10.0a0
        - libxslt >=1.1.33,<2.0a0
        - python >=3.7,<3.8.0a0
        - python_abi 3.7.* *_cp37m
        - qt >=5.12.9,<5.13.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012
test:
    commands:
        - shiboken2 --help
        - pyside2-lupdate -help
        - pyside2-rcc -help
        - pyside2-uic -help
    imports:
        - PySide2.Qt3DAnimation
        - PySide2.Qt3DCore
        - PySide2.Qt3DExtras
        - PySide2.Qt3DInput
        - PySide2.Qt3DLogic
        - PySide2.Qt3DRender
        - PySide2.QtCharts
        - PySide2.QtConcurrent
        - PySide2.QtCore
        - PySide2.QtDataVisualization
        - PySide2.QtGui
        - PySide2.QtHelp
        - PySide2.QtLocation
        - PySide2.QtMultimedia
        - PySide2.QtMultimediaWidgets
        - PySide2.QtNetwork
        - PySide2.QtOpenGL
        - PySide2.QtPositioning
        - PySide2.QtPrintSupport
        - PySide2.QtQml
        - PySide2.QtQuick
        - PySide2.QtQuickWidgets
        - PySide2.QtRemoteObjects
        - PySide2.QtScript
        - PySide2.QtScriptTools
        - PySide2.QtScxml
        - PySide2.QtSensors
        - PySide2.QtSql
        - PySide2.QtSvg
        - PySide2.QtTest
        - PySide2.QtTextToSpeech
        - PySide2.QtUiTools
        - PySide2.QtWebChannel
        - PySide2.QtWebEngineCore
        - PySide2.QtWebEngineWidgets
        - PySide2.QtWebSockets
        - PySide2.QtWidgets
        - PySide2.QtXml
        - PySide2.QtXmlPatterns
about:
    home: https://wiki.qt.io/PySide2
    license: LGPL-3.0-only
    license_file: LICENSE.LGPLv3
    summary: Python bindings for Qt
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jschueller
