# This file created by conda-build 3.20.0
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/more-itertools-8.5.0-on-linux_64, last modified Mon Aug 31 14:25:12 2020
# ------------------------------------------------

package:
    name: more-itertools
    version: 8.5.0
source:
    sha256: 6f83822ae94818eae2612063a5101a7311e68ae8002005b5e05f03fd74a86a20
    url: https://pypi.io/packages/source/m/more-itertools/more-itertools-8.5.0.tar.gz
build:
    noarch: python
    number: '0'
    script: '/tmp/build/80754af9/more-itertools_1598884071673/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
        -m pip install . --no-deps --ignore-installed -vv '
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.2.2 py38_0
        - python 3.8.5 hcff3b4d_0
        - readline 8.0 h7b6447c_0
        - setuptools 49.6.0 py38_0
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=3.4
test:
    commands:
        - pip check
    imports:
        - more_itertools
    requires:
        - pip
about:
    dev_url: https://github.com/more-itertools/more-itertools
    doc_url: https://more-itertools.readthedocs.io/en/latest/api.html
    home: https://github.com/more-itertools/more-itertools
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: More routines for operating on iterables, beyond itertools
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dbast
        - pmlandwehr
