# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# C:\ci\containers\000015220v2\tmp\build\80754af9\combined_recipe, last modified Wed Oct  7 08:17:33 2020
# ------------------------------------------------

package:
    name: distributed
    version: 2.30.0
source:
    sha256: 3eb8e4173625cea6ebda2f0a079b813eeabbffd1b24584855cf063ed1cca60b3
    url: https://pypi.io/packages/source/d/distributed/distributed-2.30.0.tar.gz
build:
    entry_points:
        - dask-scheduler=distributed.cli.dask_scheduler:go
        - dask-ssh=distributed.cli.dask_ssh:go
        - dask-worker=distributed.cli.dask_worker:go
    number: '0'
    script: C:\\ci\\distributed_1602065865185\\_h_env\\python.exe -m pip install .
        --no-deps --ignore-installed --no-cache-dir -vvv
    string: py37_0
requirements:
    host:
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py37_0
        - openssl 1.1.1h he774522_0
        - pip 20.2.3 py37_0
        - python 3.7.9 h60c2a47_0
        - setuptools 50.3.0 py37h9490d1a_1
        - sqlite 3.33.0 h2a8f88b_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - wheel 0.35.1 py_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - click >=6.6
        - cloudpickle >=1.5.0
        - cytoolz >=0.8.2
        - dask-core >=2.9.0
        - msgpack-python >=0.6.0
        - psutil >=5.0
        - python >=3.7,<3.8.0a0
        - pyyaml
        - setuptools
        - sortedcontainers !=2.0.0,!=2.0.1
        - tblib >=1.6.0
        - toolz >=0.8.2
        - tornado >=5
        - zict >=0.1.3
    run_constrained:
        - openssl !=1.1.1e
test:
    commands:
        - dask-scheduler --help
        - dask-ssh --help
        - dask-worker --help
    imports:
        - distributed
        - distributed.cli
        - distributed.comm
        - distributed.deploy
        - distributed.diagnostics
        - distributed.protocol
about:
    description: 'Distributed is a lightweight library for distributed computing in
        Python.

        It extends both the concurrent.futures and dask APIs to moderate sized

        clusters.

        '
    dev_url: https://github.com/dask/distributed
    doc_source_url: https://github.com/dask/distributed/blob/master/docs/source/index.rst
    doc_url: https://distributed.dask.org
    home: http://distributed.readthedocs.io/en/latest/
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: Distributed computing with Dask
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jcrist
        - jrbourbeau
        - marcelotrevisani
        - martindurant
        - mrocklin
        - ogrisel
        - tomaugspurger
