# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Aug  8 06:52:23 2020
# ------------------------------------------------

package:
    name: dash-daq
    version: 0.5.0
source:
    sha256: a1d85b6799f7b885652fbc44aebdb58c41254616a8d350b943beeb42ade4256a
    url: https://pypi.io/packages/source/d/dash-daq/dash_daq-0.5.0.tar.gz
build:
    noarch: python
    number: '1'
    script: /home/conda/feedstock_root/build_artifacts/dash-daq_1596869611219/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
        -m pip install . --no-deps -vv
    string: pyh9f0ad1d_1
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py36h9f0ad1d_0
        - ld_impl_linux-64 2.34 hc38a660_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h24d8f2e_14
        - libgomp 9.3.0 h24d8f2e_14
        - libstdcxx-ng 9.3.0 hdf63c60_14
        - ncurses 6.2 he1b5a44_1
        - openssl 1.1.1g h516909a_1
        - pip 20.2.1 py_0
        - python 3.6.11 h4d41432_2_cpython
        - python_abi 3.6 1_cp36m
        - readline 8.0 he28a2e2_2
        - setuptools 49.2.1 py36h9f0ad1d_0
        - sqlite 3.32.3 hcee41ef_1
        - tk 8.6.10 hed695b0_0
        - wheel 0.34.2 py_1
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1006
    run:
        - dash >=1.6.1
        - python
test:
    imports:
        - dash_daq
about:
    dev_url: https://github.com/plotly/dash-daq
    doc_url: https://dash.plot.ly/dash-daq
    home: https://www.dashdaq.io/
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: Control components for Dash
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - moorepants
