# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00001fuf6kf\tmp\build\80754af9\rsync-recipes\bitarray-1.5.3-python_3.7-on-winbuilder, last modified Mon Aug 31 15:38:00 2020
# ------------------------------------------------

package:
    name: bitarray
    version: 1.5.3
source:
    sha256: 567631fc922b1c2c528c376795f18dcc0604d18702e0b8b50e8e35f0474214a5
    url: https://pypi.io/packages/source/b/bitarray/bitarray-1.5.3.tar.gz
build:
    number: '0'
    script: C:\\ci\\bitarray_1598885049384\\_h_env\\python.exe -m pip install . --no-deps
        -vv
    string: py37he774522_0
requirements:
    build:
        - vs2017_win-64 19.16.27032.1 hb4161e2_3
        - vswhere 2.7.1 h21ff451_0
    host:
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py37_0
        - openssl 1.1.1g he774522_1
        - pip 20.2.2 py37_0
        - python 3.7.7 h81c818b_4
        - setuptools 49.6.0 py37_0
        - sqlite 3.33.0 h2a8f88b_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - wheel 0.35.1 py_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - python >=3.7,<3.8.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    imports:
        - bitarray
about:
    description: 'Bitarray provides an object type which efficiently represents an
        array of

        booleans. Bitarrays are sequence types that behave very similarly

        to usual lists. All functionality is implemented in C.

        '
    dev_url: https://github.com/ilanschnell/bitarray
    doc_source_url: https://github.com/ilanschnell/bitarray/blob/master/README.rst
    doc_url: https://pypi.python.org/pypi/bitarray/0.8.1
    home: https://github.com/ilanschnell/bitarray
    license: PSF
    license_file: LICENSE
    summary: efficient arrays of booleans -- C extension
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nehaljwani
