# This file created by conda-build 3.20.2
# meta.yaml template originally from:
# C:\ci\containers\00001p8n0em\tmp\build\80754af9\combined_recipe, last modified Thu Sep 24 15:48:27 2020
# ------------------------------------------------

package:
    name: cytoolz
    version: 0.11.0
source:
    sha256: c64f3590c3eb40e1548f0d3c6b2ccde70493d0b8dc6cc7f9f3fec0bb3dcd4222
    url: https://pypi.io/packages/source/c/cytoolz/cytoolz-0.11.0.tar.gz
build:
    number: '0'
    script: C:\\ci\\cytoolz_1600959050588\\_h_env\\python.exe -m pip install . --no-deps
        --ignore-installed --no-cache-dir -vvv --global-option=--with-cython
    string: py37he774522_0
requirements:
    build:
        - vs2017_win-64 19.16.27032.1 hb4161e2_3
        - vswhere 2.7.1 h21ff451_0
    host:
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py37_0
        - cython 0.29.21 py37ha925a31_0
        - openssl 1.1.1h he774522_0
        - pip 20.2.2 py37_0
        - python 3.7.9 h60c2a47_0
        - setuptools 49.6.0 py37_0
        - sqlite 3.33.0 h2a8f88b_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - wheel 0.35.1 py_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - python >=3.7,<3.8.0a0
        - toolz >=0.10.0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    commands:
        - nosetests --with-doctest cytoolz
    imports:
        - cytoolz
        - cytoolz.curried
    requires:
        - nose
        - toolz 0.10.0.*
about:
    description: 'CyToolz is the Cython implementation of the toolz package, which
        provides

        high performance utility functions for iterables, functions, and

        dictionaries.

        '
    dev_url: https://github.com/pytoolz/cytoolz
    doc_source_url: https://github.com/pytoolz/cytoolz/blob/master/README.rst
    doc_url: https://pypi.python.org/pypi/cytoolz
    home: https://github.com/pytoolz/cytoolz
    license: BSD-3-Clause
    license_file: LICENSE.txt
    summary: Cython implementation of Toolz. High performance functional utilities
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - eriknw
        - jakirkham
        - jcrist
        - mrocklin
