# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Tue Feb  4 23:49:58 2020
# ------------------------------------------------

package:
    name: libogg
    version: 1.3.2
source:
    fn: libogg-1.3.2.tar.gz
    sha256: e19ee34711d7af328cb26287f4137e70630e7261b17cbe3cd41011d73a654692
    url: http://downloads.xiph.org/releases/ogg/libogg-1.3.2.tar.gz
build:
    number: '1002'
    run_exports:
        - libogg >=1.3.2,<1.4.0a0
    string: hfa6e2cd_1002
requirements:
    build:
        - cmake 3.16.3 he025d50_0
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
        - vs2015_win-64 14.0.25420 h55c1224_11
    host:
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
    run:
        - vc >=14,<15.0a0
test:
    commands:
        - if not exist %LIBRARY_LIB%\\ogg.lib exit 1
        - if not exist %LIBRARY_BIN%\\ogg.dll exit 1
        - if not exist %LIBRARY_INC%\\ogg\\config_types.h exit 1
        - if not exist %LIBRARY_INC%\\ogg\\ogg.h exit 1
        - if not exist %LIBRARY_INC%\\ogg\\os_types.h exit 1
about:
    description: 'OGG media container. This is the native format and the recommended
        container

        for Xiph codecs.

        '
    doc_url: https://wiki.xiph.org/
    home: https://www.xiph.org/
    license: BSD3
    license_file: COPYING
    summary: OGG media container
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dschreij
