# This file created by conda-build 3.20.2
# ------------------------------------------------

package:
    name: tbb-devel
    version: '2020.3'
source:
    fn: tbbv2020.3_oss_src.tgz
    sha256: ebc4f6aa47972daed1f7bf71d100ae5bf6931c2e3144cf299c8cc7d041dca2f3
    url: https://github.com/intel/tbb/archive/v2020.3.tar.gz
build:
    number: 0
    run_exports:
        - tbb >=2020.3
    script: python build/build.py --build-args="CXXFLAGS= CFLAGS=" --make-tool=mingw32-make
        --build-prefix=vc%VS_MAJOR% --no-rebuild --install-devel --install-docs
    string: h74a9793_0
requirements:
    build:
        - bzip2 1.0.8 he774522_0
        - ca-certificates 2020.7.22 0
        - cmake 3.18.2 hab937c2_0
        - libuv 1.39.0 he774522_0
        - lz4-c 1.9.2 h62dcd97_1
        - m2w64-make 4.1.2351.a80a8b8 2
        - msys2-conda-epoch 20160418 1
        - openssl 1.1.1g he774522_1
        - python 3.8.5 h5fd99cc_1
        - sqlite 3.33.0 h2a8f88b_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - vs2017_win-64 19.16.27032.1 hb4161e2_3
        - vswhere 2.7.1 h21ff451_0
        - xz 5.2.5 h62dcd97_0
        - zlib 1.2.11 h62dcd97_4
        - zstd 1.4.5 h04227a9_0
    host:
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
    run:
        - tbb 2020.3 h74a9793_0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    commands:
        - set "TBB_DIR=%PREFIX%/bin"
        - cmake -S examples/test_all/fibonacci -B test-bld
        - cmake --build test-bld --config release
    requires:
        - cmake >=3.13
        - vs2017_win-64
    source_files:
        - examples/test_all/fibonacci
about:
    dev_url: https://github.com/01org/tbb
    doc_url: https://software.intel.com/en-us/node/506039
    home: http://www.threadingbuildingblocks.org
    license: Apache-2.0
    license_file: LICENSE
    summary: High level abstract threading library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - anton-malakhov
        - jschueller
