# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/qdarkstyle-2.8.1-on-linux_64, last modified Mon Apr 20 16:14:34 2020
# ------------------------------------------------

package:
    name: qdarkstyle
    version: 2.8.1
source:
    fn: qdarkstyle-2.8.1.tar.gz
    sha256: d53b0120bddd9e3efba9801731e22ef86ed798bb5fc6a802f5f7bb32dedf0321
    url: https://pypi.io/packages/source/q/qdarkstyle/QDarkStyle-2.8.1.tar.gz
build:
    noarch: python
    number: '0'
    script: '/tmp/build/80754af9/qdarkstyle_1587400184992/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
        -m pip install . --no-deps --ignore-installed -vvv '
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.1 py36_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_0
        - openssl 1.1.1f h7b6447c_0
        - pip 20.0.2 py36_1
        - python 3.6.10 hcf32534_1
        - readline 8.0 h7b6447c_0
        - setuptools 46.1.3 py36_0
        - sqlite 3.31.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - wheel 0.34.2 py36_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python
test:
    imports:
        - qdarkstyle
about:
    description: 'Package that provides dark stylesheet for Qt applications

        (Qt4, Qt5, PySide, PyQt4, PyQt5, QtPy, PyQtGraph).

        '
    dev_url: https://github.com/ColinDuquesnoy/QDarkStyleSheet/tree/dev
    home: https://github.com/ColinDuquesnoy/QDarkStyleSheet
    license: MIT
    license_family: MIT
    license_file: LICENSE.rst
    summary: A dark stylesheet for Qt applications (Qt4, Qt5, PySide, PyQt4, PyQt5,
        QtPy, PyQtGraph).
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - dalthviz
        - goanpeca
