# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Sun May  3 19:53:54 2020
# ------------------------------------------------

package:
    name: freecad
    version: 0.19.alpha2
source:
    git_rev: 0.19.alpha2
    git_url: https://github.com/looooo/FreeCAD
build:
    number: '0'
    string: py37h43b4559_0
requirements:
    build:
        - cmake 3.17.0 he025d50_0
        - git 2.26.2 0
        - ninja 1.10.0 h1ad3211_0
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - vs2017_win-64 19.16.27038 h2e3bad8_2
        - vswhere 2.7.1 h21ff451_0
    host:
        - boost-cpp 1.72.0 h0caebb8_0
        - bzip2 1.0.8 hfa6e2cd_2
        - ca-certificates 2020.4.5.1 hecc5488_0
        - coin3d 4.0.0 h93788fa_1009
        - curl 7.69.1 h1dcc11c_0
        - doxygen 1.8.18 0
        - eigen 3.3.7 he980bc4_1001
        - expat 2.2.9 he025d50_2
        - flann 1.9.1 h3a160d9_1008
        - fontconfig 2.13.1 hb964e45_1001
        - freeimage 3.18.0 h33f27b4_0
        - freetype 2.9.1 h563cfd7_1006
        - future 0.18.2 py37hc8dfbb8_1
        - hdf4 4.2.13 hf8e6fe8_1003
        - hdf5 1.10.6 nompi_ha405e13_100
        - icu 64.2 he025d50_1
        - jpeg 9c hfa6e2cd_1001
        - jsoncpp 1.8.4 h1ad3211_1002
        - krb5 1.17.1 hdd46e55_0
        - libclang 9.0.1 default_hf44288c_0
        - libcurl 7.69.1 h1dcc11c_0
        - libiconv 1.15 hfa6e2cd_1006
        - libnetcdf 4.7.4 nompi_h256d12c_104
        - libpng 1.6.37 hfe6a214_1
        - libssh2 1.8.2 h642c060_2
        - libtiff 4.1.0 h885aae3_6
        - libxml2 2.9.10 h9ce36c8_0
        - libxslt 1.1.33 heafd4d3_0
        - lz4-c 1.9.2 h33f27b4_0
        - netgen 6.2.1808 py37hb990d29_1007
        - occt 7.4.0 h823b557_6
        - openssl 1.1.1g he774522_0
        - pcl 1.9.1 h674dfd5_1005
        - pivy 0.6.5 py37hb798155_1
        - ply 3.11 py_1
        - pthreads-win32 2.9.1 hfa6e2cd_3
        - pybind11 2.5.0 py37heaa310e_0
        - pyside2 5.13.2 py37hfa7ce6d_2
        - python 3.7.6 h60c2a47_5_cpython
        - python_abi 3.7 1_cp37m
        - qhull 2015.2 he980bc4_1000
        - qt 5.12.5 h7ef1ec2_0
        - six 1.14.0 py_1
        - smesh 8.3.0.3 py37h5fe68d0_10
        - soqt 1.6.0 h95c7cbc_1
        - sqlite 3.30.1 hfa6e2cd_0
        - swig 4.0.1 0
        - tbb 2019.9 he980bc4_1
        - tbb-devel 2019.9 he980bc4_1
        - tk 8.6.10 hfa6e2cd_0
        - vc 14.1 h869be7e_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - vtk 8.2.0 py37h359a0f6_216
        - xerces-c 3.2.2 h6538335_1004
        - xz 5.2.5 h2fa13f4_0
        - zlib 1.2.11 h2fa13f4_1006
        - zstd 1.4.4 h9f78265_3
    run:
        - boost-cpp >=1.72.0,<1.72.1.0a0
        - coin3d
        - freetype >=2.9.1,<3.0a0
        - freetype >=2.9.1,<3.0a0
        - hdf5 >=1.10.6,<1.10.7.0a0
        - netgen
        - numpy
        - occt >=7.4.0,<7.5.0a0
        - pcl
        - pivy
        - ply
        - pyside2 >=5.13.2,<6.0a0
        - python >=3.7,<3.8.0a0
        - python_abi 3.7.* *_cp37m
        - pyyaml
        - qt >=5.12.5,<5.13.0a0
        - qt >=5.12.5,<5.13.0a0
        - six
        - smesh
        - tbb >=2019.9
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012
        - vtk >=8.2.0,<8.2.1.0a0
        - xerces-c >=3.2.2,<3.2.3.0a0
        - xerces-c >=3.2.2,<3.2.3.0a0
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - freecadcmd -t 0
about:
    description: 'FreeCAD is a general purpose feature-based, parametric 3D modeler
        for

        CAD, MCAD, CAx, CAE and PLM, aimed directly at mechanical engineering

        and product design but also fits a wider range of uses in engineering,

        such as architecture or other engineering specialties. It is 100% Open

        Source (LGPL2+ license) and extremely modular, allowing for very

        advanced extension and customization.

        FreeCAD is based on OpenCASCADE, a powerful geometry kernel, features an

        Open Inventor-compliant 3D scene representation model provided by the

        Coin 3D library, and a broad Python API. The interface is built with Qt.

        FreeCAD runs exactly the same way on Windows, Mac OSX, BSD and Linux

        platforms.

        '
    dev_url: https://github.com/FreeCAD/FreeCAD
    doc_url: https://www.freecadweb.org/wiki/Main_Page
    home: https://www.freecadweb.org/
    license: LGPL2.1
    license_family: LGPL
    license_file: LICENSE
    summary: 'FreeCAD is a parametric 3D modeler made primarily to design real-life
        objects of any size. '
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - looooo
