# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00002t0ro0d\tmp\build\80754af9\rsync-recipes\zlib-1.2.11-on-winbuilder, last modified Sat Apr 18 03:27:15 2020
# ------------------------------------------------

package:
    name: zlib
    version: 1.2.11
source:
    sha256: c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1
    url: http://zlib.net/zlib-1.2.11.tar.gz
build:
    number: '4'
    run_exports:
        - zlib >=1.2.11,<1.3.0a0
    string: h62dcd97_4
requirements:
    build:
        - cmake 3.14.0 h33f27b4_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
        - vs2017_win-64 19.16.27032.1 hb8d98e7_1
        - vswhere 2.7.1 h21ff451_0
    host:
        - ripgrep 11.0.2 0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
    run:
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
about:
    description: 'zlib is designed to be a free, general-purpose, lossless data-compression

        library for use on virtually any computer hardware and operating system.

        '
    dev_url: https://github.com/madler/zlib
    doc_url: http://zlib.net/manual.html
    home: http://zlib.net/
    license: zlib
    license_family: Other
    license_file: license.txt
    summary: Massively spiffy yet delicately unobtrusive compression library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - groutr
        - mingwandroid
        - msarahan
        - ocefpaf
