# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/nltk-3.5-on-linux_64, last modified Thu Jun 18 15:58:36 2020
# ------------------------------------------------

package:
    name: nltk
    version: '3.5'
source:
    sha256: 845365449cd8c5f9731f7cb9f8bd6fd0767553b9d53af9eb1b3abf7700936b35
    url: https://pypi.io/packages/source/n/nltk/nltk-3.5.zip
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/nltk_1592496090529/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
        -m pip install . --no-deps -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.2 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.3 he6710b0_1
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.1.1 py38_1
        - python 3.8.3 hcff3b4d_0
        - readline 8.0 h7b6447c_0
        - setuptools 47.3.0 py38_0
        - sqlite 3.31.1 h62c20be_1
        - tk 8.6.8 hbc83047_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - click
        - joblib
        - python >=3.5
        - regex
        - tqdm
test:
    imports:
        - nltk
        - nltk.app
        - nltk.ccg
        - nltk.chat
        - nltk.chunk
        - nltk.classify
        - nltk.cluster
        - nltk.corpus
        - nltk.corpus.reader
        - nltk.draw
        - nltk.inference
        - nltk.metrics
        - nltk.misc
        - nltk.parse
        - nltk.sem
        - nltk.sentiment
        - nltk.stem
        - nltk.tag
        - nltk.tbl
        - nltk.test
        - nltk.test.unit
        - nltk.test.unit.translate
        - nltk.tokenize
        - nltk.translate
        - nltk.twitter
about:
    description: 'NLTK has been called a wonderful tool for teaching and working in

        computational linguistics using Python and an amazing library to play with

        natural language.

        '
    dev_url: https://github.com/nltk/nltk
    doc_source_url: https://github.com/nltk/nltk/blob/develop/web/index.rst
    doc_url: http://www.nltk.org/
    home: http://nltk.org/
    license: Apache 2.0
    license_family: Apache
    license_file: LICENSE.txt
    summary: Natural Language Toolkit
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pmlandwehr
        - quartox
