# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00000sildjb\tmp\build\80754af9\rsync-recipes\sqlite-3.33.0-on-winbuilder, last modified Thu Aug 20 07:57:11 2020
# ------------------------------------------------

package:
    name: sqlite
    version: 3.33.0
source:
    -   folder: amalgamated
        patches:
            - patches/applicable-to-amalgamated/0001-expose_symbols.patch
        sha256: 106a2c48c7f75a298a7557bcc0d5f4f454e5b43811cc738b7ca294d6956bbb15
        url: https://www.sqlite.org/2020/sqlite-autoconf-3330000.tar.gz
build:
    number: '0'
    run_exports:
        - sqlite >=3.33.0,<4.0a0
    string: h2a8f88b_0
requirements:
    build:
        - m2-gcc-libs 5.3.0 4
        - m2-msys2-runtime 2.5.0.17080.65c939c 3
        - m2-patch 2.7.5 2
        - msys2-conda-epoch 20160418 1
        - vs2017_win-64 19.16.27032.1 hb4161e2_3
        - vswhere 2.7.1 h21ff451_0
    host:
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - zlib 1.2.11 h62dcd97_4
    run:
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - sqlite3 --version
        - if not exist %PREFIX%\\Library\bin\sqlite3.dll exit 1
        - if not exist %PREFIX%\\Library\lib\sqlite3.lib exit 1
        - if not exist %PREFIX%\\Library\include\sqlite3.h exit 1
about:
    description: 'SQLite is a self-contained, high-reliability, embedded, full-featured,

        public-domain, SQL database engine.It is the most used database engine

        in the world.

        '
    dev_url: https://github.com/mackyle/sqlite
    doc_source_url: https://github.com/mackyle/sqlite/tree/master/doc
    doc_url: http://www.sqlite.org/docs.html
    home: http://www.sqlite.org/
    license: Public-Domain (http://www.sqlite.org/copyright.html)
    license_url: http://www.sqlite.org/copyright.html
    summary: Implements a self-contained, zero-configuration, SQL database engine
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - ocefpaf
        - snorfalorpagus
