# This file created by conda-build 3.20.2
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Mon Sep 28 16:49:22 2020
# ------------------------------------------------

package:
    name: jupyter_client
    version: 6.1.7
source:
    sha256: 49e390b36fe4b4226724704ea28d9fb903f1a3601b6882ce3105221cd09377a1
    url: https://pypi.io/packages/source/j/jupyter_client/jupyter_client-6.1.7.tar.gz
build:
    entry_points:
        - jupyter-kernel = jupyter_client.kernelapp:main
        - jupyter-kernelspec = jupyter_client.kernelspecapp:KernelSpecApp.launch_instance
        - jupyter-run = jupyter_client.runapp:main
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/jupyter_client_1601311786391/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
        -m pip install . --no-deps -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1h h7b6447c_0
        - pip 20.2.2 py38_0
        - python 3.8.5 h7579374_1
        - readline 8.0 h7b6447c_0
        - setuptools 49.6.0 py38_1
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - jupyter_core >=4.6.0
        - python >=3.5
        - python-dateutil >=2.1
        - pyzmq >=13
        - tornado >=4.1
        - traitlets
test:
    commands:
        - python -m pip check
        - jupyter kernelspec list
        - jupyter run -h
        - pytest --pyargs jupyter_client --cov jupyter_client
    imports:
        - jupyter_client
    requires:
        - async_generator
        - ipykernel
        - ipython
        - mock
        - pip
        - pytest
        - pytest-asyncio
        - pytest-cov
        - pytest-timeout
about:
    dev_url: https://github.com/jupyter/jupyter_client
    doc_source_url: https://github.com/jupyter/jupyter_client/tree/master/docs
    doc_url: https://jupyter-client.readthedocs.io/en/stable/
    home: https://jupyter.org
    license: BSD-3-Clause
    license_family: BSD
    license_file: COPYING.md
    summary: jupyter_client contains the reference implementation of the Jupyter protocol.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - SylvainCorlay
        - bollwyvl
        - carreau
        - jakirkham
        - minrk
        - ocefpaf
        - pelson
