# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# C:\ci\containers\000015220rf\tmp\build\80754af9\combined_recipe, last modified Wed Sep 30 11:33:18 2020
# ------------------------------------------------

package:
    name: keyring
    version: 21.4.0
source:
    sha256: 9aeadd006a852b78f4b4ef7c7556c2774d2432bbef8ee538a3e9089ac8b11466
    url: https://pypi.io/packages/source/k/keyring/keyring-21.4.0.tar.gz
build:
    entry_points:
        - keyring = keyring.cli:main
    number: '1'
    script: C:\\ci\\keyring_1601488971022\\_h_env\\python.exe -m pip install . --no-deps
        -vv
    string: py37_1
requirements:
    host:
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py37_0
        - openssl 1.1.1h he774522_0
        - pip 20.2.2 py37_0
        - python 3.7.9 h60c2a47_0
        - setuptools 49.6.0 py37_1
        - setuptools-scm 4.1.2 py_0
        - setuptools_scm 4.1.2 0
        - sqlite 3.33.0 h2a8f88b_0
        - toml 0.10.1 py_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - wheel 0.35.1 py_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - importlib_metadata
        - python >=3.7,<3.8.0a0
        - pywin32-ctypes
test:
    commands:
        - pip check
        - py.test -v tests
        - keyring --help
    imports:
        - keyring
        - keyring.backends
        - keyring.util
    requires:
        - pip
        - pytest >=2.8
        - pytest-runner
        - setuptools_scm >=1.15.0
    source_files:
        - tests/*
about:
    description: 'the python keyring lib provides a easy way to access the system
        keyring

        service from python.  it can be used in any application that needs safe

        password storage.

        '
    doc_source_url: https://github.com/jaraco/keyring/blob/master/readme.rst
    doc_url: https://pypi.org/project/keyring/
    home: https://github.com/jaraco/keyring
    license: Python Software Foundation or MIT
    license_family: MIT
    license_file: LICENSE
    summary: Store and access your passwords safely
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - ericdill
        - licode
        - tacaswell
