# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\0000325qdpd\tmp\build\80754af9\rsync-recipes\pillow-7.2.0-python_3.7-on-winbuilder, last modified Thu Jul  9 08:04:42 2020
# ------------------------------------------------

package:
    name: pillow
    version: 7.2.0
source:
    sha256: 97f9e7953a77d5a70f49b9a48da7776dc51e9b738151b22dacf101641594a626
    url: https://pypi.io/packages/source/P/Pillow/Pillow-7.2.0.tar.gz
build:
    number: '0'
    string: py37hcc1f983_0
requirements:
    build:
        - vs2017_win-64 19.16.27032.1 hb4161e2_3
        - vswhere 2.7.1 h21ff451_0
    host:
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py37_0
        - freetype 2.9.1 ha9979f8_1
        - jpeg 9b hb83a4c4_2
        - libpng 1.6.37 h2a8f88b_0
        - libtiff 4.1.0 h56a325e_1
        - lz4-c 1.9.2 h62dcd97_0
        - openssl 1.1.1g he774522_0
        - pip 20.1.1 py37_1
        - python 3.7.7 h81c818b_4
        - setuptools 47.3.1 py37_0
        - sqlite 3.32.3 h2a8f88b_0
        - tk 8.6.10 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - wheel 0.34.2 py37_0
        - wincertstore 0.2 py37_0
        - xz 5.2.5 h62dcd97_0
        - zlib 1.2.11 h62dcd97_4
        - zstd 1.4.4 ha9fde0e_3
    run:
        - freetype >=2.9.1,<3.0a0
        - jpeg >=9b,<10a
        - libtiff >=4.1.0,<5.0a0
        - olefile
        - python >=3.7,<3.8.0a0
        - tk >=8.6.10,<8.7.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    imports:
        - PIL
        - PIL.Image
        - PIL._imaging
        - PIL._imagingft
        - PIL._imagingmath
        - PIL._imagingmorph
about:
    description: 'Pillow is the friendly PIL fork. PIL is the Python Imaging Library,

        adds image processing capabilities to your Python interpreter.

        '
    dev_url: https://github.com/python-pillow/Pillow
    doc_source_url: https://github.com/python-pillow/Pillow/blob/4.2.x/docs/index.rst
    doc_url: http://pillow.readthedocs.io/en/4.2.x/
    home: https://pillow.readthedocs.io
    license: LicenseRef-PIL
    license_file: LICENSE
    summary: Pillow is the friendly PIL fork by Alex Clark and Contributors
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - ocefpaf
        - patricksnape
        - pelson
