# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00003fjors0\tmp\build\80754af9\pull-recipes-nose\recipe, last modified Fri Jul 10 11:39:51 2020
# ------------------------------------------------

package:
    name: nose
    version: 1.3.7
source:
    md5: 4d3ad0ff07b61373d2cefc89c5d0b20b
    patches:
        - win-rmentry.patch
    url: https://pypi.io/packages/source/n/nose/nose-1.3.7.tar.gz
build:
    entry_points:
        - nosetests = nose:run_exit
    number: '1004'
    string: py37_1004
requirements:
    host:
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py37_0
        - openssl 1.1.1g he774522_0
        - pip 20.1.1 py37_1
        - python 3.7.7 h81c818b_4
        - setuptools 47.3.1 py37_0
        - sqlite 3.32.3 h2a8f88b_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - wheel 0.34.2 py37_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - python >=3.7,<3.8.0a0
        - setuptools
test:
    commands:
        - nosetests -h
    imports:
        - nose
        - pkg_resources
about:
    description: 'NOTE: Nose has been in maintenance mode for the past several years
        and will

        likely cease without a new person/team to take over maintainership. New

        projects should consider using Nose2, py.test, or just plain

        unittest/unittest2.

        '
    dev_url: https://github.com/nose-devs/nose/
    doc_source_url: https://github.com/nose-devs/nose/blob/master/doc/index.rst
    doc_url: https://nose.readthedocs.org
    home: http://readthedocs.org/docs/nose/
    license: LGPL-2.1
    license_file: lgpl.txt
    summary: Nose extends unittest to make testing easier
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - msarahan
        - ocefpaf
        - scopatz
