# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/jinja2-2.11.2-on-linux_64, last modified Wed Apr 29 14:28:46 2020
# ------------------------------------------------

package:
    name: jinja2
    version: 2.11.2
source:
    fn: Jinja2-2.11.2.tar.gz
    sha256: 89aab215427ef59c34ad58735269eb58b1a5808103067f7bb9d5836c651b3bb0
    url: https://pypi.io/packages/source/J/Jinja2/Jinja2-2.11.2.tar.gz
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/jinja2_1588170652563/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
        -m pip install . --no-deps -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.1.1 0
        - certifi 2019.11.28 py27_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.3 he6710b0_1
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_0
        - pip 19.3.1 py27_0
        - python 2.7.18 h15b4118_1
        - readline 8.0 h7b6447c_0
        - setuptools 44.0.0 py27_0
        - sqlite 3.31.1 h62c20be_1
        - tk 8.6.8 hbc83047_0
        - wheel 0.33.6 py27_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - markupsafe >=0.23
        - python
        - setuptools
test:
    imports:
        - jinja2
about:
    description: 'Jinja2 is a full featured template engine for Python. It has full
        unicode

        support, an optional integrated sandboxed execution environment, widely

        used and BSD licensed.

        '
    dev_url: https://github.com/pallets/jinja
    doc_source_url: https://github.com/pallets/jinja/blob/master/docs/index.rst
    doc_url: http://jinja.pocoo.org/docs/dev/
    home: http://jinja.pocoo.org
    license: 3-Clause BSD
    license_file: LICENSE.rst
    summary: An easy to use stand-alone template engine written in pure python.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - msarahan
        - nehaljwani
        - scopatz
