# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/pull-recipes-imageio/recipe, last modified Tue Jul  7 22:36:16 2020
# ------------------------------------------------

package:
    name: imageio
    version: 2.9.0
source:
    sha256: 52ddbaeca2dccf53ba2d6dec5676ca7bc3b2403ef8b37f7da78b7654bb3e10f0
    url: https://pypi.io/packages/source/i/imageio/imageio-2.9.0.tar.gz
build:
    entry_points:
        - imageio_download_bin = imageio.__main__:download_bin_main
        - imageio_remove_bin = imageio.__main__:remove_bin_main
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/imageio_1594161405741/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
        -m pip install . --no-deps --ignore-installed -vvv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h7b6447c_0
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.1.1 py38_1
        - python 3.8.3 hcff3b4d_2
        - readline 8.0 h7b6447c_0
        - setuptools 47.3.1 py38_0
        - sqlite 3.32.3 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - numpy
        - pillow
        - python >=3
test:
    commands:
        - imageio_download_bin -h
        - imageio_remove_bin -h
    imports:
        - imageio
about:
    dev_url: https://github.com/imageio/imageio
    doc_url: https://imageio.readthedocs.io
    home: https://imageio.github.io
    license: BSD-2-Clause
    license_file: LICENSE
    summary: A Python library for reading and writing image data
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - almarklein
        - blink1073
        - jni
