# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\0000218nnus\tmp\build\80754af9\rsync-recipes\scikit-learn-0.23.2-python_3.7-on-winbuilder, last modified Tue Aug 25 12:32:06 2020
# ------------------------------------------------

package:
    name: scikit-learn
    version: 0.23.2
source:
    sha256: 26f56e0c5aac4811f5a90109c4eed0396ee196d8383608b9bf33129528e6fcfd
    url: https://github.com/scikit-learn/scikit-learn/archive/0.23.2.tar.gz
build:
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .  --verbose
    string: py37h47e9c7a_0
requirements:
    build:
        - vs2017_win-64 19.16.27032.1 hb4161e2_3
        - vswhere 2.7.1 h21ff451_0
    host:
        - blas 1.0 mkl
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py37_0
        - cython 0.29.21 py37ha925a31_0
        - icc_rt 2019.0.0 h0cc432a_1
        - intel-openmp 2019.4 245
        - joblib 0.16.0 py_0
        - mkl 2019.4 245
        - mkl-service 2.3.0 py37hb782905_0
        - mkl_fft 1.0.14 py37h6288b17_0
        - mkl_random 1.0.4 py37h343c172_0
        - numpy 1.14.6 py37ha06f490_5
        - numpy-base 1.14.6 py37hc3f5095_5
        - openssl 1.1.1g he774522_1
        - pip 20.2.2 py37_0
        - python 3.7.7 h81c818b_4
        - scipy 1.5.2 py37h9439919_0
        - setuptools 49.6.0 py37_0
        - six 1.15.0 py_0
        - sqlite 3.33.0 h2a8f88b_0
        - threadpoolctl 2.1.0 pyh5ca1d4c_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - wheel 0.34.2 py37_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - joblib >=0.11
        - numpy >=1.14.6,<2.0a0
        - python >=3.7,<3.8.0a0
        - scipy
        - threadpoolctl
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    commands:
        - set OPENBLAS_NUM_THREADS=1
        - set OMP_NUM_THREADS=1
        - pytest --timeout 300 -n 1 --verbose --pyargs sklearn -k "not (_not_a_real_test
            or network or test_california_housing)"
    imports:
        - sklearn
    requires:
        - cython >=0.28.5
        - pytest >=3.3.0
        - pytest-timeout
        - pytest-xdist
about:
    home: http://scikit-learn.org/
    license: BSD-3-Clause
    license_file: COPYING
    summary: A set of python modules for machine learning and data mining
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - adrinjalali
        - amueller
        - astaric
        - jakirkham
        - jnothman
        - lesteve
        - msarahan
        - ocefpaf
        - ogrisel
        - rth
