# This file created by conda-build 3.20.4
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/prompt-toolkit-3.0.8-on-linux_64, last modified Wed Oct 14 15:18:47 2020
# ------------------------------------------------

package:
    name: prompt-toolkit
    version: 3.0.8
source:
    sha256: 25c95d2ac813909f813c93fde734b6e44406d1477a9faef7c915ff37d39c0a8c
    url: https://pypi.io/packages/source/p/prompt_toolkit/prompt_toolkit-3.0.8.tar.gz
build:
    noarch: python
    number: '0'
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.10.14 0
        - certifi 2020.6.20 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1h h7b6447c_0
        - pip 20.2.3 py38_0
        - python 3.8.5 h7579374_1
        - readline 8.0 h7b6447c_0
        - setuptools 50.3.0 py38hb0f4dca_1
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - pygments
        - python >=3.6
        - wcwidth
    run_constrained:
        - prompt_toolkit 3.0.8
about:
    description: 'prompt_toolkit is a library for building powerful interactive command

        lines and terminal applications in Python. It can be a pure Python

        replacement for GNU readline, but it can be much more than that.

        '
    dev_url: https://github.com/jonathanslenders/python-prompt-toolkit
    doc_url: http://python-prompt-toolkit.readthedocs.io
    home: https://github.com/jonathanslenders/python-prompt-toolkit
    license: BSD-3-Clause
    license_file: LICENSE
    summary: Library for building powerful interactive command lines in Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - asmeurer
        - jakirkham
        - ocefpaf
        - scopatz
