# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Thu Aug  6 11:10:01 2020
# ------------------------------------------------

package:
    name: ffmpeg
    version: 4.3.1
source:
    -   sha256: dd29b7f92f48dead4dd940492c7509138c0f99db445076d0a597007298a79940
        url: https://ffmpeg.zeranoe.com/builds/win64/shared/ffmpeg-4.3.1-win64-shared.zip
    -   sha256: 2e8038242cf8e1bd095c2978f196ff0462b122cc6ef7e74626a6af15459d8b81
        url: https://ffmpeg.zeranoe.com/builds/win64/dev/ffmpeg-4.3.1-win64-dev.zip
build:
    number: '0'
    run_exports:
        - ffmpeg >=4.3.1,<4.4.0a0
    string: ha925a31_0
requirements:
    build:
        - vs2017_win-64 19.16.27038 h2e3bad8_2
        - vswhere 2.7.1 h21ff451_0
    host:
        - vc 14.1 h869be7e_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
    run:
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012
test:
    commands:
        - ffmpeg --help
about:
    home: http://www.ffmpeg.org/
    license: GPL-3.0-or-later
    summary: Cross-platform solution to record, convert and stream audio and video.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - 183amir
        - carlodri
        - caspervdw
        - danielballan
        - jakirkham
        - ocefpaf
        - patricksnape
        - sdvillal
