# This file created by conda-build 3.20.2
# meta.yaml template originally from:
# C:\ci\containers\00000iroi4t\tmp\build\80754af9\combined_recipe, last modified Fri Sep 25 10:48:17 2020
# ------------------------------------------------

package:
    name: libuv
    version: 1.40.0
source:
    fn: libuv-v1.40.0.tar.gz
    patches:
        - 0001-Skip-the-single-bit-that-fails-in-test-fs-copyfile-w.patch
    sha256: 70fe1c9ba4f2c509e8166c0ca2351000237da573bb6c82092339207a9715ba6b
    url: https://github.com/libuv/libuv/archive/v1.40.0.tar.gz
build:
    number: '0'
    run_exports:
        - libuv >=1.40.0,<2.0a0
    string: he774522_0
requirements:
    build:
        - vs2017_win-64 19.16.27032.1 hb4161e2_3
        - vswhere 2.7.1 h21ff451_0
    host:
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
    run:
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    commands:
        - test -f "%PREFIX%/Library/include/uv.h"
about:
    description: 'libuv is a multi-platform support library with a focus on asynchronous
        I/O.

        It was primarily developed for use by Node.js, but it''s also used by Luvit,

        Julia, pyuv, and others.

        '
    dev_url: https://github.com/libuv/libuv
    doc_source_url: https://github.com/libuv/libuv/tree/v1.x/docs
    doc_url: http://docs.libuv.org/
    home: http://libuv.org/
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: Cross-platform asynchronous I/O
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - frol
        - mariusvniekerk
