# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/wcwidth-0.2.5-on-linux_64, last modified Mon Jun 29 16:11:44 2020
# ------------------------------------------------

package:
    name: wcwidth
    version: 0.2.5
source:
    sha256: c4d647b99872929fdb7bdcaa4fbe7f01413ed3d98077df798530e5b04f116c83
    url: https://pypi.io/packages/source/w/wcwidth/wcwidth-0.2.5.tar.gz
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/wcwidth_1593447189090/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
        -m pip install . -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.1.1 0
        - certifi 2020.6.20 py36_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h7b6447c_0
        - libffi 3.3 he6710b0_1
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.1.1 py36_1
        - python 3.6.10 h7579374_2
        - readline 8.0 h7b6447c_0
        - setuptools 47.3.1 py36_0
        - sqlite 3.32.3 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.34.2 py36_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python
test:
    commands:
        - pip check
    imports:
        - wcwidth
    requires:
        - pip
about:
    home: https://github.com/jquast/wcwidth
    license: MIT
    license_file: LICENSE
    summary: Measures number of Terminal column cells of wide-character codes.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
