# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/pull-recipes-autopep8/recipe, last modified Tue Aug  4 21:55:33 2020
# ------------------------------------------------

package:
    name: autopep8
    version: 1.5.4
source:
    sha256: d21d3901cb0da6ebd1e83fc9b0dfbde8b46afc2ede4fe32fbda0c7c6118ca094
    url: https://pypi.io/packages/source/a/autopep8/autopep8-1.5.4.tar.gz
build:
    entry_points:
        - autopep8 = autopep8:main
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/autopep8_1596578164842/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
        -m pip install . -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py37_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.1.1 py37_1
        - python 3.7.7 hcff3b4d_5
        - readline 8.0 h7b6447c_0
        - setuptools 49.2.0 py37_0
        - sqlite 3.32.3 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.34.2 py37_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - pycodestyle >=2.6
        - python
        - toml
test:
    commands:
        - pip check
        - autopep8 --help
    imports:
        - autopep8
    requires:
        - pip
about:
    dev_url: https://github.com/hhatto/autopep8
    home: https://github.com/hhatto/autopep8
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: A tool that automatically formats Python code to conform to the PEP 8
        style guide
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
        - pmlandwehr
