c_compiler: vs2017
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
curl: '7'
cxx_compiler: vs2017
extend_keys:
- extend_keys
- ignore_version
- pin_run_as_build
- ignore_build_only_deps
fortran_compiler: gfortran
icu: '67'
ignore_build_only_deps:
- python
- numpy
jpeg: '9'
libpng: '1.6'
lua: '5'
numpy: '1.11'
openssl: 1.1.1
perl: 5.26.2
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  curl:
    max_pin: x
  icu:
    max_pin: x
  jpeg:
    max_pin: x
  libpng:
    max_pin: x.x
  openssl:
    max_pin: x.x.x
  sqlite:
    max_pin: x
  zlib:
    max_pin: x.x
python: '3.8'
r_base: '3.4'
sqlite: '3'
target_platform: win-64
vc: '14'
zlib: '1.2'
