# This file created by conda-build 3.20.2
# meta.yaml template originally from:
# C:\Users\isuru\projects\qt-feedstock\recipe, last modified Tue Oct  6 05:42:48 2020
# ------------------------------------------------

package:
    name: qt
    version: 5.12.9
source:
    -   md5: fa2646280cf38180689c29c393cddd05
        patches:
            - patches/0001-qtbase-osx-xctest-check.patch
            - patches/0001-qtscript-mark-cti_vm_throw-as-REFERENCED_FROM_ASM.patch
            - patches/0001-qtwebengine-allow-any-xcblah-in-PATH.patch
            - patches/0001-shobjidl-Fix-compile-guard-around-SHARDAPPIDINFOLINK.patch
            - patches/0002-qtbase-osx-allow-any-xcrun-in-PATH.patch
            - patches/0002-qtwebengine-find_sdk-respect-CONDA_BUILD_SYSROOT.patch
            - patches/0003-qtbase-use-better-clang-optimize-size.patch
            - patches/0004-qtbase-never-enable-new-dtags.patch
            - patches/0004-qtwebengine-use-CONDA_PREFIX_include-for-system_libjpeg.patch
            - patches/0005-qtbase-link-xcb-shm.patch
            - patches/0005-qtwebengine-jpeg-codec-cannot-convert-bool-to-boolean.patch
            - patches/0006-qtbase-Do-not-set-PKG_CONFIG_SYSROOT_DIR-when-sysroo.patch
            - patches/0006-qtwebengine-run-gn-verbosely.patch
            - patches/0007-qtbase-Disable-kTLSProtocol13-for-macOS-10.12.patch
            - patches/0008-qtbase-Define-kIOSurfaceSuccess-if-it-is-not-defined.patch
            - patches/0008-qtwebengine-link-gn-to-librt.patch
            - patches/0009-qtbase-fix-hardcoded-sysroot-path.patch
            - patches/0009-qtwebengine-Add-conda_prefix-to-features-gni-declare_args.patch
            - patches/0010-qtwebengine-Use-conda_prefix-for-system-zlib.patch
            - patches/0011-qtwebengine-Use-conda_prefix-for-ui-gl.patch
            - patches/0012-qtwebengine-Ignore-glibc-2-17-min-version-check.patch
            - patches/0013-qtwebengine-missing_EVIOCGPROP.diff
            - patches/0014-qtwebengine-HAVE_SENDMMSG.diff
            - patches/qcore_for_sdk_10_13_1.patch
        url: http://download.qt.io/official_releases/qt/5.12/5.12.9/single/qt-everywhere-src-5.12.9.tar.xz
    -   folder: opengl32sw
        sha256: 2a0d2f92c60e0962ef5f6039d3793424c6f39e49ba27ac04a5b21ca4ae012e15
        url: http://download.qt.io/development_releases/prebuilt/llvmpipe/windows/opengl32sw-64-mesa_12_0_rc2.7z
build:
    detect_binary_files_with_prefix: true
    number: '0'
    run_exports:
        - qt >=5.12.9,<5.13.0a0
    string: hb2cf2c5_0
requirements:
    build:
        - ca-certificates 2020.6.20 hecda079_0
        - curl 7.71.1 h4b64cdc_8
        - jom 1.1.3 0
        - krb5 1.17.1 hc04afaa_3
        - libcurl 7.71.1 h4b64cdc_8
        - libssh2 1.9.0 hb06d900_5
        - m2-bash 4.3.042 5
        - m2-bison 3.0.4 2
        - m2-flex 2.6.0 2
        - m2-gcc-libs 5.3.0 4
        - m2-gperf 3.0.4 4
        - m2-gzip 1.7 2
        - m2-info 6.0 2
        - m2-less 481 2
        - m2-libiconv 1.14 3
        - m2-libintl 0.19.7 4
        - m2-libpcre 8.38 2
        - m2-m4 1.4.17 5
        - m2-msys2-runtime 2.5.0.17080.65c939c 3
        - m2-ncurses 6.0.20160220 2
        - m2-patch 2.7.5 2
        - msys2-conda-epoch 20160418 1
        - ninja 1.10.1 h7ef1ec2_1
        - openssl 1.1.1h he774522_0
        - perl 5.30.3.1 he774522_1
        - tk 8.6.10 he774522_0
        - vc 14.1 h869be7e_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - vs2017_win-64 19.16.27038 h2e3bad8_2
        - vswhere 2.7.1 h21ff451_0
        - zlib 1.2.11 h62dcd97_1009
    host:
        - ca-certificates 2020.6.20 hecda079_0
        - clang 10.0.1 default_hf44288c_1
        - clang-tools 10.0.1 default_hf44288c_1
        - clangdev 10.0.1 default_hf44288c_1
        - clangxx 10.0.1 default_hf44288c_1
        - icu 67.1 h33f27b4_0
        - jpeg 9d he774522_0
        - libclang 10.0.1 default_hf44288c_1
        - libclang-cpp 10.0.1 default_hf44288c_1
        - libllvm10 10.0.1 hde8ddfe_3
        - libpng 1.6.37 ha81a0f5_2
        - llvm-tools 10.0.1 hde8ddfe_3
        - llvmdev 10.0.1 hde8ddfe_3
        - openssl 1.1.1h he774522_0
        - sqlite 3.33.0 he774522_0
        - vc 14.1 h869be7e_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - zlib 1.2.11 h62dcd97_1009
    run:
        - icu >=67.1,<68.0a0
        - jpeg >=9d,<10a
        - libclang >=10.0.1,<11.0a0
        - libpng >=1.6.37,<1.7.0a0
        - openssl >=1.1.1h,<1.1.2a
        - openssl >=1.1.1h,<1.1.2a
        - sqlite >=3.33.0,<4.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - if not exist %LIBRARY_BIN%\\Qt5WebEngine.dll exit 1
        - if not exist %LIBRARY_PREFIX%\plugins\sqldrivers\qsqlite.dll exit 1
    files:
        - test/hello.pro
        - test/main-qtwebengine.cpp
        - test/main.cpp
        - test/main.qml
        - test/qml.qrc
        - test/qrc_qml.cpp
        - test/qtwebengine.pro
        - xcodebuild
        - xcrun
    requires:
        - vs2017_win-64
about:
    description: 'Qt helps you create connected devices, UIs & applications that run

        anywhere on any device, on any operating system at any time.

        '
    dev_url: https://github.com/qtproject
    doc_url: http://doc.qt.io/
    home: http://qt-project.org
    license: LGPL-3.0-only
    license_file: LICENSE.LGPLv3
    summary: Qt is a cross-platform application and UI framework.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - gillins
        - mingwandroid
        - msarahan
        - ocefpaf
        - stuarteberg
