# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00000r5sf9d\tmp\build\80754af9\rsync-recipes\xz-5.2.5-on-winbuilder, last modified Wed Apr 15 16:55:04 2020
# ------------------------------------------------

package:
    name: xz
    version: 5.2.5
source:
    patches:
        - 0001-Add-vs2008-support-via-cmake.patch
        - 0002-Add-gettimeofday-for-VS2008.patch
    sha256: 5117f930900b341493827d63aa910ff5e011e0b994197c3b71c08a20228a42df
    url: http://downloads.sourceforge.net/project/lzmautils/xz-5.2.5.tar.bz2
build:
    number: '0'
    run_exports:
        - xz >=5.2.5,<6.0a0
    string: h62dcd97_0
requirements:
    build:
        - ca-certificates 2020.1.1 0
        - cmake 3.14.0 h33f27b4_0
        - ninja 1.9.0 py38h74a9793_0
        - openssl 1.1.1f he774522_0
        - python 3.8.2 h5fd99cc_11
        - sqlite 3.31.1 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
        - vs2017_win-64 19.16.27032.1 hb8d98e7_1
        - vswhere 2.7.1 h21ff451_0
    host:
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
    run:
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    commands:
        - xz.exe --help
        - unxz.exe --help
        - if not exist %PREFIX%\\Library\\bin\\liblzma.dll exit 1
        - if not exist %PREFIX%\\Library\\lib\\liblzma.lib exit 1
        - if not exist %PREFIX%\\Library\\lib\\liblzma_static.lib exit 1
        - if not exist %PREFIX%\\Library\\include\\lzma.h exit 1
about:
    description: 'XZ Utils is free general-purpose data compression software with
        a high

        compression ratio. XZ Utils were written for POSIX-like systems, but also

        work on some not-so-POSIX systems.

        '
    dev_url: http://git.tukaani.org/
    doc_source_url: https://github.com/xz-mirror/xz/blob/master/README
    doc_url: http://tukaani.org/xz/
    home: http://tukaani.org/xz/
    license: LGPL-2.1 and GPL-2.0
    license_file: COPYING
    summary: Data compression software with high compression ratio
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mingwandroid
        - msarahan
        - nehaljwani
        - ocefpaf
        - scopatz
