# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00002t0ro0i\tmp\build\80754af9\rsync-recipes\libarchive-3.4.2-on-winbuilder, last modified Sat Apr 18 01:54:45 2020
# ------------------------------------------------

package:
    name: libarchive
    version: 3.4.2
source:
    patches:
        - patches/0001-Add-lib-to-CMAKE_FIND_LIBRARY_PREFIXES-for-lzma.patch
        - patches/0002-VC9-compatibility-test-for-BCryptDeriveKeyPBKDF2.patch
        - patches/0003-VC9-compatibility-define-BCRYPT_SUCCESS.patch
        - patches/0004-VC9-compatibility-openssl-define-inline-as-__inline.patch
        - patches/0005-VC9-compatibility-Ignore-some-warnings.patch
        - patches/0006-C99-compatibility-Remove-the-limited-amount-of-C99.patch
        - patches/0007-CMake-Force-Multi-threaded-DLL-runtime.patch
    sha256: b60d58d12632ecf1e8fad7316dc82c6b9738a35625746b47ecdcaf4aed176176
    url: https://github.com/libarchive/libarchive/releases/download/v3.4.2/libarchive-3.4.2.tar.gz
build:
    number: '0'
    run_exports:
        - libarchive >=3.4.2,<3.5.0a0
    string: h5e25573_0
requirements:
    build:
        - cmake 3.14.0 h33f27b4_0
        - jom 1.1.2 h3bd88b9_0
        - m2-msys2-runtime 2.5.0.17080.65c939c 3
        - m2-patch 2.7.5 2
        - msys2-conda-epoch 20160418 1
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
        - vs2017_win-64 19.16.27032.1 hb8d98e7_1
        - vswhere 2.7.1 h21ff451_0
    host:
        - bzip2 1.0.8 he774522_0
        - ca-certificates 2020.1.1 0
        - libiconv 1.15 h1df5818_7
        - libxml2 2.9.9 h464c3ec_0
        - lz4-c 1.9.2 h62dcd97_0
        - openssl 1.1.1f he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
        - xz 5.2.5 h62dcd97_0
        - zlib 1.2.11 h62dcd97_4
        - zstd 1.4.4 ha9fde0e_3
    run:
        - bzip2 >=1.0.8,<2.0a0
        - libiconv >=1.15,<2.0a0
        - libxml2 >=2.9.9,<2.10.0a0
        - lz4-c >=1.9.2,<1.10.0a0
        - openssl >=1.1.1f,<1.1.2a
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
        - xz >=5.2.5,<6.0a0
        - zlib >=1.2.11,<1.3.0a0
        - zstd >=1.4.4,<1.4.5.0a0
test:
    commands:
        - bsdcat --version
        - bsdcpio --version
        - bsdtar --version
        - pushd test-archives
        - bsdtar -vxf hello_world.xar 2>&1 | rg "x hello_world"
        - bsdtar -vxf archive.7z 2>&1 | rg "x 7zip-archive"
        - bsdtar -vxf hello_world.tar.zst 2>&1 | rg "greets"
        - popd
    files:
        - test-archives
    requires:
        - ripgrep
about:
    home: http://www.libarchive.org/
    license: BSD-2-Clause
    license_family: BSD
    license_file: COPYING
    summary: Multi-format archive and compression library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mingwandroid
        - ocefpaf
