CI: azure
bzip2: '1'
c_compiler: vs2017
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: vs2017
extend_keys:
- pin_run_as_build
- ignore_build_only_deps
- extend_keys
- ignore_version
fortran_compiler: gfortran
hdf5: 1.10.6
ignore_build_only_deps:
- numpy
- python
lua: '5'
numpy: '1.14'
perl: 5.26.0
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  bzip2:
    max_pin: x
  zlib:
    max_pin: x.x
python: 3.7.* *_cpython
r_base: '3.4'
target_platform: win-64
vc: '14'
zlib: '1.2'
