# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Thu Apr 16 10:17:17 2020
# ------------------------------------------------

package:
    name: pytables
    version: 3.6.1
source:
    patches:
        - do_not_copy_dlls_into_package.patch
        - remove_dll_check.patch
    sha256: 49a972b8a7c27a8a173aeb05f67acb45fe608b64cd8e9fa667c0962a60b71b49
    url: https://pypi.io/packages/source/t/tables/tables-3.6.1.tar.gz
build:
    entry_points:
        - pt2to3 = tables.scripts.pt2to3:main
        - ptdump = tables.scripts.ptdump:main
        - ptrepack = tables.scripts.ptrepack:main
        - pttree = tables.scripts.pttree:main
    number: '2'
    string: py37h2d87964_2
requirements:
    build:
        - blosc 1.18.1 h6538335_0
        - vc 14.1 h869be7e_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - vs2017_win-64 19.16.27038 h2e3bad8_2
        - vswhere 2.7.1 h21ff451_0
    host:
        - blosc 1.18.1 h6538335_0
        - bzip2 1.0.8 hfa6e2cd_2
        - ca-certificates 2020.4.5.1 hecc5488_0
        - certifi 2020.4.5.1 py37hc8dfbb8_0
        - cython 0.29.16 py37h63f7a3c_0
        - hdf5 1.10.6 nompi_ha405e13_100
        - intel-openmp 2020.0 166
        - libblas 3.8.0 15_mkl
        - libcblas 3.8.0 15_mkl
        - liblapack 3.8.0 15_mkl
        - mkl 2020.0 166
        - numexpr 2.7.1 py37h63f7a3c_1
        - numpy 1.14.6 py37hc71023c_1201
        - openssl 1.1.1f hfa6e2cd_0
        - pip 20.0.2 py_2
        - python 3.7.6 h60c2a47_5_cpython
        - python_abi 3.7 1_cp37m
        - setuptools 46.1.3 py37hc8dfbb8_0
        - sqlite 3.30.1 hfa6e2cd_0
        - vc 14.1 h869be7e_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - wheel 0.34.2 py_1
        - wincertstore 0.2 py37_1003
        - zlib 1.2.11 h2fa13f4_1006
    run:
        - blosc >=1.18.1,<2.0a0
        - bzip2 >=1.0.8,<2.0a0
        - bzip2 >=1.0.8,<2.0a0
        - hdf5 >=1.10.6,<1.10.7.0a0
        - mock
        - numexpr
        - numpy >=1.14.6,<2.0a0
        - python >=3.7,<3.8.0a0
        - python_abi 3.7.* *_cp37m
        - six
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - pt2to3 -h
        - ptdump -h
        - ptrepack -h
        - pttree -h
    requires:
        - mock
        - setuptools
about:
    description: 'PyTables is a package for managing hierarchical datasets and designed
        to

        efficiently and easily cope with extremely large amounts of data. PyTables

        is built on top of the HDF5 library, using the Python language and the

        NumPy package.

        '
    dev_url: https://github.com/PyTables
    doc_url: http://www.pytables.org/
    home: http://www.pytables.org
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: Brings together Python, HDF5 and NumPy to easily handle large amounts
        of data.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - msarahan
        - ocefpaf
        - scopatz
        - tomkooij
