# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# C:\ci\containers\0000201rrkm\tmp\build\80754af9\rsync-recipes\conda-package-handling-1.6.1-python_3.7-on-winbuilder, last modified Wed May  6 21:35:59 2020
# ------------------------------------------------

package:
    name: conda-package-handling
    version: 1.6.1
source:
    git_ref: 1.6.1
    git_url: https://github.com/conda/conda-package-handling
build:
    entry_points:
        - cph = conda_package_handling.cli:main
    missing_dso_whitelist:
        - '*/VCRUNTIME140.dll'
        - MSVCR90.dll
    number: '0'
    script: C:\ci\conda-package-handling_1588798509220\_h_env\python.exe -m pip install
        . --no-deps -vv
    string: py37h62dcd97_0
requirements:
    build:
        - vs2017_win-64 19.16.27032.1 hb8d98e7_1
        - vswhere 2.7.1 h21ff451_0
    host:
        - _libarchive_static_for_cph 3.3.3 he261513_0
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.1 py37_0
        - cython 0.29.17 py37ha925a31_0
        - openssl 1.1.1g he774522_0
        - pip 20.0.2 py37_1
        - python 3.7.7 h81c818b_4
        - setuptools 46.1.3 py37_0
        - sqlite 3.31.1 h2a8f88b_1
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
        - wheel 0.34.2 py37_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - python >=3.7,<3.8.0a0
        - six
        - tqdm
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    commands:
        - pytest tests
    imports:
        - conda_package_handling
        - conda_package_handling.archive_utils_cy
    requires:
        - mock
        - pytest
        - pytest-cov
        - pytest-mock
    source_files:
        - tests
about:
    home: https://github.com/conda/conda-package-handling
    license: BSD-3-Clause
    license_family: BSD
    license_file:
        - LICENSE
        - static_deps_licenses/bzip2.txt
        - static_deps_licenses/libarchive.txt
        - static_deps_licenses/zlib.txt
        - static_deps_licenses/zstd.txt
    summary: Create and extract conda packages of various formats
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jjhelmus
        - msarahan
