# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# C:\ci\containers\0000160bukj\tmp\build\80754af9\rsync-recipes\conda-4.9.2-python_3.7-on-winbuilder, last modified Tue Nov 10 21:28:10 2020
# ------------------------------------------------

package:
    name: conda
    version: 4.9.2
source:
    fn: conda-4.9.2.tar.gz
    sha256: d7f946e5c770e45da8961323ca96399bf1a881eb68bbaecc7cb1e249f5c86d54
    url: https://github.com/conda/conda/archive/4.9.2.tar.gz
build:
    always_include_files:
        - Scripts/activate
        - Scripts/activate.bat
        - Scripts/deactivate
    number: '0'
    string: py37haa95532_0
requirements:
    build:
        - m2-base 1.0.0 3
        - m2-bash 4.3.042 5
        - m2-bash-completion 2.3 2
        - m2-catgets 1.1 3
        - m2-coreutils 8.25 102
        - m2-dash 0.5.8 2
        - m2-file 5.25 2
        - m2-filesystem 2016.04 4
        - m2-findutils 4.6.0 2
        - m2-gawk 4.1.3 2
        - m2-gcc-libs 5.3.0 4
        - m2-gettext 0.19.7 4
        - m2-gmp 6.1.0 3
        - m2-grep 2.22 4
        - m2-gzip 1.7 2
        - m2-inetutils 1.9.2 2
        - m2-info 6.0 2
        - m2-less 481 2
        - m2-libasprintf 0.19.7 4
        - m2-libcatgets 1.1 3
        - m2-libcrypt 1.3 2
        - m2-libgettextpo 0.19.7 4
        - m2-libiconv 1.14 3
        - m2-libintl 0.19.7 4
        - m2-liblzma 5.2.2 2
        - m2-libpcre 8.38 2
        - m2-libreadline 6.3.008 8
        - m2-libutil-linux 2.26.2 2
        - m2-libxml2 2.9.2 3
        - m2-mintty 1!2.2.3 2
        - m2-mpfr 3.1.4 2
        - m2-msys2-launcher-git 0.3.28.860c495 2
        - m2-msys2-runtime 2.5.0.17080.65c939c 3
        - m2-ncurses 6.0.20160220 2
        - m2-sed 4.2.2 3
        - m2-tftp-hpa 5.2 2
        - m2-time 1.7 2
        - m2-ttyrec 1.0.8 2
        - m2-tzcode 2015.e 2
        - m2-util-linux 2.26.2 2
        - m2-which 2.21 3
        - m2-zlib 1.2.8 4
        - msys2-conda-epoch 20160418 1
    host:
        - ca-certificates 2020.10.14 0
        - certifi 2020.6.20 pyhd3eb1b0_3
        - conda-package-handling 1.7.2 py37h76e460a_0
        - menuinst 1.4.16 py37he774522_1
        - openssl 1.1.1h he774522_0
        - pip 20.2.4 py37haa95532_0
        - python 3.7.9 h60c2a47_0
        - pywin32 227 py37he774522_1
        - ruamel_yaml 0.15.87 py37he774522_1
        - setuptools 50.3.1 py37haa95532_1
        - six 1.15.0 py_0
        - sqlite 3.33.0 h2a8f88b_0
        - tqdm 4.50.2 py_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - wheel 0.35.1 py_0
        - wincertstore 0.2 py37_0
        - yaml 0.2.5 he774522_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - conda-package-handling >=1.3.0
        - menuinst >=1.4.11,<2
        - pycosat >=0.6.3
        - pyopenssl >=16.2.0
        - python >=3.7,<3.8.0a0
        - requests >=2.18.4,<3
        - ruamel_yaml >=0.11.14,<0.16
        - setuptools >=31.0.1
    run_constrained:
        - conda-build >=3
        - conda-env >=2.6
        - cytoolz >=0.8.1
test:
    downstreams:
        - conda-smithy
    files:
        - test_conda.bat
    imports:
        - conda
        - conda_env
    requires:
        - m2-base
        - m2-bash
        - m2-filesystem
        - mock
        - pexpect
        - pytest
        - responses
    source_files:
        - conftest.py
        - setup.cfg
        - tests
about:
    description: 'Conda is an open source package management system and environment
        management system for installing multiple versions of software packages and
        their dependencies and switching easily between them. It works on Linux, OS
        X and Windows, and was created for Python programs but can package and distribute
        any software.

        '
    dev_url: https://github.com/conda/conda
    doc_url: https://conda.io/projects/conda/en/latest/
    home: https://conda.io
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: OS-agnostic, system-level binary package and environment manager.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - chenghlee
        - jakirkham
        - jjhelmus
        - kalefranz
        - mbargull
        - mcg1969
        - mingwandroid
        - msarahan
        - mwcraig
        - ocefpaf
        - patricksnape
        - pelson
        - scopatz
