# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00001fa3ovv\tmp\build\80754af9\rsync-recipes\tk-8.6.10-on-winbuilder, last modified Thu Jun 18 18:57:42 2020
# ------------------------------------------------

package:
    name: tk
    version: 8.6.10
source:
    -   folder: tcl8.6.10
        sha256: 5196dbf6638e3df8d5c87b5815c8c2b758496eb6f0e41446596c9a4e638d87ed
        url: https://downloads.sourceforge.net/tcl/tcl8.6.10-src.tar.gz
    -   folder: tk8.6.10
        sha256: 63df418a859d0a463347f95ded5cd88a3dd3aaa1ceecaeee362194bc30f3e386
        url: https://downloads.sourceforge.net/tcl/tk8.6.10-src.tar.gz
build:
    detect_binary_files_with_prefix: true
    number: '0'
    run_exports:
        - tk >=8.6.10,<8.7.0a0
    string: he774522_0
requirements:
    build:
        - vs2017_win-64 19.16.27032.1 hb4161e2_2
        - vswhere 2.7.1 h21ff451_0
    host:
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_2
    run:
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    commands:
        - if not exist %LIBRARY_PREFIX%\\bin\\wish.exe exit 1
        - if not exist %LIBRARY_PREFIX%\\bin\\tclsh.exe exit 1
        - if not exist %LIBRARY_PREFIX%\\bin\\wish86.exe exit 1
        - if not exist %LIBRARY_PREFIX%\\bin\\tclsh86.exe exit 1
        - if not exist %LIBRARY_PREFIX%\\include\\tcl.h exit 1
        - if not exist %LIBRARY_PREFIX%\\include\\tclDecls.h exit 1
        - if not exist %LIBRARY_PREFIX%\\include\\tclPlatDecls.h exit 1
        - if not exist %LIBRARY_PREFIX%\\include\\tclPlatDecls.h exit 1
        - if not exist %LIBRARY_PREFIX%\\include\\tclTomMathDecls.h exit 1
        - if not exist %LIBRARY_PREFIX%\\include\\tclTomMath.h exit 1
        - if not exist %LIBRARY_PREFIX%\\include\\tk.h exit 1
        - if not exist %LIBRARY_PREFIX%\\include\\tkDecls.h exit 1
        - if not exist %LIBRARY_PREFIX%\\include\\tkPlatDecls.h exit 1
        - if not exist %LIBRARY_PREFIX%\\lib\\tcl86t.lib exit 1
        - if not exist %LIBRARY_PREFIX%\\bin\\tcl86t.dll exit 1
        - if not exist %LIBRARY_PREFIX%\\lib\\tclstub86.lib exit 1
        - if not exist %LIBRARY_PREFIX%\\lib\\tk86t.lib exit 1
        - if not exist %LIBRARY_PREFIX%\\bin\\tk86t.dll exit 1
        - if not exist %LIBRARY_PREFIX%\\lib\\tkstub86.lib exit 1
        - tclsh hello.tcl
        - tclsh86 hello.tcl
        - wish hello.tcl
        - wish86t hello.tcl
    files:
        - hello.tcl
about:
    home: http://www.tcl.tk/
    license: Tcl/Tk
    license_family: BSD
    license_file: tcl8.6.10/license.terms
    summary: A dynamic programming language with GUI support.  Bundles Tcl and Tk.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - ocefpaf
        - pelson
