# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# C:\ci\containers\000033lpj6p\tmp\build\80754af9\rsync-recipes\brotlipy-0.7.0-python_3.7-on-winbuilder, last modified Wed Jun  3 02:43:26 2020
# ------------------------------------------------

package:
    name: brotlipy
    version: 0.7.0
source:
    fn: brotlipy-0.7.0.tar.gz
    sha256: 36def0b859beaf21910157b4c33eb3b06d8ce459c942102f16988cca6ea164df
    url: https://pypi.io/packages/source/b/brotlipy/brotlipy-0.7.0.tar.gz
build:
    number: '1000'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py37he774522_1000
requirements:
    build:
        - vs2017_win-64 19.16.27032.1 hb4161e2_2
        - vswhere 2.7.1 h21ff451_0
    host:
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.1 py37_0
        - cffi 1.14.0 py37h7a1dbc1_0
        - openssl 1.1.1g he774522_0
        - pycparser 2.20 py_0
        - python 3.7.7 h81c818b_4
        - setuptools 46.4.0 py37_0
        - sqlite 3.31.1 h2a8f88b_1
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_2
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - cffi >=1.0.0
        - python >=3.7,<3.8.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    imports:
        - brotli
about:
    dev_url: https://github.com/python-hyper/brotlipy
    home: https://github.com/python-hyper/brotlipy
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: Python bindings to the Brotli compression library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - astaric
        - primozgodec
