# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Oct  9 18:10:54 2020
# ------------------------------------------------

package:
    name: flask-compress
    version: 1.7.0
source:
    fn: Flask-Compress-1.7.0.tar.gz
    sha256: 965e832684160871b5268f97879c5e85a88569cc6e3e353a7779215664eefdad
    url: https://pypi.io/packages/source/F/Flask-Compress/Flask-Compress-1.7.0.tar.gz
build:
    noarch: python
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/flask-compress_1602267119698/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
        -m pip install . -vv
    string: pyh9f0ad1d_0
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py36h9880bd3_2
        - ld_impl_linux-64 2.35 h769bd43_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - ncurses 6.2 he1b5a44_1
        - openssl 1.1.1h h516909a_0
        - pip 20.2.3 py_0
        - python 3.6.11 h4d41432_2_cpython
        - python_abi 3.6 1_cp36m
        - readline 8.0 he28a2e2_2
        - setuptools 49.6.0 py36h9880bd3_2
        - sqlite 3.33.0 h4cf870e_1
        - tk 8.6.10 hed695b0_1
        - wheel 0.35.1 pyh9f0ad1d_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1009
    run:
        - brotli-python
        - flask
        - python
test:
    commands:
        - pip check
        - pytest tests
    imports:
        - flask_compress
    requires:
        - pip
        - pytest
    source_files:
        - tests
about:
    description: 'Flask-Compress allows you to easily compress your Flask application''s
        responses with gzip.

        '
    dev_url: https://github.com/colour-science/flask-compress
    home: https://github.com/colour-science/flask-compress
    license: MIT
    license_family: MIT
    license_file: LICENSE.txt
    summary: Compress responses in your Flask app with gzip.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mariusvniekerk
        - synapticarbors
