# This file created by conda-build 3.20.4
# ------------------------------------------------

package:
    name: brotli-python
    version: 1.0.9
source:
    fn: brotli-1.0.9.tar.gz
    patches:
        - 0001-Add-separate-options-to-disable-shared-static-librar.patch
        - 0002-Fix-pkgconfig-rpath.patch
    sha256: f9e8d81d0405ba66d181529af42a3354f838c939095ff99930da6aa9cdf6fe46
    url: https://github.com/google/brotli/archive/v1.0.9.tar.gz
build:
    number: 3
    run_exports:
        - brotli >=1.0.9,<2.0a0
    string: py37h8e8dfb5_3
requirements:
    build:
        - cmake 3.18.2 h001a745_0
        - ninja 1.10.1 h587dcfd_2
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - vs2017_win-64 19.16.27038 h2e3bad8_2
        - vswhere 2.7.1 h21ff451_0
    host:
        - brotli 1.0.9 ha925a31_3
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py37hf50a25e_2
        - openssl 1.1.1h he774522_0
        - pip 20.2.4 py_0
        - python 3.7.8 h60c2a47_1_cpython
        - python_abi 3.7 1_cp37m
        - setuptools 49.6.0 py37hf50a25e_2
        - sqlite 3.33.0 he774522_1
        - vc 14.1 h869be7e_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - wheel 0.35.1 pyh9f0ad1d_0
        - wincertstore 0.2 py37hc8dfbb8_1005
    run:
        - python >=3.7,<3.8.0a0
        - python_abi 3.7.* *_cp37m
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012
test:
    imports:
        - brotli
about:
    home: http://github.com/google/brotli
    license: MIT
    license_file: LICENSE
    summary: Brotli compression format
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - CJ-Wright
        - wesm
        - xhochy
