# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\0000272k9p8\tmp\build\80754af9\rsync-recipes\krb5-1.18.2-on-winbuilder, last modified Mon Jun 29 14:11:55 2020
# ------------------------------------------------

package:
    name: krb5
    version: 1.18.2
source:
    sha256: 3a92fb44d06a60a79c71a031a528246bf4cf3badad150a2b91dfa7c4702c6c19
    url: https://github.com/krb5/krb5/archive/krb5-1.18.2-final.tar.gz
build:
    ignore_run_exports:
        - tk
    number: '0'
    run_exports:
        - krb5 >=1.18.2,<1.19.0a0
    string: hc04afaa_0
requirements:
    build:
        - ca-certificates 2020.1.1 0
        - m2-base 1.0.0 3
        - m2-bash 4.3.042 5
        - m2-bash-completion 2.3 2
        - m2-catgets 1.1 3
        - m2-coreutils 8.25 102
        - m2-dash 0.5.8 2
        - m2-diffutils 3.3 4
        - m2-file 5.25 2
        - m2-filesystem 2016.04 4
        - m2-findutils 4.6.0 2
        - m2-gawk 4.1.3 2
        - m2-gcc-libs 5.3.0 4
        - m2-gettext 0.19.7 4
        - m2-gmp 6.1.0 3
        - m2-grep 2.22 4
        - m2-gzip 1.7 2
        - m2-inetutils 1.9.2 2
        - m2-info 6.0 2
        - m2-less 481 2
        - m2-libasprintf 0.19.7 4
        - m2-libbz2 1.0.6 3
        - m2-libcatgets 1.1 3
        - m2-libcrypt 1.3 2
        - m2-libgettextpo 0.19.7 4
        - m2-libiconv 1.14 3
        - m2-libintl 0.19.7 4
        - m2-liblzma 5.2.2 2
        - m2-libpcre 8.38 2
        - m2-libreadline 6.3.008 8
        - m2-libutil-linux 2.26.2 2
        - m2-libxml2 2.9.2 3
        - m2-make 4.1 5
        - m2-mintty 1!2.2.3 2
        - m2-mpfr 3.1.4 2
        - m2-msys2-launcher-git 0.3.28.860c495 2
        - m2-msys2-runtime 2.5.0.17080.65c939c 3
        - m2-ncurses 6.0.20160220 2
        - m2-sed 4.2.2 3
        - m2-tar 1.28 4
        - m2-tftp-hpa 5.2 2
        - m2-time 1.7 2
        - m2-ttyrec 1.0.8 2
        - m2-tzcode 2015.e 2
        - m2-unzip 6.0 3
        - m2-util-linux 2.26.2 2
        - m2-which 2.21 3
        - m2-zip 3.0 2
        - m2-zlib 1.2.8 4
        - msys2-conda-epoch 20160418 1
        - openssl 1.1.1g he774522_0
        - perl 5.26.2.1 h0c8e037_0
        - posix 1.0.0 2
        - python 3.8.3 he1778fa_0
        - sqlite 3.32.3 h2a8f88b_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_2
        - vs2017_win-64 19.16.27032.1 hb4161e2_2
        - vswhere 2.7.1 h21ff451_0
        - zlib 1.2.11 h62dcd97_4
    host:
        - ca-certificates 2020.1.1 0
        - openssl 1.1.1g he774522_0
        - tk 8.6.10 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_2
    run:
        - openssl >=1.1.1g,<1.1.2a
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    requires:
        - python <3.8
about:
    home: http://web.mit.edu/kerberos/
    license: MIT
    license_file: doc/notice.rst
    summary: A network authentication protocol.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - chenghlee
        - mariusvniekerk
        - mingwandroid
        - ocefpaf
        - pelson
