# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Thu Nov 12 13:59:03 2020
# ------------------------------------------------

package:
    name: ujson
    version: '1.35'
source:
    -   sha256: f66073e5506e91d204ab0c614a148d5aa938bdbf104751be66f8ad7a222f5f86
        url: https://pypi.io/packages/source/u/ujson/ujson-1.35.tar.gz
    -   sha256: 3d0bf08e9f269f093baea3c6ab1a44b05d531197493942414114e969cd67b594
        url: https://raw.githubusercontent.com/ultrajson/ultrajson/v1.35/LICENSE.txt
build:
    number: '1003'
    script: D:\bld\ujson_1605189869925\_h_env\python.exe -m pip install . -vv
    string: py37hf2a7229_1003
requirements:
    build:
        - vs2017_win-64 19.16.27038 h2e3bad8_2
        - vswhere 2.7.1 h21ff451_0
    host:
        - ca-certificates 2020.11.8 h5b45459_0
        - certifi 2020.11.8 py37h03978a9_0
        - openssl 1.1.1h he774522_0
        - pip 20.2.4 py_0
        - python 3.7.8 h60c2a47_1_cpython
        - python_abi 3.7 1_cp37m
        - setuptools 49.6.0 py37hf50a25e_2
        - setuptools-scm 4.1.2 pyh9f0ad1d_0
        - setuptools_scm 4.1.2 0
        - sqlite 3.33.0 he774522_1
        - toml 0.10.2 pyhd8ed1ab_0
        - vc 14.1 h869be7e_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - wheel 0.35.1 pyh9f0ad1d_0
        - wincertstore 0.2 py37hc8dfbb8_1005
    run:
        - python >=3.7,<3.8.0a0
        - python_abi 3.7.* *_cp37m
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012
test:
    imports:
        - ujson
about:
    dev_url: https://github.com/ultrajson/ultrajson
    home: https://github.com/ultrajson/ultrajson
    license: BSD-3-Clause
    license_file: LICENSE.txt
    summary: Ultra fast JSON decoder and encoder written in C with Python bindings
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - kszucs
        - synapticarbors
