# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Wed Sep 30 18:31:34 2020
# ------------------------------------------------

package:
    name: jupyterlab_pygments
    version: 0.1.2
source:
    sha256: cfcda0873626150932f438eccf0f8bf22bfa92345b814890ab360d666b254146
    url: https://pypi.io/packages/source/j/jupyterlab_pygments/jupyterlab_pygments-0.1.2.tar.gz
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/jupyterlab_pygments_1601490720602/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py36_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1h h7b6447c_0
        - pip 20.2.2 py36_0
        - python 3.6.12 hcff3b4d_2
        - readline 8.0 h7b6447c_0
        - setuptools 49.6.0 py36_1
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - pygments >=2.4.1,<3
        - python
test:
    imports:
        - jupyterlab_pygments
about:
    description: 'The goal is to enable the use of JupyterLab''s themes with pygments-generated
        HTML.

        '
    dev_url: https://github.com/JupyterLab/jupyterlab_pygments
    home: http://github.com/JupyterLab/jupyterlab_pygments
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Pygments syntax coloring scheme making use of the JupyterLab CSS variables
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - SylvainCorlay
        - maartenbreddels
