# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Jun 29 15:12:45 2020
# ------------------------------------------------

package:
    name: dash_colorscales
    version: 0.0.4
source:
    sha256: e2eb8c78e702d03e9c13fb7ca888ed202152494dbb053f5aab6417b6f6d19f63
    url: https://pypi.io/packages/source/d/dash_colorscales/dash_colorscales-0.0.4.tar.gz
build:
    noarch: python
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/dash_colorscales_1593443621680/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
        -m pip install . -vv
    string: pyh9f0ad1d_0
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py36h9f0ad1d_0
        - ld_impl_linux-64 2.34 h53a641e_5
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1g h516909a_0
        - pip 20.1.1 py_1
        - python 3.6.10 h8356626_1011_cpython
        - python_abi 3.6 1_cp36m
        - readline 8.0 hf8c457e_0
        - setuptools 47.3.1 py36h9f0ad1d_0
        - sqlite 3.32.3 hcee41ef_0
        - tk 8.6.10 hed695b0_0
        - wheel 0.34.2 py_1
        - xz 5.2.5 h516909a_0
        - zlib 1.2.11 h516909a_1006
    run:
        - dash
        - python
test:
    imports:
        - dash_colorscales
about:
    description: Colorscale picker UI for your Dash apps.
    dev_url: https://github.com/plotly/dash-colorscales
    doc_url: https://github.com/plotly/dash-colorscales
    home: https://github.com/plotly/dash-colorscales
    license: MIT
    license_family: MIT
    license_file: LICENSE.txt
    summary: Wrapper of react-colorscales UI for Dash apps
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - aschonfeld
