# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Wed Jul 22 20:51:45 2020
# ------------------------------------------------

package:
    name: libnetcdf
    version: 4.7.4
source:
    patches:
        - patches/0003-Add-find_package-Threads-REQUIRED-to-CMakeLists.txt.patch
        - patches/0004-Prefer-getenv-TOPSRCDIR-over-STRINGIFY-TOPSRCDIR.patch
        - patches/0006-Fix-tests-for-Windows-VS2008-define-__func__-as-__FU.patch
        - patches/0008-Finish-the-missing-code-to-handle-VS-in-test_common..patch
        - patches/0009-topsrcdir.patch
        - patches/fix-474-for-new-curl.patch
        - patches/prevent_MS_runtime_libs_being_installed_again.patch
        - patches/strdup.patch
    sha256: 99930ad7b3c4c1a8e8831fb061cb02b2170fc8e5ccaeda733bd99c3b9d31666b
    url: https://github.com/Unidata/netcdf-c/archive/v4.7.4.tar.gz
build:
    number: '105'
    run_exports:
        - libnetcdf >=4.7.4,<4.7.5.0a0
    string: nompi_h256d12c_105
requirements:
    build:
        - cmake 3.17.0 he025d50_0
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - vs2017_win-64 19.16.27038 h2e3bad8_2
        - vswhere 2.7.1 h21ff451_0
    host:
        - bzip2 1.0.8 hfa6e2cd_2
        - ca-certificates 2020.6.20 hecda079_0
        - curl 7.71.1 h4b64cdc_3
        - hdf4 4.2.13 hf8e6fe8_1003
        - hdf5 1.10.6 nompi_ha405e13_100
        - jpeg 9d he774522_0
        - krb5 1.17.1 hc04afaa_1
        - libcurl 7.71.1 h4b64cdc_3
        - libssh2 1.9.0 hb06d900_4
        - openssl 1.1.1g he774522_0
        - tk 8.6.10 hfa6e2cd_0
        - vc 14.1 h869be7e_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - zlib 1.2.11 h2fa13f4_1006
    run:
        - bzip2 >=1.0.8,<2.0a0
        - bzip2 >=1.0.8,<2.0a0
        - curl >=7.71.1,<8.0a0
        - hdf4 >=4.2.13,<4.3.0a0
        - hdf4 >=4.2.13,<4.3.0a0
        - hdf5 * nompi_*
        - hdf5 >=1.10.6,<1.10.7.0a0
        - jpeg >=9d,<10a
        - jpeg >=9d,<10a
        - libssh2
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
about:
    home: http://www.unidata.ucar.edu/software/netcdf/
    license: MIT
    license_file: COPYRIGHT
    summary: Libraries and data formats that support array-oriented scientific data
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - beckermr
        - groutr
        - kmuehlbauer
        - mingwandroid
        - msarahan
        - ocefpaf
        - xylar
