# This file created by conda-build 3.20.2
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Wed Sep 16 17:48:36 2020
# ------------------------------------------------

package:
    name: python-jsonrpc-server
    version: 0.4.0
source:
    sha256: 62c543e541f101ec5b57dc654efc212d2c2e3ea47ff6f54b2e7dcb36ecf20595
    url: https://pypi.io/packages/source/p/python-jsonrpc-server/python-jsonrpc-server-0.4.0.tar.gz
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/python-jsonrpc-server_1600278539111/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py36_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.2.2 py36_0
        - python 3.6.12 hcff3b4d_2
        - readline 8.0 h7b6447c_0
        - setuptools 49.6.0 py36_0
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - future
        - python
        - ujson >=3.0.0
test:
    commands:
        - python -m pip check
    imports:
        - pyls_jsonrpc
        - pyls_jsonrpc.dispatchers
    requires:
        - pip
about:
    dev_url: https://github.com/palantir/python-jsonrpc-server
    home: https://github.com/palantir/python-jsonrpc-server
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: A Python 2.7 and 3.4+ server implementation of the JSON RPC 2.0 protocol.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - andfoy
        - ccordoba12
