# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/pull-recipes-et_xmlfile/recipe, last modified Fri Jul 10 03:34:58 2020
# ------------------------------------------------

package:
    name: et_xmlfile
    version: 1.0.1
source:
    fn: et_xmlfile-1.0.1.tar.gz
    sha256: 614d9722d572f6246302c4491846d2c393c199cfa4edc9af593437691683335b
    url: https://pypi.io/packages/source/e/et_xmlfile/et_xmlfile-1.0.1.tar.gz
build:
    noarch: python
    number: '1001'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py_1001
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py37_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h7b6447c_0
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - python 3.7.7 hcff3b4d_5
        - readline 8.0 h7b6447c_0
        - setuptools 47.3.1 py37_0
        - sqlite 3.32.3 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python
test:
    imports:
        - et_xmlfile
about:
    description: 'et_xmlfile is a low memory library for creating large XML files.

        '
    dev_url: https://bitbucket.org/openpyxl/et_xmlfile
    doc_source_url: https://bitbucket.org/openpyxl/et_xmlfile/src/default/doc/index.rst
    doc_url: https://et-xmlfile.readthedocs.io
    home: https://bitbucket.org/openpyxl/et_xmlfile
    license: MIT
    license_family: MIT
    license_file: /tmp/build/80754af9/pull-recipes-et_xmlfile/recipe/LICENCE.rst
    summary: An implementation of lxml.xmlfile for the standard library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - curtisalexander
