# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/prometheus_client-0.8.0-on-linux_64, last modified Tue Jun 16 17:28:38 2020
# ------------------------------------------------

package:
    name: prometheus_client
    version: 0.8.0
source:
    sha256: ac8f06e260aaef5467be369032c7a02e17fd39e6d2ac933964757cb6c92da678
    url: https://github.com/prometheus/client_python/archive/v0.8.0.tar.gz
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/prometheus_client_1592328588836/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
        -m pip install . -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.2 py36_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.3 he6710b0_1
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.0.2 py36_3
        - python 3.6.10 h7579374_2
        - readline 8.0 h7b6447c_0
        - setuptools 47.1.1 py36_0
        - sqlite 3.31.1 h62c20be_1
        - tk 8.6.8 hbc83047_0
        - wheel 0.34.2 py36_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python
test:
    commands:
        - pip check
    imports:
        - prometheus_client
        - prometheus_client.bridge
    requires:
        - pip
about:
    home: https://github.com/prometheus/client_python
    license: Apache-2.0
    license_family: Apache
    license_file: LICENSE
    summary: Python client for the Prometheus monitoring system
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jessicaaustin
        - kwilcox
        - ocefpaf
