# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Tue Oct 13 15:46:04 2020
# ------------------------------------------------

package:
    name: isort
    version: 5.6.4
source:
    sha256: dcaeec1b5f0eca77faea2a35ab790b4f3680ff75590bfcb7145986905aab2f58
    url: https://pypi.io/packages/source/i/isort/isort-5.6.4.tar.gz
build:
    entry_points:
        - isort = isort.main:main
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/isort_1602603989581/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
        -m pip install . -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1h h7b6447c_0
        - pip 20.2.3 py38_0
        - poetry-core 1.0.0 py_0
        - python 3.8.5 h7579374_1
        - readline 8.0 h7b6447c_0
        - setuptools 50.3.0 py38hb0f4dca_1
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=3.6,<4.0
        - setuptools
test:
    commands:
        - pip check
        - isort --help
    imports:
        - isort
        - isort._future
    requires:
        - pip
about:
    description: 'isort is a Python utility / library to sort imports alphabetically,
        and

        automatically separated into sections. It provides a command line utility,

        Python library and plugins for various editors to quickly sort all your

        imports. It currently cleanly supports Python 2.6 - 3.5 using pies to

        achieve this without ugly hacks and/or py2to3.

        '
    dev_url: https://github.com/timothycrosley/isort
    doc_source_url: https://github.com/timothycrosley/isort/blob/develop/README.rst
    doc_url: http://isort.readthedocs.io/en/latest/
    home: https://github.com/timothycrosley/isort
    license: MIT
    license_file: LICENSE
    summary: A Python utility / library to sort Python imports.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - goanpeca
        - nehaljwani
        - nicoddemus
        - ocefpaf
