# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Fri Apr 24 09:09:31 2020
# ------------------------------------------------

package:
    name: gl2ps
    version: 1.4.2
source:
    folder: source
    patches:
        - 0001-Disable-static-library-on-Windows.patch
    sha256: 8d1c00c1018f96b4b97655482e57dcb0ce42ae2f1d349cd6d4191e7848d9ffe9
    url: http://geuz.org/gl2ps/src/gl2ps-1.4.2.tgz
build:
    number: '0'
    run_exports:
        - gl2ps >=1.4.2,<1.4.3.0a0
    string: h2c487a6_0
requirements:
    build:
        - cmake 3.17.0 he025d50_0
        - ninja 1.10.0 h1ad3211_0
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - vs2017_win-64 19.16.27038 h2e3bad8_2
        - vswhere 2.7.1 h21ff451_0
    host:
        - libpng 1.6.37 hfe6a214_1
        - vc 14.1 h869be7e_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - zlib 1.2.11 h2fa13f4_1006
    run:
        - libpng >=1.6.37,<1.7.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - if not exist %LIBRARY_BIN%\\gl2ps.dll exit 1
about:
    description: 'This is GL2PS, an OpenGL to PostScript (and PDF, and SVG...) printing
        library.

        '
    dev_url: http://gitlab.onelab.info/gl2ps/gl2ps
    doc_url: http://geuz.org/gl2ps/#tth_sEc1
    home: http://geuz.org/gl2ps
    license: LGPL-2.0-or-later
    license_family: LGPL
    license_file: source/COPYING.LGPL
    summary: OpenGL to PostScript Printing Library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - chrisburr
        - henryiii
