# This file created by conda-build 3.20.0
# meta.yaml template originally from:
# C:\ci\containers\00001fuf6ki\tmp\build\80754af9\rsync-recipes\python-3.7.9-on-winbuilder, last modified Mon Aug 31 12:16:46 2020
# ------------------------------------------------

package:
    name: python
    version: 3.7.9
source:
    -   md5: 389d3ed26b4d97c741d9e5423da1f43b
        patches:
            - patches/0001-Fix-off-by-one-error-in-_winapi_WaitForMultipleObjec.patch
            - patches/0003-Add-Anaconda-Distribution-version-logic.patch
            - patches/0004-Darwin-Add-arch-x86_64-to-UnicCCompiler-ld_args.patch
            - patches/0005-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
            - patches/0006-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
            - patches/0007-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
            - patches/0008-Support-cross-compiling-byte-code.patch
            - patches/0009-Win32-Fixes-for-Windows-GCC-interop-needed-by-RPy2-a.patch
            - patches/0010-Darwin-Look-in-sysroot-usr-lib-include-if-sysroot-is.patch
            - patches/0011-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
            - patches/0012-Win32-Do-not-download-externals.patch
            - patches/0013-Add-support-for-_CONDA_PYTHON_SYSCONFIGDATA_NAME-if-.patch
            - patches/0014-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
            - patches/0015-Disable-new-dtags-in-unixccompiler.py.patch
            - patches/0016-Fix-cross-compilation-on-Debian-based-distros.patch
            - patches/0017-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
            - patches/0018-Unvendor-openssl.patch
            - patches/0019-Unvendor-sqlite3.patch
            - patches/0020-venv-Revert-a-change-from-https-github.com-python-cp.patch
            - patches/0021-Add-CondaEcosystemModifyDllSearchPath.patch
            - patches/0022-Use-ranlib-from-env-if-env-variable-is-set.patch
        url: https://www.python.org/ftp/python/3.7.9/Python-3.7.9.tar.xz
    -   folder: externals/xz-5.2.2
        sha256: 02b6d6f1e0369940e7e1f0d324992e069d09f5f3d32d86e2d22cd8b82ac3fb3f
        url: https://github.com/python/cpython-source-deps/archive/xz-5.2.2.zip
    -   folder: externals/tcl-core-8.6.9.0
        sha256: ea9e724536ec13b476ebbd47948303b92fdd90a33aa94f30fcc2f5c3a899f69e
        url: https://github.com/python/cpython-source-deps/archive/tcl-core-8.6.9.0.zip
    -   folder: externals/tk-8.6.9.0
        sha256: f3112b6bbc3bd163c877030187e73ce9a113ce03eff559ec5b9df697e3a08fad
        url: https://github.com/python/cpython-source-deps/archive/tk-8.6.9.0.zip
    -   folder: externals/tcltk-8.6.9.0
        sha256: 37cd629a75d2a34974a3d771ccab5c9e3caf3d138cea81040f9cdba1aded1cf2
        url: https://github.com/python/cpython-bin-deps/archive/tcltk-8.6.9.0.zip
    -   folder: externals/tix-8.4.3.6
        sha256: e558e3dc5e67ac0942f8fceafce00ca46b177da9ebeaf38ec7fafd9b9913ac56
        url: https://github.com/python/cpython-source-deps/archive/tix-8.4.3.6.zip
    -   folder: externals/bzip2-1.0.6
        sha256: c42fd1432a2667b964a74bc423bb7485059c4a6d5dc92946d59dbf9a6bdb988d
        url: https://github.com/python/cpython-source-deps/archive/bzip2-1.0.6.zip
    -   folder: externals/zlib-1.2.11
        sha256: debb1952945fa6c25817a40abe90641b572c83171f244937b70b9fe156f5a63a
        url: https://github.com/python/cpython-source-deps/archive/zlib-1.2.11.zip
    -   folder: externals/nasm-2.11.06
        sha256: de3c87b26a80e789986d8e6950c6304175d3829afe9c6c7211eb7257266ab0ac
        url: https://github.com/python/cpython-bin-deps/archive/nasm-2.11.06.zip
build:
    binary_has_prefix_files:
        - lib/libpython3.7.*.1.0
    detect_binary_files_with_prefix: false
    no_link:
        - DLLs/_ctypes.pyd
    number: '0'
    script_env:
        - OPENSSL_DIR=%PREFIX%\Library
        - PY_INTERP_DEBUG
        - PY_INTERP_LINKAGE_NATURE
        - SQLITE3_DIR=%PREFIX%\Library
    string: h60c2a47_0
requirements:
    build:
        - m2-gcc-libs 5.3.0 4
        - m2-msys2-runtime 2.5.0.17080.65c939c 3
        - m2-patch 2.7.5 2
        - msys2-conda-epoch 20160418 1
        - vs2017_win-64 19.16.27032.1 hb4161e2_3
        - vswhere 2.7.1 h21ff451_0
    host:
        - ca-certificates 2020.7.22 0
        - openssl 1.1.1g he774522_1
        - sqlite 3.33.0 h2a8f88b_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - zlib 1.2.11 h62dcd97_4
    run:
        - openssl >=1.1.1g,<1.1.2a
        - sqlite >=3.33.0,<4.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    commands:
        - python -V
        - 2to3 -h
        - pydoc -h
        - python -m venv %%TEMP%%\venv
        - pushd tests
        - pushd distutils
        - python setup.py install -v -v
        - python -c "import foobar"
        - popd
        - pushd distutils.cext
        - python setup.py install --single-version-externally-managed --record=record.txt
            -v -v
        - python -v -v -v -c "import greet"
        - python -v -v -v -c "import greet; greet.greet('Python user')" | rg "Hello
            Python"
        - popd
        - pushd processpoolexecutor-max_workers-61
        - python ppe.py
        - popd
        - pushd cmake
        - popd
        - popd
    files:
        - tests/cmake/*
        - tests/cython/*
        - tests/distutils.cext/*
        - tests/distutils/*
        - tests/prefix-replacement/*
        - tests/processpoolexecutor-max_workers-61/*
    requires:
        - cmake
        - cython
        - ninja
        - ripgrep
        - setuptools
        - vs2017_win-64
about:
    description: 'Python is a widely used high-level, general-purpose, interpreted,
        dynamic

        programming language. Its design philosophy emphasizes code

        readability, and its syntax allows programmers to express concepts in

        fewer lines of code than would be possible in languages such as C++ or

        Java. The language provides constructs intended to enable clear programs

        on both a small and large scale.

        '
    dev_url: https://docs.python.org/devguide/
    doc_source_url: https://github.com/python/pythondotorg/blob/master/docs/source/index.rst
    doc_url: https://www.python.org/doc/versions/
    home: http://www.python.org/
    license: PSF
    license_file: LICENSE
    summary: General purpose programming language
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - isuruf
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - ocefpaf
        - pelson
        - scopatz
