# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Thu Oct  8 19:26:21 2020
# ------------------------------------------------

package:
    name: tqdm
    version: 4.50.2
source:
    sha256: 69dfa6714dee976e2425a9aab84b622675b7b1742873041e3db8a8e86132a4af
    url: https://pypi.io/packages/source/t/tqdm/tqdm-4.50.2.tar.gz
build:
    entry_points:
        - tqdm = tqdm.cli:main
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/tqdm_1602185206534/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
        -m pip install . --no-deps -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py36_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1h h7b6447c_0
        - pip 20.2.3 py36_0
        - python 3.6.12 hcff3b4d_2
        - readline 8.0 h7b6447c_0
        - setuptools 50.3.0 py36hb0f4dca_1
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python
test:
    commands:
        - tqdm --help
        - tqdm -v
    imports:
        - tqdm
about:
    dev_url: https://github.com/tqdm/tqdm
    doc_url: https://github.com/tqdm/tqdm
    home: https://pypi.python.org/pypi/tqdm
    license: MPLv2.0, MIT
    license_family: MIT
    license_file: LICENCE
    summary: A Fast, Extensible Progress Meter
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - casperdcl
        - ericdill
        - pmlandwehr
