# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# C:\ci\containers\00003vfggug\tmp\build\80754af9\combined_recipe, last modified Fri Oct  2 18:05:01 2020
# ------------------------------------------------

package:
    name: pywavelets
    version: 1.1.1
source:
    patches:
        - pr522.patch
    sha256: 1a64b40f6acb4ffbaccce0545d7fc641744f95351f62e4c6aaa40549326008c9
    url: https://pypi.io/packages/source/P/PyWavelets/PyWavelets-1.1.1.tar.gz
build:
    number: '2'
    script: C:\ci\pywavelets_1601658407053\_h_env\python.exe -m pip install . --no-deps
        -vv
    string: py37he774522_2
requirements:
    build:
        - vs2017_win-64 19.16.27032.1 hb4161e2_3
        - vswhere 2.7.1 h21ff451_0
    host:
        - blas 1.0 mkl
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py37_0
        - cython 0.29.21 py37ha925a31_0
        - icc_rt 2019.0.0 h0cc432a_1
        - intel-openmp 2019.4 245
        - mkl 2019.4 245
        - mkl-service 2.3.0 py37hb782905_0
        - mkl_fft 1.0.14 py37h6288b17_0
        - mkl_random 1.0.4 py37h343c172_0
        - numpy 1.14.6 py37ha06f490_5
        - numpy-base 1.14.6 py37hc3f5095_5
        - openssl 1.1.1h he774522_0
        - pip 20.2.3 py37_0
        - python 3.7.9 h60c2a47_0
        - setuptools 49.6.0 py37_1
        - six 1.15.0 py_0
        - sqlite 3.33.0 h2a8f88b_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - wheel 0.35.1 py_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - numpy >=1.14.6,<2.0a0
        - python >=3.7,<3.8.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    imports:
        - pywt
    requires:
        - pytest
about:
    description: 'PyWavelets is a free Open Source library for wavelet transforms
        in Python.

        Wavelets are mathematical basis functions that are localized in both time
        and frequency.

        Wavelet transforms are time-frequency transforms employing wavelets. They
        are similar to

        Fourier transforms, the difference being that Fourier transforms are localized
        only in

        frequency instead of in time and frequency.

        '
    dev_url: https://github.com/PyWavelets/pywt
    doc_source_url: https://github.com/PyWavelets/pywt/tree/master/doc
    doc_url: http://pywavelets.readthedocs.io/en/latest/
    home: https://github.com/PyWavelets/pywt
    license: MIT
    license_file: LICENSE
    summary: Discrete Wavelet Transforms in Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - grlee77
        - jakirkham
        - ocefpaf
