# This file created by conda-build 3.20.2
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/qtconsole-4.7.7-on-linux_64, last modified Wed Sep 23 14:06:06 2020
# ------------------------------------------------

package:
    name: qtconsole
    version: 4.7.7
source:
    sha256: f236ead8711dba0702507dd8fad473c7216a86eefa6098eff8ec4b54f57d7804
    url: https://pypi.io/packages/source/q/qtconsole/qtconsole-4.7.7.tar.gz
build:
    entry_points:
        - jupyter-qtconsole = qtconsole.qtconsoleapp:main
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/qtconsole_1600870028330/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
        -m pip install . --no-deps -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py36_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1h h7b6447c_0
        - pip 20.2.2 py36_0
        - python 3.6.12 hcff3b4d_2
        - readline 8.0 h7b6447c_0
        - setuptools 49.6.0 py36_0
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - ipykernel >=4.1
        - ipython_genutils
        - jupyter_client >=4.1
        - jupyter_core
        - pygments
        - pyqt
        - python
        - qtpy
        - traitlets
test:
    commands:
        - DISPLAY=localhost:1.0 xvfb-run -a bash -c 'jupyter qtconsole --help'
    imports:
        - qtconsole
        - qtconsole.tests
app:
    entry: jupyter-qtconsole
    summary: Jupyter Qt Console
    type: desk
about:
    description: 'A rich Qt-based console for working with Jupyter kernels, supporting
        rich

        media output, session export, and more. The Qt console is a very

        lightweight application that largely feels like a terminal, but provides

        a number of enhancements only possible in a GUI, such as inline figures,

        proper multiline editing with syntax highlighting, graphical calltips, and

        more.

        '
    dev_url: https://github.com/jupyter/qtconsole
    doc_source_url: https://github.com/jupyter/qtconsole/tree/master/docs
    doc_url: https://qtconsole.readthedocs.org/en/stable/
    home: http://jupyter.org
    license: BSD-3-Clause
    license_file: LICENSE
    summary: Jupyter Qt console
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - Carreau
        - ccordoba12
        - jakirkham
        - minrk
        - ocefpaf
        - takluyver
