# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/python-libarchive-c-2.9-on-linux_canary, last modified Fri Apr 17 01:09:18 2020
# ------------------------------------------------

package:
    name: python-libarchive-c
    version: '2.9'
source:
    patches:
        - 0002-prefer-to-load-libarchive-from-conda-pkg-path.patch
    sha256: 9919344cec203f5db6596a29b5bc26b07ba9662925a05e24980b84709232ef60
    url: https://pypi.io/packages/source/l/libarchive-c/libarchive-c-2.9.tar.gz
build:
    noarch: python
    number: '0'
    script:
        - /tmp/build/80754af9/python-libarchive-c_1587221046010/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
            -m pip install . -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.1 py36_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_0
        - openssl 1.1.1f h7b6447c_0
        - pip 20.0.2 py36_1
        - python 3.6.10 hcf32534_1
        - readline 8.0 h7b6447c_0
        - setuptools 46.1.3 py36_0
        - sqlite 3.31.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - wheel 0.34.2 py36_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - libarchive
        - python
test:
    commands:
        - python -c "import libarchive; libarchive.extract_file('test/hello_world.xar')"
        - python -c "import os, shutil, libarchive; shutil.copytree(os.path.dirname(libarchive.__file__),
            'libarchive')"
        - pytest --cov libarchive -vv
    files:
        - test/hello_world.xar
    imports:
        - libarchive
    requires:
        - mock
        - pytest-cov
    source_files:
        - README.rst
        - tests
about:
    home: https://github.com/Changaco/python-libarchive-c
    license: CC0-1.0
    license_family: CC
    license_file: cc0-1.0.txt
    summary: Python interface to libarchive
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - bollwyvl
        - mingwandroid
        - ocefpaf
