CI: azure
VTK_WITH_OSMESA: 'False'
boost_cpp: '1.72'
c_compiler: vs2017
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: vs2017
expat: '2.2'
extend_keys:
- extend_keys
- pin_run_as_build
- ignore_version
- ignore_build_only_deps
ffmpeg: '4.3'
fortran_compiler: gfortran
freetype: 2.9.1
glew: '2.1'
hdf5: 1.10.6
ignore_build_only_deps:
- numpy
- python
jpeg: '9'
jsoncpp: 1.8.4
libnetcdf: 4.7.4
libpng: '1.6'
libtiff: 4.1.0
libxml2: '2.9'
lua: '5'
lz4_c: 1.9.2
numpy: '1.11'
perl: 5.26.0
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  boost-cpp:
    max_pin: x.x.x
  expat:
    max_pin: x.x
  ffmpeg:
    max_pin: x.x
  freetype:
    max_pin: x
  glew:
    max_pin: x.x
  jpeg:
    max_pin: x
  jsoncpp:
    max_pin: x.x.x
  libpng:
    max_pin: x.x
  libtiff:
    max_pin: x
  libxml2:
    max_pin: x.x
  lz4-c:
    max_pin: x.x.x
  sqlite:
    max_pin: x
  vtk:
    max_pin: x.x.x
  zlib:
    max_pin: x.x
proj: 7.0.0
python: 3.7.* *_cpython
r_base: '3.4'
sqlite: '3'
target_platform: win-64
vc: '14'
vtk: 8.2.0
zlib: '1.2'
