# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Mon Jul  6 10:08:22 2020
# ------------------------------------------------

package:
    name: vtk
    version: 9.0.1
source:
    sha256: 1b39a5e191c282861e7af4101eaa8585969a2de05f5646c9199a161213a622c7
    url: http://www.vtk.org/files/release/9.0/VTK-9.0.1.tar.gz
build:
    number: '100'
    string: no_osmesa_py37h35f1388_100
requirements:
    build:
        - cmake 3.17.0 he025d50_0
        - ninja 1.10.0 h1ad3211_0
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - vs2017_win-64 19.16.27038 h2e3bad8_2
        - vswhere 2.7.1 h21ff451_0
    host:
        - boost-cpp 1.72.0 h2ba7cf6_1
        - bzip2 1.0.8 hfa6e2cd_2
        - ca-certificates 2020.6.20 hecda079_0
        - colorama 0.4.3 py_0
        - curl 7.71.1 h4b64cdc_0
        - double-conversion 3.1.5 h6538335_2
        - eigen 3.3.7 he980bc4_1001
        - expat 2.2.9 he025d50_2
        - ffmpeg 4.3 ha925a31_0
        - freetype 2.9.1 h563cfd7_1006
        - gl2ps 1.4.2 h2c487a6_0
        - glew 2.1.0 he025d50_0
        - hdf4 4.2.13 hf8e6fe8_1003
        - hdf5 1.10.6 nompi_ha405e13_100
        - jpeg 9d he774522_0
        - jsoncpp 1.8.4 h1ad3211_1002
        - krb5 1.17.1 hc04afaa_1
        - libcurl 7.71.1 h4b64cdc_0
        - libiconv 1.15 hfa6e2cd_1006
        - libnetcdf 4.7.4 nompi_h256d12c_104
        - libogg 1.3.2 hfa6e2cd_1002
        - libpng 1.6.37 hfe6a214_1
        - libssh2 1.9.0 h3235a2c_2
        - libtheora 1.1.1 h62dcd97_1003
        - libtiff 4.1.0 h885aae3_6
        - libxml2 2.9.10 h5d81f1c_1
        - loguru 0.5.0 py37hc8dfbb8_0
        - lz4-c 1.9.2 h62dcd97_1
        - openssl 1.1.1g he774522_0
        - proj 7.0.0 haa36216_3
        - pugixml 1.10 h6538335_1
        - python 3.7.6 h60c2a47_5_cpython
        - python_abi 3.7 1_cp37m
        - sqlite 3.32.3 he774522_0
        - tbb 2019.9 he980bc4_1
        - tbb-devel 2019.9 he980bc4_1
        - tk 8.6.10 hfa6e2cd_0
        - utfcpp 3.1.1 0
        - vc 14.1 h869be7e_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - win32_setctime 1.0.1 py_0
        - xz 5.2.5 h2fa13f4_0
        - zlib 1.2.11 h2fa13f4_1006
        - zstd 1.4.4 h9f78265_3
    run:
        - double-conversion >=3.1.5,<3.2.0a0
        - eigen
        - expat >=2.2.9,<2.3.0a0
        - expat >=2.2.9,<2.3.0a0
        - ffmpeg >=4.3,<4.4.0a0
        - ffmpeg >=4.3,<4.4.0a0
        - freetype >=2.9.1,<3.0a0
        - freetype >=2.9.1,<3.0a0
        - gl2ps >=1.4.2,<1.4.3.0a0
        - glew >=2.1.0,<2.2.0a0
        - glew >=2.1.0,<2.2.0a0
        - hdf5 >=1.10.6,<1.10.7.0a0
        - jpeg >=9d,<10a
        - jpeg >=9d,<10a
        - jsoncpp >=1.8.4,<1.8.5.0a0
        - jsoncpp >=1.8.4,<1.8.5.0a0
        - libnetcdf >=4.7.4,<4.7.5.0a0
        - libogg >=1.3.2,<1.4.0a0
        - libpng >=1.6.37,<1.7.0a0
        - libpng >=1.6.37,<1.7.0a0
        - libtheora >=1.1.1,<1.2.0a0
        - libtiff >=4.1.0,<5.0a0
        - libtiff >=4.1.0,<5.0a0
        - libxml2 >=2.9.10,<2.10.0a0
        - libxml2 >=2.9.10,<2.10.0a0
        - loguru
        - lz4-c >=1.9.2,<1.9.3.0a0
        - lz4-c >=1.9.2,<1.9.3.0a0
        - proj >=7.0.0,<7.0.1.0a0
        - pugixml >=1.10,<1.11.0a0
        - python >=3.7,<3.8.0a0
        - python_abi 3.7.* *_cp37m
        - sqlite >=3.32.3,<4.0a0
        - sqlite >=3.32.3,<4.0a0
        - tbb >=2019.9
        - tbb-devel
        - utfcpp
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
    run_constrained:
        - paraview ==9999999999
test:
    imports:
        - vtk
        - vtk.vtkChartsCore
        - vtk.vtkCommonCore
        - vtk.vtkFiltersCore
        - vtk.vtkFiltersGeneric
        - vtk.vtkFiltersHybrid
        - vtk.vtkGeovisCore
        - vtk.vtkIOCore
        - vtk.vtkImagingCore
        - vtk.vtkInfovisCore
        - vtk.vtkInteractionWidgets
        - vtk.vtkRenderingCore
        - vtk.vtkRenderingVolume
        - vtk.vtkViewsCore
        - vtk.vtkWebGLExporter
        - vtkmodules
        - vtkmodules.vtkChartsCore
        - vtkmodules.vtkCommonCore
        - vtkmodules.vtkFiltersCore
        - vtkmodules.vtkFiltersGeneric
        - vtkmodules.vtkFiltersHybrid
        - vtkmodules.vtkGeovisCore
        - vtkmodules.vtkIOCore
        - vtkmodules.vtkImagingCore
        - vtkmodules.vtkInfovisCore
        - vtkmodules.vtkInteractionWidgets
        - vtkmodules.vtkRenderingCore
        - vtkmodules.vtkRenderingVolume
        - vtkmodules.vtkViewsCore
    requires:
        - setuptools
about:
    home: http://www.vtk.org/
    license: BSD-3-Clause
    license_file: Copyright.txt
    summary: 'The Visualization Toolkit (VTK) is an open-source, freely available
        software system for 3D computer graphics, modeling, image processing, volume
        rendering, scientific visualization, and information visualization.

        '
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - Maxyme
        - ccordoba12
        - dfroger
        - downiec
        - grlee77
        - jasonb5
        - marcelotrevisani
        - msarahan
        - muryanto1
        - patricksnape
        - tadeu
