# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Wed Aug  5 09:03:26 2020
# ------------------------------------------------

package:
    name: occt
    version: 7.4.0
source:
    fn: occt-7.4.0.tar.gz
    patches:
        - cmake_policy.patch
        - fix-brepblend.patch
        - fix-private-linking.patch
        - no-xmu.patch
        - vtk.patch
    sha256: 9614c2075cef53e30b25317fc8fcfb71d60a69181d562e1c56469ed8e54ad758
    url: http://git.dev.opencascade.org/gitweb/?p=occt.git;a=snapshot;h=V7_4_0;sf=tgz
build:
    number: '8'
    string: hd267c4f_8
requirements:
    build:
        - cmake 3.16.5 he025d50_0
        - ninja 1.10.0 h1ad3211_0
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - vs2017_win-64 19.16.27038 h2e3bad8_2
        - vswhere 2.7.1 h21ff451_0
    host:
        - bzip2 1.0.8 hfa6e2cd_2
        - ca-certificates 2020.6.20 hecda079_0
        - colorama 0.4.3 py_0
        - curl 7.71.1 h4b64cdc_4
        - double-conversion 3.1.5 h6538335_2
        - eigen 3.3.7 he980bc4_1001
        - expat 2.2.9 he025d50_2
        - ffmpeg 4.3 ha925a31_1
        - fontconfig 2.13.1 hdcb13c4_1002
        - freeimage 3.18.0 h33f27b4_0
        - freetype 2.9.1 h563cfd7_1006
        - gl2ps 1.4.2 h2c487a6_0
        - glew 2.1.0 he025d50_0
        - hdf4 4.2.13 hf8e6fe8_1003
        - hdf5 1.10.6 nompi_he0bbb20_101
        - icu 67.1 h33f27b4_0
        - jpeg 9d he774522_0
        - jsoncpp 1.8.4 h1ad3211_1002
        - krb5 1.17.1 hc04afaa_2
        - libcurl 7.71.1 h4b64cdc_4
        - libiconv 1.15 hfa6e2cd_1006
        - libnetcdf 4.7.4 nompi_h256d12c_105
        - libogg 1.3.2 hfa6e2cd_1002
        - libpng 1.6.37 hfe6a214_1
        - libssh2 1.9.0 hb06d900_5
        - libtheora 1.1.1 h62dcd97_1003
        - libtiff 4.1.0 h885aae3_6
        - libxml2 2.9.10 h5d81f1c_2
        - loguru 0.5.0 py38h32f6830_0
        - lz4-c 1.9.2 h62dcd97_1
        - openssl 1.1.1g he774522_1
        - proj 7.0.0 haa36216_5
        - pugixml 1.10 h6538335_1
        - python 3.8.5 h5fd99cc_2_cpython
        - python_abi 3.8 1_cp38
        - sqlite 3.32.3 he774522_1
        - tbb 2019.9 he980bc4_1
        - tbb-devel 2019.9 he980bc4_1
        - tk 8.6.10 hfa6e2cd_0
        - utfcpp 3.1.1 0
        - vc 14.1 h869be7e_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - vtk 9.0.1 no_osmesa_py38hf2580a8_100
        - win32_setctime 1.0.1 py_0
        - xz 5.2.5 h62dcd97_1
        - zlib 1.2.11 h2fa13f4_1006
        - zstd 1.4.5 h1f3a1b7_2
    run:
        - fontconfig >=2.13.1,<3.0a0
        - fontconfig >=2.13.1,<3.0a0
        - freeimage >=3.18.0,<3.19.0a0
        - freetype >=2.9.1,<3.0a0
        - freetype >=2.9.1,<3.0a0
        - tbb >=2019.9
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012
        - vtk >=9.0.1,<9.0.2.0a0
test:
    commands:
        - cmake -G "Ninja" .
    files:
        - CMakeLists.txt
    requires:
        - cmake
        - ninja
about:
    description: 'Open Cascade Technology (OCCT), formerly called CAS.CADE

        is an open source software development platform for 3D CAD,

        CAM, CAE, etc. that is developed and supported by Open Cascade SAS.

        '
    dev_url: http://git.dev.opencascade.org/gitweb/?p=occt.git
    doc_url: https://www.opencascade.com/content/documentation
    home: https://www.opencascade.com/
    license: LGPL-2.1
    license_family: LGPL
    license_file: LICENSE_LGPL_21.txt
    summary: this is the occ (opencascade) CAD-Kernel
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - looooo
