# This file created by conda-build 3.20.2
# meta.yaml template originally from:
# C:\ci\containers\00000f81h1c\tmp\build\80754af9\combined_recipe, last modified Sat Sep 19 15:33:27 2020
# ------------------------------------------------

package:
    name: tbb
    version: '2020.3'
source:
    fn: tbbv2020.3_oss_src.tgz
    sha256: ebc4f6aa47972daed1f7bf71d100ae5bf6931c2e3144cf299c8cc7d041dca2f3
    url: https://github.com/intel/tbb/archive/v2020.3.tar.gz
build:
    number: '0'
    script: python build/build.py --build-args="CXXFLAGS= CFLAGS=" --make-tool=mingw32-make
        --build-prefix=vc%VS_MAJOR% --install-libs
    script_env:
        - OS
    string: h74a9793_0
requirements:
    build:
        - ca-certificates 2020.7.22 0
        - m2w64-make 4.1.2351.a80a8b8 2
        - msys2-conda-epoch 20160418 1
        - openssl 1.1.1g he774522_1
        - python 3.8.5 h5fd99cc_1
        - sqlite 3.33.0 h2a8f88b_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - vs2017_win-64 19.16.27032.1 hb4161e2_3
        - vswhere 2.7.1 h21ff451_0
        - zlib 1.2.11 h62dcd97_4
    host:
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
    run:
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    commands:
        - python -c "import ctypes, os; os.add_dll_directory(os.environ['LIBRARY_BIN']);
            assert 11103 == ctypes.cdll[r'tbb.dll'] ['TBB_runtime_interface_version']()"
    requires:
        - python *
about:
    dev_url: https://github.com/01org/tbb
    doc_url: https://software.intel.com/en-us/node/506039
    home: http://www.threadingbuildingblocks.org
    license: Apache-2.0
    license_file: LICENSE
    summary: High level abstract threading library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - anton-malakhov
        - jschueller
