# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/intervaltree-3.1.0-on-linux_64, last modified Tue Aug 25 17:25:08 2020
# ------------------------------------------------

package:
    name: intervaltree
    version: 3.1.0
source:
    fn: intervaltree-3.1.0.tar.gz
    sha256: 902b1b88936918f9b2a19e0e5eb7ccb430ae45cde4f39ea4b36932920d33952d
    url: https://pypi.io/packages/source/i/intervaltree/intervaltree-3.1.0.tar.gz
build:
    noarch: python
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py36_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.2.2 py36_0
        - python 3.6.10 h7579374_2
        - readline 8.0 h7b6447c_0
        - setuptools 49.6.0 py36_0
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.34.2 py36_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python
        - sortedcontainers
test:
    imports:
        - intervaltree
about:
    home: https://github.com/chaimleib/intervaltree
    license: Apache-2.0
    license_family: APACHE
    license_file: LICENSE.txt
    summary: Editable interval tree data structure for Python 2 and 3
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - bgruening
        - johanneskoester
