# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\0000218nnuk\tmp\build\80754af9\rsync-recipes\sqlalchemy-1.3.19-python_3.7-on-winbuilder, last modified Tue Aug 25 11:56:42 2020
# ------------------------------------------------

package:
    name: sqlalchemy
    version: 1.3.19
source:
    sha256: 3bba2e9fbedb0511769780fe1d63007081008c5c2d7d715e91858c94dbaa260e
    url: https://pypi.io/packages/source/S/SQLAlchemy/SQLAlchemy-1.3.19.tar.gz
build:
    number: '0'
    script: C:\\ci\\sqlalchemy_1598374801163\\_h_env\\python.exe -m pip install .
        --no-deps -vv
    string: py37he774522_0
requirements:
    build:
        - vs2017_win-64 19.16.27032.1 hb4161e2_3
        - vswhere 2.7.1 h21ff451_0
    host:
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py37_0
        - openssl 1.1.1g he774522_1
        - pip 20.2.2 py37_0
        - python 3.7.7 h81c818b_4
        - setuptools 49.6.0 py37_0
        - sqlite 3.33.0 h2a8f88b_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - wheel 0.34.2 py37_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - python >=3.7,<3.8.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    imports:
        - sqlalchemy
        - sqlalchemy.connectors
        - sqlalchemy.databases
        - sqlalchemy.dialects
        - sqlalchemy.dialects.firebird
        - sqlalchemy.dialects.mssql
        - sqlalchemy.dialects.mysql
        - sqlalchemy.dialects.oracle
        - sqlalchemy.dialects.postgresql
        - sqlalchemy.dialects.sqlite
        - sqlalchemy.dialects.sybase
        - sqlalchemy.engine
        - sqlalchemy.event
        - sqlalchemy.ext
        - sqlalchemy.ext.declarative
        - sqlalchemy.orm
        - sqlalchemy.sql
        - sqlalchemy.testing
        - sqlalchemy.testing.plugin
        - sqlalchemy.util
about:
    description: 'SQLAlchemy is the Python SQL toolkit and Object Relational Mapper
        that

        gives application developers the full power and flexibility of SQL.

        '
    dev_url: https://bitbucket.org/zzzeek/sqlalchemy/
    doc_source_url: https://github.com/zzzeek/sqlalchemy/blob/master/doc/build/index.rst
    doc_url: http://docs.sqlalchemy.org/en/rel_1_0/
    home: http://www.sqlalchemy.org/
    license: MIT
    license_file: LICENSE
    summary: Database Abstraction Library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - igortg
        - mcs07
        - nehaljwani
        - ocefpaf
