# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00001hd07mc\tmp\build\80754af9\rsync-recipes\mpfr-4.0.2-on-winbuilder, last modified Thu Jun 25 15:00:42 2020
# ------------------------------------------------

package:
    name: mpfr
    version: 4.0.2
source:
    fn: mpfr-4.0.2.tar.bz2
    patches:
        - patches/build-vc14.patch
        - patches/corei5.patch
    sha256: ae26cace63a498f07047a784cd3b0e4d010b44d2b193bab82af693de57a19a78
    url: http://ftp.gnu.org/gnu/mpfr/mpfr-4.0.2.tar.gz
build:
    number: '1'
    run_exports:
        - mpfr >=4.0.2,<5.0a0
    string: h62dcd97_1
requirements:
    build:
        - vs2017_win-64 19.16.27032.1 hb4161e2_2
        - vswhere 2.7.1 h21ff451_0
    host:
        - mpir 3.0.0 hec2e145_1
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_2
    run:
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    commands:
        - if not exist %LIBRARY_INC%\\mpfr.h exit 1
        - if not exist %LIBRARY_LIB%\\mpfr.lib exit 1
        - if not exist %LIBRARY_BIN%\\mpfr.dll exit 1
        - if not exist %LIBRARY_LIB%\\mpfr_static.lib exit 1
    requires:
        - vs2017_win-64
about:
    home: http://www.mpfr.org/
    license: LGPL-3.0-only
    license_file: C:\ci\mpfr_1593116193042\work/COPYING.LESSER
    summary: The MPFR library is a C library for multiple-precision floating-point
        computations with correct rounding.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - isuruf
        - jakirkham
        - marcelotrevisani
