# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# C:\ci\containers\00001p8n0q3\tmp\build\80754af9\combined_recipe, last modified Mon Oct 12 18:21:14 2020
# ------------------------------------------------

package:
    name: ujson
    version: 4.0.1
source:
    fn: ujson-4.0.1.tar.gz
    sha256: 26cf6241b36ff5ce4539ae687b6b02673109c5e3efc96148806a7873eaa229d3
    url: https://pypi.io/packages/source/u/ujson/ujson-4.0.1.tar.gz
build:
    number: '0'
    script: C:\\ci\\ujson_1602523369547\\_h_env\\python.exe -m pip install . -vv
    string: py37ha925a31_0
requirements:
    build:
        - vs2017_win-64 19.16.27032.1 hb4161e2_3
        - vswhere 2.7.1 h21ff451_0
    host:
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py37_0
        - openssl 1.1.1h he774522_0
        - pip 20.2.3 py37_0
        - python 3.7.9 h60c2a47_0
        - setuptools 50.3.0 py37h9490d1a_1
        - setuptools-scm 4.1.2 py_0
        - setuptools_scm 4.1.2 0
        - sqlite 3.33.0 h2a8f88b_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - wheel 0.35.1 py_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - python >=3.7,<3.8.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    imports:
        - ujson
about:
    dev_url: https://github.com/ultrajson/ultrajson
    home: https://github.com/ultrajson/ultrajson
    license: BSD-3-Clause
    license_file: LICENSE.txt
    summary: Ultra fast JSON decoder and encoder written in C with Python bindings
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - kszucs
        - synapticarbors
