# This file created by conda-build 3.20.2
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Sun Sep 13 20:27:50 2020
# ------------------------------------------------

package:
    name: coin3d
    version: 4.0.0
source:
    -   patches:
            - 0001-cpack.d-is-now-optional.patch
        sha256: b00d2a8e9d962397cf9bf0d9baa81bcecfbd16eef675a98c792f5cf49eb6e805
        url: https://github.com/coin3d/coin/archive/Coin-4.0.0.tar.gz
    -   folder: superglue
        patches:
            - superglue.patch
        sha256: f408adcfb706e7c781db9c218ef9e8ba56d43995ccb61dffad5f6154c34f17d6
        url: https://github.com/coin3d/superglu/archive/superglu-1.3.0.tar.gz
build:
    number: '1010'
    string: h84d8830_1010
requirements:
    build:
        - cmake 3.18.2 h33f27b4_0
        - ninja 1.10.1 h7ef1ec2_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - vs2017_win-64 19.16.27038 h2e3bad8_2
        - vswhere 2.7.1 h21ff451_0
    host:
        - boost-cpp 1.72.0 hd4e6614_3
        - bzip2 1.0.8 he774522_3
        - expat 2.2.9 h33f27b4_2
        - lz4-c 1.9.2 h62dcd97_2
        - vc 14.1 h869be7e_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - xz 5.2.5 h62dcd97_1
        - zlib 1.2.11 h62dcd97_1009
        - zstd 1.4.5 h1f3a1b7_2
    run:
        - boost-cpp >=1.72.0,<1.72.1.0a0
        - expat >=2.2.9,<2.3.0a0
        - expat >=2.2.9,<2.3.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012
test:
    commands:
        - where /r "%PREFIX%"  Coin4.dll
    requires:
        - vs2017_win-64
about:
    description: Coin3D is a high-level, retained-mode toolkit for effective 3D graphics
        development. It is API compatible with Open Inventor 2.1.
    dev_url: https://bitbucket.org/Coin3D/coin/wiki/Home
    doc_url: https://bitbucket.org/Coin3D/coin/wiki/Home
    home: https://bitbucket.org/Coin3D/coin/wiki/Home
    license: BSD 3-Clause
    license_family: BSD
    license_file: COPYING
    summary: Coin3D is a c++ high-level 3D graphics toolkit.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - looooo
