# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/pull-recipes-openpyxl/recipe, last modified Sat Aug 22 16:17:45 2020
# ------------------------------------------------

package:
    name: openpyxl
    version: 3.0.5
source:
    sha256: 18e11f9a650128a12580a58e3daba14e00a11d9e907c554a17ea016bf1a2c71b
    url: https://pypi.io/packages/source/o/openpyxl/openpyxl-3.0.5.tar.gz
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/openpyxl_1598113097404/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
        -m pip install . --no-deps -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.2.2 py38_0
        - python 3.8.5 hcff3b4d_0
        - readline 8.0 h7b6447c_0
        - setuptools 49.6.0 py38_0
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - et_xmlfile
        - jdcal
        - python >=3.6
test:
    imports:
        - openpyxl
        - openpyxl.cell
        - openpyxl.chart
        - openpyxl.chartsheet
        - openpyxl.comments
        - openpyxl.compat
        - openpyxl.descriptors
        - openpyxl.drawing
        - openpyxl.formatting
        - openpyxl.formula
        - openpyxl.packaging
        - openpyxl.pivot
        - openpyxl.reader
        - openpyxl.styles
        - openpyxl.utils
        - openpyxl.workbook
        - openpyxl.workbook.external_link
        - openpyxl.worksheet
        - openpyxl.writer
        - openpyxl.xml
about:
    description: 'openpyxl is a Python library to read/write Excel 2010

        xlsx/xlsm/xltx/xltm files.

        '
    dev_url: https://bitbucket.org/openpyxl/openpyxl/
    doc_source_url: https://bitbucket.org/openpyxl/openpyxl/src/default/doc/index.rst
    doc_url: https://openpyxl.readthedocs.io/
    home: https://openpyxl.readthedocs.io
    license: MIT
    license_family: MIT
    license_file: LICENCE.rst
    summary: A Python library to read/write Excel 2010 xlsx/xlsm files
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - curtisalexander
        - ocefpaf
