# This file created by conda-build 3.20.4
# ------------------------------------------------

package:
    name: libblas
    version: 3.8.0
source:
    patches:
        - patches/0001-Test-BLAS-and-LAPACKE-in-addition-to-LAPACK.patch
    url: https://github.com/Reference-LAPACK/lapack/archive/v3.8.0.tar.gz
build:
    number: 20
    run_exports:
        - libblas >=3.8.0,<4.0a0
    string: 20_mkl
requirements:
    host:
        - intel-openmp 2020.2 254
        - mkl 2020.2 256
    run:
        - mkl >=2020.2,<2021.0a0 256
    run_constrained:
        - blas * mkl
        - libcblas 3.8.0 20_mkl
        - liblapack 3.8.0 20_mkl
        - liblapacke 3.8.0 20_mkl
test:
    commands:
        - if not exist %LIBRARY_BIN%/libblas.dll exit 1
about:
    home: https://github.com/conda-forge/blas-feedstock
    license: BSD-3-Clause
    license_file:
        - LICENSE.txt
        - mkl_license.txt
    summary: Metapackage to select the BLAS variant. Use conda's pinning mechanism
        in your environment to control which variant you want.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - isuruf
        - jakirkham
        - ocefpaf
        - pelson
