# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# C:\ci\containers\00003235v0r\tmp\build\80754af9\rsync-recipes\comtypes-1.1.7-python_3.7-on-winbuilder, last modified Wed Jun 10 10:06:08 2020
# ------------------------------------------------

package:
    name: comtypes
    version: 1.1.7
source:
    fn: comtypes-1.1.7.tar.gz
    sha256: 77ba1f0bd59f669dfb26e45702042e0a41bd6aa924257c4d00f74cc11b0a6087
    url: https://github.com/enthought/comtypes/archive/1.1.7.tar.gz
build:
    number: '1001'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py37_1001
requirements:
    host:
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.1 py37_0
        - openssl 1.1.1g he774522_0
        - python 3.7.7 h81c818b_4
        - setuptools 47.1.1 py37_0
        - sqlite 3.31.1 h2a8f88b_1
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_2
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - comtypes
about:
    description: 'comtypes is a pure Python COM package based on the ctypes ffi foreign

        function library.The comtypes package makes it easy to access and implement

        both custom and dispatch based COM interfaces.While the pywin32 package

        contains superior client side support for dispatch based COM interfaces,it
        is

        not possible to access custom COM interfaces unless they are wrapped in

        C++-code.

        '
    dev_url: https://github.com/enthought/comtypes/
    doc_source_url: https://github.com/enthought/comtypes/blob/master/docs/source/index.rst
    doc_url: http://pythonhosted.org/comtypes/
    home: http://starship.python.net/crew/theller/comtypes/
    license: MIT
    license_file: LICENSE.txt
    summary: pure Python COM package
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nehaljwani
