# This file created by conda-build 3.20.2
# meta.yaml template originally from:
# C:\ci\containers\00001p8n0hm\tmp\build\80754af9\combined_recipe, last modified Tue Sep 29 17:38:20 2020
# ------------------------------------------------

package:
    name: gevent
    version: 20.9.0
source:
    fn: gevent-20.9.0.tar.gz
    patches:
        - 0001-Allow-include-flags-to-be-present-in-CFLAGS.patch
    sha256: 5f6d48051d336561ec08995431ee4d265ac723a64bba99cc58c3eb1a4d4f5c8d
    url: https://pypi.io/packages/source/g/gevent/gevent-20.9.0.tar.gz
build:
    number: '0'
    script:
        - copy %SRC_DIR%\deps\c-ares\ares_build.h.dist %SRC_DIR%\deps\c-ares\ares_build.h
        - C:\\ci\\gevent_1601397624717\\_h_env\\python.exe -m pip install . --no-deps
            --ignore-installed -vvv
    string: py37he774522_0
requirements:
    build:
        - vs2017_win-64 19.16.27032.1 hb4161e2_3
        - vswhere 2.7.1 h21ff451_0
    host:
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py37_0
        - cffi 1.14.3 py37h7a1dbc1_0
        - openssl 1.1.1h he774522_0
        - pip 20.2.2 py37_0
        - pycparser 2.20 py_2
        - python 3.7.9 h60c2a47_0
        - setuptools 49.6.0 py37_1
        - sqlite 3.33.0 h2a8f88b_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - wheel 0.35.1 py_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - cffi >=1.11.5
        - greenlet >=0.4.14
        - python >=3.7,<3.8.0a0
        - setuptools
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
        - zope.event
        - zope.interface
test:
    commands:
        - python -m pip check
    imports:
        - gevent
        - gevent.libev
    requires:
        - pip
about:
    description: 'Gevent uses greenlet to provide a high-level synchronous API on
        top of the libev event loop.

        '
    dev_url: https://github.com/gevent/gevent
    doc_url: https://www.gevent.org/contents.html
    home: https://www.gevent.org
    license: MIT
    license_family: MIT
    license_file:
        - LICENSE
        - deps/c-ares/LICENSE.md
        - deps/libev/LICENSE
        - deps/libuv/LICENSE
    summary: Coroutine-based network library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nehaljwani
