# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/packaging-20.4-on-linux_64, last modified Tue Jun 16 15:29:15 2020
# ------------------------------------------------

package:
    name: packaging
    version: '20.4'
source:
    sha256: 4357f74f47b9c12db93624a82154e9b120fa8293699949152b22065d556079f8
    url: https://pypi.io/packages/source/p/packaging/packaging-20.4.tar.gz
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/packaging_1592321439749/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
        -m pip install . --no-deps -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.2 py36_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.3 he6710b0_1
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.0.2 py36_3
        - python 3.6.10 h7579374_2
        - readline 8.0 h7b6447c_0
        - setuptools 47.1.1 py36_0
        - sqlite 3.31.1 h62c20be_1
        - tk 8.6.8 hbc83047_0
        - wheel 0.34.2 py36_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - pyparsing >=2.0.2
        - python
        - six
test:
    imports:
        - packaging
about:
    dev_url: https://github.com/pypa/packaging
    doc_source_url: https://github.com/pypa/packaging/tree/master/docs
    doc_url: https://packaging.pypa.io/en/latest/
    home: https://github.com/pypa/packaging
    license: Apache 2.0 or BSD 2-Clause
    license_file: LICENSE
    summary: Core utilities for Python packages
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mingwandroid
        - nicoddemus
