# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/flask-1.1.2-on-linux_canary, last modified Fri Apr 17 13:10:35 2020
# ------------------------------------------------

package:
    name: flask
    version: 1.1.2
source:
    fn: Flask-1.1.2.tar.gz
    sha256: 4efa1ae2d7c9865af48986de8aeb8504bf32c7f3d6fdc9353d34b21f4b127060
    url: https://pypi.io/packages/source/F/Flask/Flask-1.1.2.tar.gz
build:
    entry_points:
        - flask = flask.cli:main
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/flask_1587129249498/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.1 py36_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_0
        - openssl 1.1.1f h7b6447c_0
        - pip 20.0.2 py36_1
        - python 3.6.10 hcf32534_1
        - readline 8.0 h7b6447c_0
        - setuptools 46.1.3 py36_0
        - sqlite 3.31.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - wheel 0.34.2 py36_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - click >=5.1
        - itsdangerous >=0.24
        - jinja2 >=2.10.1
        - python
        - werkzeug >=0.15
test:
    commands:
        - flask --help
    imports:
        - flask
        - flask.json
about:
    description: 'Flask is a microframework for Python based on Werkzeug and Jinja2.
        It''s

        intended for getting started very quickly and was developed with best

        intentions in mind.

        '
    dev_url: https://github.com/pallets/flask
    doc_source_url: https://github.com/pallets/flask/blob/master/docs/index.rst
    doc_url: http://flask.pocoo.org/docs/1.0/
    home: http://flask.pocoo.org
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE.rst
    summary: A microframework based on Werkzeug, Jinja2 and good intentions.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - goanpeca
        - marcelotrevisani
        - nehaljwani
        - ukaratay
        - xylar
