# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\000033lpj6f\tmp\build\80754af9\rsync-recipes\libtiff-4.1.0-vc_14-cxx_compiler_vs2017-c_compiler_vs2017-on-winbuilder, last modified Mon Jun  1 12:09:55 2020
# ------------------------------------------------

package:
    name: libtiff
    version: 4.1.0
source:
    patches:
        - patches/0001-CVE-2017-11613_part1.patch
        - patches/0002-CVE-2017-11613_part2.patch
        - patches/fix_TIFFReadRawStrip_man_page_typo.patch
    sha256: 5d29f32517dadb6dbcd1255ea5bbc93a2b54b94fbf83653b4d65c7d6775b8634
    url: https://download.osgeo.org/libtiff/tiff-4.1.0.tar.gz
build:
    missing_dso_whitelist:
        - /opt/X11/lib/libGL.1.dylib
        - /opt/X11/lib/libglut.3.dylib
    number: '1'
    run_exports:
        - libtiff >=4.1.0,<5.0a0
    string: h56a325e_1
requirements:
    build:
        - ca-certificates 2020.1.1 0
        - cmake 3.17.2 h33f27b4_0
        - ninja 1.9.0 py38h74a9793_0
        - openssl 1.1.1g he774522_0
        - python 3.8.3 he1778fa_0
        - sqlite 3.31.1 h2a8f88b_1
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_2
        - vs2017_win-64 19.16.27032.1 hb4161e2_2
        - vswhere 2.7.1 h21ff451_0
        - zlib 1.2.11 h62dcd97_4
    host:
        - jpeg 9b hb83a4c4_2
        - lz4-c 1.9.2 h62dcd97_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_2
        - xz 5.2.5 h62dcd97_0
        - zlib 1.2.11 h62dcd97_4
        - zstd 1.4.4 ha9fde0e_3
    run:
        - jpeg >=9b,<10a
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
        - xz >=5.2.5,<6.0a0
        - zlib >=1.2.11,<1.3.0a0
        - zstd >=1.4
        - zstd >=1.4.4,<1.4.5.0a0
test:
    commands:
        - if not exist %PREFIX%\\Library\\bin\\tiff.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\tiffxx.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\libtiff.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\libtiffxx.dll exit 1
about:
    description: 'This software provides support for the Tag Image File Format (TIFF),
        a

        widely used format for storing image data.

        '
    doc_url: http://www.libtiff.org/document.html
    home: http://www.libtiff.org/
    license: HPND
    license_file: COPYRIGHT
    summary: Support for the Tag Image File Format (TIFF).
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mingwandroid
        - msarahan
        - ocefpaf
        - stuarteberg
