# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\000037t86dn\tmp\build\80754af9\pull-recipes-sympy\recipe, last modified Mon Aug 10 19:11:54 2020
# ------------------------------------------------

package:
    name: sympy
    version: 1.6.2
source:
    sha256: 1cfadcc80506e4b793f5b088558ca1fcbeaec24cd6fc86f1fdccaa3ee1d48708
    url: https://pypi.io/packages/source/s/sympy/sympy-1.6.2.tar.gz
build:
    entry_points:
        - isympy = isympy:main
    number: '0'
    script: C:\\ci\\sympy_1597083371142\\_h_env\\python.exe -m pip install . --no-deps
        --ignore-installed --no-cache-dir -vvv
    string: py37_0
requirements:
    host:
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py37_0
        - mpmath 1.1.0 py37_0
        - openssl 1.1.1g he774522_0
        - pip 20.2.1 py37_0
        - python 3.7.7 h81c818b_4
        - setuptools 49.2.1 py37_0
        - sqlite 3.32.3 h2a8f88b_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - wheel 0.34.2 py37_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - mpmath >=0.19
        - python >=3.7,<3.8.0a0
    run_constrained:
        - antlr-python-runtime >=4.7,<4.8
test:
    commands:
        - isympy --help
    imports:
        - sympy
about:
    description: 'SymPy is a Python library for symbolic mathematics. It aims to become
        a

        full-featured computer algebra system (CAS) while keeping the code as

        simple as possible in order to be comprehensible and easily extensible.

        '
    dev_url: https://github.com/sympy/sympy
    doc_source_url: https://github.com/sympy/sympy/tree/master/doc
    doc_url: https://docs.sympy.org/latest/index.html
    home: https://sympy.org
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Python library for symbolic mathematics
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - asmeurer
        - msarahan
        - scopatz
