# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\000020i4105\tmp\build\80754af9\rsync-recipes\ipykernel-5.3.4-python_3.7-on-winbuilder, last modified Fri Jul 31 15:41:26 2020
# ------------------------------------------------

package:
    name: ipykernel
    version: 5.3.4
source:
    sha256: 9b2652af1607986a1b231c62302d070bc0534f564c393a5d9d130db9abbbe89d
    url: https://pypi.io/packages/source/i/ipykernel/ipykernel-5.3.4.tar.gz
build:
    number: '0'
    script:
        - C:\\ci\\ipykernel_1596208728219\\_h_env\\python.exe setup.py bdist_wheel
        - cd dist
        - C:\\ci\\ipykernel_1596208728219\\_h_env\\python.exe -m pip install ipykernel-5.3.4-py3-none-any.whl
            --no-deps -vv
        - C:\\ci\\ipykernel_1596208728219\\_h_env\\python.exe -m ipykernel install
            --sys-prefix
    string: py37h5ca1d4c_0
requirements:
    host:
        - backcall 0.2.0 py_0
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py37_0
        - colorama 0.4.3 py_0
        - decorator 4.4.2 py_0
        - ipython 7.16.1 py37h5ca1d4c_0
        - ipython_genutils 0.2.0 py37_0
        - jedi 0.17.1 py37_0
        - jupyter_client 6.1.6 py_0
        - jupyter_core 4.6.3 py37_0
        - libsodium 1.0.18 h62dcd97_0
        - openssl 1.1.1g he774522_0
        - parso 0.7.0 py_0
        - pickleshare 0.7.5 py37_1001
        - pip 20.1.1 py37_1
        - prompt-toolkit 3.0.5 py_0
        - pygments 2.6.1 py_0
        - python 3.7.7 h81c818b_4
        - python-dateutil 2.8.1 py_0
        - pywin32 227 py37he774522_1
        - pyzmq 19.0.1 py37ha925a31_1
        - setuptools 49.2.0 py37_0
        - six 1.15.0 py_0
        - sqlite 3.32.3 h2a8f88b_0
        - tornado 6.0.4 py37he774522_1
        - traitlets 4.3.3 py37_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - wcwidth 0.2.5 py_0
        - wheel 0.34.2 py37_0
        - wincertstore 0.2 py37_0
        - zeromq 4.3.2 ha925a31_2
        - zlib 1.2.11 h62dcd97_4
    run:
        - ipython >=5.0
        - jupyter_client
        - python >=3.7,<3.8.0a0
        - tornado >=4.2
        - traitlets >=4.1
test:
    commands:
        - jupyter kernelspec list
    imports:
        - ipykernel
    requires:
        - curio
        - flaky
        - ipython
        - nose
        - numpy
        - pytest !=5.3.4
about:
    description: 'A powerful interactive Python shell and a Jupyter kernel to work
        with

        Python code in Jupyter notebooks and other interactive frontends.

        '
    dev_url: https://github.com/ipython/ipykernel
    doc_source_url: https://github.com/ipython/ipykernel/blob/master/docs/index.rst
    doc_url: https://ipython.readthedocs.io
    home: https://ipython.org
    license: BSD-3-Clause
    license_family: BSD
    license_file: COPYING.md
    summary: IPython Kernel for Jupyter
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - Carreau
        - blink1073
        - bollwyvl
        - jakirkham
        - minrk
        - ocefpaf
        - pelson
