# This file created by conda-build 3.20.4
# meta.yaml template originally from:
# C:\ci\containers\0000160bu7d\tmp\build\80754af9\rsync-recipes\matplotlib-base-3.3.2-python_3.7-on-winbuilder, last modified Thu Oct 22 08:33:48 2020
# ------------------------------------------------

package:
    name: matplotlib-base
    version: 3.3.2
source:
    sha256: a17664009de73849906de076c1de60d2854d26325d012cdd0b5e75edb8bd8edb
    url: https://github.com/matplotlib/matplotlib/archive/v3.3.2.tar.gz
build:
    number: '0'
    string: py37hba9282a_0
requirements:
    build:
        - vs2017_win-64 19.16.27032.1 hb4161e2_3
        - vswhere 2.7.1 h21ff451_0
    host:
        - blas 1.0 mkl
        - ca-certificates 2020.10.14 0
        - certifi 2020.6.20 py37_0
        - cycler 0.10.0 py37_0
        - freetype 2.10.4 hd328e21_0
        - icc_rt 2019.0.0 h0cc432a_1
        - intel-openmp 2019.4 245
        - libpng 1.6.37 h2a8f88b_0
        - mkl 2019.4 245
        - mkl-service 2.3.0 py37hb782905_0
        - mkl_fft 1.0.14 py37h6288b17_0
        - mkl_random 1.0.4 py37h343c172_0
        - nose 1.3.7 py37_1004
        - numpy 1.15.4 py37h19fb1c0_0
        - numpy-base 1.15.4 py37hc3f5095_0
        - openssl 1.1.1h he774522_0
        - pip 20.2.4 py37_0
        - pyparsing 2.4.7 py_0
        - python 3.7.9 h60c2a47_0
        - python-dateutil 2.8.1 py_0
        - setuptools 50.3.0 py37h9490d1a_1
        - six 1.15.0 py_0
        - sqlite 3.33.0 h2a8f88b_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - wheel 0.35.1 py_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - certifi >=2020.06.20
        - cycler >=0.10
        - freetype >=2.10.4,<3.0a0
        - kiwisolver >=1.0.1
        - numpy >=1.15.4,<2.0a0
        - pillow >=6.2.0
        - pyparsing >=2.0.3,!=2.0.4,!=2.1.2,!=2.1.6
        - python >=3.7,<3.8.0a0
        - python-dateutil >=2.1
        - setuptools
        - tornado
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
about:
    description: 'matplotlib is a python 2D plotting library which produces publication

        quality figures in a variety of hardcopy formats and interactive

        environments across platforms. matplotlib can be used in Python scripts,

        the Python and IPython shell (ala MATLAB or Mathematica), web

        application servers, and six graphical user interface toolkits.

        '
    dev_url: https://github.com/matplotlib/matplotlib/
    doc_url: http://matplotlib.org/contents.html
    home: http://matplotlib.org/
    license: LicenseRef-PSF-based
    license_family: PSF
    license_file: LICENSE/LICENSE
    license_url: http://matplotlib.sourceforge.net/users/license.html
    summary: Publication quality figures in Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dopplershift
        - mdboom
        - ocefpaf
        - pelson
        - tacaswell
