# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Tue Oct 13 03:56:30 2020
# ------------------------------------------------

package:
    name: pyqt
    version: 5.12.3
source:
    -   folder: pyqt5
        patches:
            - 0003-configure.patch
            - 0004-configure-winbat.patch
            - py2_segfault.diff
            - qt5_dll.diff
        sha1: f442a876794947a24474cf85eb02abd60f00f642
        url: https://distfiles.macports.org/py-pyqt5/PyQt5_gpl-5.12.3.tar.gz
    -   folder: sip
        patches:
            - 0001-Do-not-override-CC-CXX-LINK-in-sipgen-Makefile.patch
            - sip-get_config_h_filename.patch
        sha1: d001eb00f6dae26a952770e805b1519f61cae77d
        url: https://distfiles.macports.org/py-sip/sip-4.19.18.tar.gz
    -   folder: pyqtwebengine
        sha1: 737acf93ecf39e5e2136e094a8b0a9ffa47bd2de
        url: https://distfiles.macports.org/py-pyqt5/PyQtWebEngine_gpl-5.12.1.tar.gz
    -   folder: pyqtcharts
        sha1: 6a876ac37d0ccb5392f67669de5e790c8f9188da
        url: https://github.com/ocefpaf/pyqt-feedstock/releases/download/v5.12.3/PyQtChart_gpl-5.12.tar.gz
build:
    number: '4'
    run_exports: pyqt >=5.12.3,<5.13.0a0
    string: py37h1834ac0_4
requirements:
    build:
        - jom 1.1.3 0
        - vs2017_win-64 19.16.27038 h2e3bad8_2
        - vswhere 2.7.1 h21ff451_0
    host:
        - ca-certificates 2020.6.20 hecda079_0
        - icu 67.1 h33f27b4_0
        - jpeg 9d he774522_0
        - libclang 10.0.1 default_hf44288c_1
        - libpng 1.6.37 ha81a0f5_2
        - openssl 1.1.1h he774522_0
        - python 3.7.8 h60c2a47_1_cpython
        - python_abi 3.7 1_cp37m
        - qt 5.12.9 hb2cf2c5_0
        - sqlite 3.33.0 he774522_1
        - vc 14.1 h869be7e_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - zlib 1.2.11 h62dcd97_1009
    run:
        - python >=3.7,<3.8.0a0
        - python_abi 3.7.* *_cp37m
        - qt >=5.12.9,<5.13.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012
test:
    files:
        - pyqt_test.py
    imports:
        - PyQt5.QtChart
        - PyQt5.QtCore
        - PyQt5.QtGui
        - PyQt5.QtHelp
        - PyQt5.QtMultimedia
        - PyQt5.QtMultimediaWidgets
        - PyQt5.QtNetwork
        - PyQt5.QtOpenGL
        - PyQt5.QtPrintSupport
        - PyQt5.QtQml
        - PyQt5.QtQuick
        - PyQt5.QtSvg
        - PyQt5.QtTest
        - PyQt5.QtWebChannel
        - PyQt5.QtWebEngine
        - PyQt5.QtWebEngineCore
        - PyQt5.QtWebEngineWidgets
        - PyQt5.QtWebSockets
        - PyQt5.QtWidgets
        - PyQt5.QtXml
        - PyQt5.QtXmlPatterns
        - PyQt5.sip
about:
    description: '"PyQt is a set of Python v2 and v3 bindings for The Qt Company''s
        Qt

        application framework and runs on all platforms supported by Qt including

        Windows, MacOS/X and Linux. PyQt5 supports Qt v5. PyQt4 supports Qt v4 and

        will build against Qt v5. The bindings are implemented as a set of Python

        modules and contain over 1,000 classes."

        '
    dev_url: https://github.com/pyqt
    doc_url: https://www.riverbankcomputing.com/software/pyqt/
    home: http://www.riverbankcomputing.co.uk/software/pyqt
    license: LicenseRef-Commercial or GPL-2.0-only or GPL-3.0-only
    license_family: GPL
    license_file: pyqt5/LICENSE
    summary: Python binding of the cross-platform GUI toolkit Qt.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - gillins
        - jschueller
        - mingwandroid
        - msarahan
        - ocefpaf
