# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Wed Oct 14 09:08:43 2020
# ------------------------------------------------

package:
    name: soqt
    version: 1.6.0
source:
    -   patches:
            - 0001-make-cpack-optional-and-disabled-by-default.patch
        sha256: 9f535af59f07c907022815679681bd345c9dec2f408c74833f6b1b24bca40e1f
        url: https://github.com/coin3d/soqt/releases/download/SoQt-1.6.0/soqt-1.6.0-src.tar.gz
build:
    number: '2'
    string: h95c7cbc_2
requirements:
    build:
        - cmake 3.18.2 h33f27b4_0
        - ninja 1.10.1 h7ef1ec2_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - vs2017_win-64 19.16.27038 h2e3bad8_2
        - vswhere 2.7.1 h21ff451_0
    host:
        - boost-cpp 1.74.0 hd4e6614_0
        - bzip2 1.0.8 he774522_3
        - ca-certificates 2020.6.20 hecda079_0
        - coin3d 4.0.0 h370ace1_1010
        - expat 2.2.9 h33f27b4_2
        - icu 67.1 h33f27b4_0
        - jpeg 9d he774522_0
        - libclang 10.0.1 default_hf44288c_1
        - libpng 1.6.37 ha81a0f5_2
        - lz4-c 1.9.2 h62dcd97_2
        - openssl 1.1.1h he774522_0
        - qt 5.12.9 hb2cf2c5_0
        - sqlite 3.33.0 he774522_1
        - vc 14.1 h869be7e_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - xz 5.2.5 h62dcd97_1
        - zlib 1.2.11 h62dcd97_1009
        - zstd 1.4.5 h1f3a1b7_2
    run:
        - coin3d
        - qt >=5.12.9,<5.13.0a0
        - qt >=5.12.9,<5.13.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012
test:
    commands:
        - cmake .
    files:
        - CMakeLists.txt
    requires:
        - cmake
about:
    description: SoQt is a Qt GUI component toolkit library for Coin.  It is also
        compatible with SGI and TGS Open Inventor, and the API is based on the API
        of the InventorXt GUI component toolkit.
    dev_url: https://bitbucket.org/Coin3D/soqt
    doc_url: https://bitbucket.org/Coin3D/soqt
    home: https://bitbucket.org/Coin3D/soqt
    license: BSD-3-Clause
    license_family: BSD
    license_file: COPYING
    summary: SoQt library needed by Coin3d.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - looooo
