# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Thu Feb 20 17:12:43 2020
# ------------------------------------------------

package:
    name: smesh
    version: 8.3.0.3
source:
    fn: smesh_8.3.0.3.tar.gz
    sha256: bd5bddd509e5120bdd56178c37471984062e8abd36465389d64fb6e1b811a1d4
    url: https://github.com/LaughlinResearch/SMESH/archive/v8.3.0.3.tar.gz
build:
    number: '8'
    string: py37h662e0ea_8
requirements:
    build:
        - cmake 3.16.4 he025d50_0
        - ninja 1.10.0 h1ad3211_0
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
        - vs2015_win-64 14.0.25420 h55c1224_11
    host:
        - boost-cpp 1.72.0 h0caebb8_0
        - bzip2 1.0.8 hfa6e2cd_2
        - ca-certificates 2019.11.28 hecc5488_0
        - curl 7.68.0 h4496350_0
        - expat 2.2.9 he025d50_2
        - fontconfig 2.13.1 hb964e45_1001
        - freetype 2.10.0 h563cfd7_1
        - future 0.18.2 py37_0
        - hdf4 4.2.13 hf8e6fe8_1003
        - hdf5 1.10.5 nompi_ha405e13_1104
        - icu 64.2 he025d50_1
        - jpeg 9c hfa6e2cd_1001
        - jsoncpp 1.8.4 h1ad3211_1002
        - krb5 1.16.4 hdd46e55_0
        - libcurl 7.68.0 h4496350_0
        - libiconv 1.15 hfa6e2cd_1005
        - libnetcdf 4.7.3 nompi_hc957ea6_101
        - libpng 1.6.37 h7602738_0
        - libssh2 1.8.2 h642c060_2
        - libtiff 4.1.0 h21b02b4_3
        - libxml2 2.9.10 h9ce36c8_0
        - lz4-c 1.8.3 he025d50_1001
        - netgen 6.2.1808 py37hb990d29_1007
        - occt 7.4.0 h823b557_1
        - openssl 1.1.1d hfa6e2cd_0
        - pthreads-win32 2.9.1 hfa6e2cd_3
        - python 3.7.6 h5b45d93_2
        - sqlite 3.30.1 hfa6e2cd_0
        - tbb 2019.9 he980bc4_1
        - tbb-devel 2019.9 he980bc4_1
        - tk 8.6.10 hfa6e2cd_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
        - vtk 8.2.0 py37h4a1a8eb_208
        - xz 5.2.4 h2fa13f4_1001
        - zlib 1.2.11 h2fa13f4_1006
        - zstd 1.4.4 hd8a0e53_1
    run:
        - boost-cpp >=1.72.0,<1.72.1.0a0
        - netgen
        - occt >=7.4.0,<7.5.0a0
        - pthreads-win32
        - python >=3.7,<3.8.0a0
        - tbb >=2019.9
        - vc >=14,<15.0a0
        - vtk >=8.2.0,<8.2.1.0a0
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - cmake -G "Ninja" .
    files:
        - CMakeLists.txt
    requires:
        - cmake
        - ninja
about:
    description: Standalone version of the meshing library from the Salome Platform.
    home: https://github.com/LaughlinResearch/SMESH
    license: LGPL2.1
    license_family: LGPL
    license_file: LICENSE.txt
    summary: A complete MESH framework based on the OCCT library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - looooo
