# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00000silcml\tmp\build\80754af9\rsync-recipes\menuinst-1.4.16-c_compiler_vs2017-python_3.7-on-winbuilder, last modified Thu Jun 11 11:37:07 2020
# ------------------------------------------------

package:
    name: menuinst
    version: 1.4.16
source:
    fn: menuinst-1.4.16.tar.gz
    sha256: c9ad6e225c2831656bac35b71ac1c8c3f82f08ba8da9718dfb3708485bbccc44
    url: https://github.com/ContinuumIO/menuinst/archive/1.4.16.tar.gz
build:
    entry_points:
        - menuinst = menuinst.main:main
    number: '1'
    skip_compile_pyc:
        - cwp.py
    string: py37he774522_1
requirements:
    host:
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.1 py37_0
        - openssl 1.1.1g he774522_0
        - python 3.7.7 h81c818b_4
        - setuptools 47.1.1 py37_0
        - sqlite 3.31.1 h2a8f88b_1
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_2
        - vs2017_win-64 19.16.27032.1 hb4161e2_2
        - vswhere 2.7.1 h21ff451_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - python >=3.7,<3.8.0a0
        - pywin32
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    commands:
        - menuinst -h
        - menuinst --version
    imports:
        - menuinst
        - menuinst.winshortcut
about:
    description: 'This application is used by Conda to create shortcuts on a wide
        variety of

        systems.

        '
    dev_url: https://github.com/ContinuumIO/menuinst
    doc_source_url: https://github.com/ContinuumIO/menuinst
    doc_url: https://pypi.python.org/pypi/menuinst/
    home: https://github.com/ContinuumIO/menuinst
    license: BSD
    summary: cross platform menu item installation
extra:
    copy_test_source_files: true
    final: true
