# This file created by conda-build 3.19.1
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Sat Mar 21 17:20:04 2020
# ------------------------------------------------

package:
    name: libwebp-base
    version: 1.1.0
source:
    sha256: 98a052268cc4d5ece27f76572a7f50293f439c17a98e67c4ea0c7ed6f50ef043
    url: http://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.1.0.tar.gz
build:
    number: '3'
    run_exports:
        - libwebp-base
    string: hfa6e2cd_3
requirements:
    build:
        - vs2015_win-64 14.0.25420 h55c1224_11
    host:
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
    run:
        - vc >=14,<15.0a0
    run_constrained:
        - libwebp 1.1.0
test:
    commands:
        - if not exist %LIBRARY_LIB%\\libwebp.lib exit 1
        - if not exist %LIBRARY_LIB%\\libwebpdemux.lib exit 1
        - if not exist %LIBRARY_LIB%\\libwebpdecoder.lib exit 1
        - if not exist %LIBRARY_BIN%\\libwebp.dll exit 1
        - if not exist %LIBRARY_BIN%\\libwebpdemux.dll exit 1
        - if not exist %LIBRARY_BIN%\\libwebpdecoder.dll exit 1
        - if not exist %LIBRARY_BIN%\\cwebp.exe exit 1
        - if not exist %LIBRARY_BIN%\\dwebp.exe exit 1
        - if not exist %LIBRARY_INC%\\webp\\decode.h exit 1
        - if not exist %LIBRARY_INC%\\webp\\encode.h exit 1
        - if not exist %LIBRARY_INC%\\webp\\types.h exit 1
about:
    description: 'WebP is a method of lossy and lossless compression that can be used
        on a

        large variety of photographic, translucent and graphical images found on the

        web. The degree of lossy compression is adjustable so a user can choose the

        trade-off between file size and image quality.

        libwebp-base provides the headers and shared libraries. For cwebp and dwep,

        binaries install libwebp.

        '
    dev_url: https://chromium.googlesource.com/webm/libwebp
    doc_url: https://developers.google.com/speed/webp/docs/using
    home: https://developers.google.com/speed/webp
    license: BSD-3-Clause
    license_file: COPYING
    summary: WebP image library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - carterbox
        - dschreij
        - ocefpaf
