# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\0000325qdl7\tmp\build\80754af9\rsync-recipes\watchdog-0.10.3-python_3.7-on-winbuilder, last modified Mon Jun 29 09:13:30 2020
# ------------------------------------------------

package:
    name: watchdog
    version: 0.10.3
source:
    fn: watchdog-0.10.3.tar.gz
    sha256: 4214e1379d128b0588021880ccaf40317ee156d4603ac388b9adcf29165e0c04
    url: https://pypi.io/packages/source/w/watchdog/watchdog-0.10.3.tar.gz
build:
    entry_points:
        - watchmedo = watchdog.watchmedo:main
    number: '0'
    script: C:\\ci\\watchdog_1593446515400\\_h_env\\python.exe -m pip install . --no-deps
        -vv
    string: py37_0
requirements:
    host:
        - ca-certificates 2020.1.1 0
        - certifi 2020.6.20 py37_0
        - openssl 1.1.1g he774522_0
        - pip 20.1.1 py37_1
        - python 3.7.7 h81c818b_4
        - setuptools 47.3.1 py37_0
        - sqlite 3.32.3 h2a8f88b_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_2
        - wheel 0.34.2 py37_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - argh >=0.24.1
        - pathtools >=0.1.1
        - python >=3.7,<3.8.0a0
        - pyyaml >=3.10
test:
    commands:
        - python -m pip check
        - watchmedo --help
    imports:
        - watchdog
        - watchdog.observers
        - watchdog.tricks
        - watchdog.utils
    requires:
        - pip
about:
    doc_url: http://pythonhosted.org/watchdog
    home: http://github.com/gorakhargosh/watchdog
    license: Apache 2.0
    license_file: LICENSE
    summary: Filesystem events monitoring
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - andfoy
        - ccordoba12
        - goanpeca
        - rlaverde
