# This file created by conda-build 3.20.4
# meta.yaml template originally from:
# C:\ci\containers\00003e01uuk\tmp\build\80754af9\rsync-recipes\regex-2020.10.11-python_3.7-on-winbuilder, last modified Wed Oct 14 07:15:49 2020
# ------------------------------------------------

package:
    name: regex
    version: 2020.10.11
source:
    sha256: 463e770c48da76a8da82b8d4a48a541f314e0df91cbb6d873a341dbe578efafd
    url: https://pypi.io/packages/source/r/regex/regex-2020.10.11.tar.gz
build:
    number: '0'
    script: C:\\ci\\regex_1602668717004\\_h_env\\python.exe -m pip install . --no-deps
        -vv
    string: py37he774522_0
requirements:
    build:
        - vs2017_win-64 19.16.27032.1 hb4161e2_3
        - vswhere 2.7.1 h21ff451_0
    host:
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py37_0
        - openssl 1.1.1h he774522_0
        - pip 20.2.3 py37_0
        - python 3.7.9 h60c2a47_0
        - setuptools 50.3.0 py37h9490d1a_1
        - sqlite 3.33.0 h2a8f88b_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - wheel 0.35.1 py_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - python >=3.7,<3.8.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    imports:
        - regex
about:
    home: https://bitbucket.org/mrabarnett/mrab-regex
    license: Python-2.0
    license_family: PSF
    summary: Alternative regular expression module, to replace re
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - kwilcox
        - ocefpaf
        - xhochy
