# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Wed Sep 30 06:32:45 2020
# ------------------------------------------------

package:
    name: libtheora
    version: 1.1.1
source:
    fn: libtheora-1.1.1.tar.bz2
    sha256: b6ae1ee2fa3d42ac489287d3ec34c5885730b1296f0801ae577a35193d3affbc
    url: http://downloads.xiph.org/releases/theora/libtheora-1.1.1.tar.bz2
build:
    number: '1004'
    run_exports:
        - libtheora >=1.1.1,<1.2.0a0
    string: h62dcd97_1004
requirements:
    build:
        - cmake 3.18.2 h33f27b4_0
        - gettext 0.19.8.1 hb01d8f6_1002
        - glib 2.58.3 hc0c2ac7_1002
        - libffi 3.2.1 ha925a31_1007
        - libiconv 1.16 he774522_0
        - m2w64-gcc-libgfortran 5.3.0 6
        - m2w64-gcc-libs 5.3.0 7
        - m2w64-gcc-libs-core 5.3.0 7
        - m2w64-gmp 6.1.0 2
        - m2w64-libwinpthread-git 5.0.0.4634.697f757 2
        - msys2-conda-epoch 20160418 1
        - pcre 8.44 h6538335_0
        - pkg-config 0.29.2 h8cfccfd_1006
        - vc 14.1 h869be7e_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - vs2017_win-64 19.16.27038 h2e3bad8_2
        - vswhere 2.7.1 h21ff451_0
        - zlib 1.2.11 h62dcd97_1009
    host:
        - libogg 1.3.2 hfa6e2cd_1002
        - vc 14.1 h869be7e_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
    run:
        - libogg 1.3.*
        - libogg >=1.3.2,<1.4.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012
test:
    commands:
        - if exist %PREFIX%\\Library\\lib\\theora.lib (exit 0) else (exit 1)
        - if exist %PREFIX%\\Library\\include\\theora.h (exit 0) else (exit 1)
        - if exist %PREFIX%\\Library\\bin\\theora.dll (exit 0) else (exit 1)
        - if exist %PREFIX%\\Library\\lib\\theoradec.lib (exit 0) else (exit 1)
        - if exist %PREFIX%\\Library\\include\\theoradec.h (exit 0) else (exit 1)
        - if exist %PREFIX%\\Library\\bin\\theoradec.dll (exit 0) else (exit 1)
        - if exist %PREFIX%\\Library\\lib\\theoraenc.lib (exit 0) else (exit 1)
        - if exist %PREFIX%\\Library\\include\\theoraenc.h (exit 0) else (exit 1)
        - if exist %PREFIX%\\Library\\bin\\theoraenc.dll (exit 0) else (exit 1)
about:
    home: https://theora.org
    license: BSD-3-Clause
    license_family: BSD
    license_file: COPYING
    summary: Theora is a free and open video compression format from the Xiph.org
        Foundation.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - bgruening
        - dschreij
