# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/threadpoolctl-2.1.0-on-linux_64, last modified Wed Jun 17 21:32:54 2020
# ------------------------------------------------

package:
    name: threadpoolctl
    version: 2.1.0
source:
    sha256: 314ef000fb78883c653a5644ffd202ffda8b874006c6bbe90de0db7db08ff9f3
    url: https://github.com/joblib/threadpoolctl/archive/2.1.0.tar.gz
build:
    noarch: python
    number: '0'
    script:
        - FLIT_ROOT_INSTALL=1 /tmp/build/80754af9/threadpoolctl_1592429666438/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
            -m flit install
    string: pyh5ca1d4c_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - brotlipy 0.7.0 py37h7b6447c_1000
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.2 py37_0
        - cffi 1.14.0 py37he30daa8_1
        - chardet 3.0.4 py37_1003
        - cryptography 2.9.2 py37h1ba5d50_0
        - docutils 0.16 py37_1
        - flit 2.3.0 py_0
        - flit-core 2.3.0 py_0
        - idna 2.9 py_1
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.3 he6710b0_1
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.1.1 py37_1
        - pycparser 2.20 py_0
        - pygments 2.6.1 py_0
        - pyopenssl 19.1.0 py37_0
        - pysocks 1.7.1 py37_0
        - python 3.7.7 hcff3b4d_5
        - pytoml 0.1.21 py_0
        - readline 8.0 h7b6447c_0
        - requests 2.23.0 py37_0
        - requests_download 0.1.2 py37_0
        - setuptools 47.3.0 py37_0
        - six 1.15.0 py_0
        - sqlite 3.31.1 h62c20be_1
        - tk 8.6.8 hbc83047_0
        - urllib3 1.25.9 py_0
        - wheel 0.34.2 py37_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=3.5
test:
    commands:
        - python -m threadpoolctl -i numpy
    imports:
        - threadpoolctl
    requires:
        - numpy
about:
    description: 'Python helpers to introspect and limit the number of threads used

        in native libraries that handle their own internal threadpool

        (BLAS and OpenMP implementations).

        '
    dev_url: https://github.com/joblib/threadpoolctl
    doc_url: https://github.com/joblib/threadpoolctl
    home: https://github.com/joblib/threadpoolctl
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Python helpers to control the threadpools of native libraries
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jeremiedbb
        - ogrisel
        - tomMoral
