# This file created by conda-build 3.17.8
# ------------------------------------------------

package:
    name: libllvm9
    version: 9.0.1
source:
    patches:
        - patches/amd-roc-2.7.0.diff
        - patches/intel-D47188-svml-VF.patch
        - patches/numba-0001-Revert-Limit-size-of-non-GlobalValue-name.patch
    sha256: 00a1ee1f389f81e9979f3a640a01c431b3021de0d42278f6508391a2f0b81c9a
    url: https://github.com/llvm/llvm-project/releases/download/llvmorg-9.0.1/llvm-9.0.1.src.tar.xz
build:
    activate_in_script: true
    number: 0
    string: h21ff451_0
requirements:
    build:
        - vs2017_win-64 19.16.27032.1 hb8d98e7_1
        - vswhere 2.7.1 h21ff451_0
    run:
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
about:
    dev_url: https://github.com/llvm-mirror/llvm
    home: http://llvm.org/
    license: LLVM-Exception
    license_family: Apache
    license_file: LICENSE.TXT
    summary: Development headers and libraries for LLVM
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - SylvainCorlay
        - inducer
        - isuruf
        - jakirkham
        - mattwala
        - mingwandroid
        - pitrou
