# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00003fjoriu\tmp\build\80754af9\rsync-recipes\snappy-1.1.8-on-winbuilder, last modified Mon Jun 22 23:49:48 2020
# ------------------------------------------------

package:
    name: snappy
    version: 1.1.8
source:
    fn: snappy-1.1.8.tar.gz
    patches:
        - skip-microbenchmarks.patch
        - windows-static-lib-name.patch
    sha256: 16b677f07832a612b0836178db7f374e414f94657c138e6993cbfc5dcc58651f
    url: https://github.com/google/snappy/archive/1.1.8.tar.gz
build:
    number: '0'
    run_exports:
        - snappy >=1.1.8,<2.0a0
    string: h33f27b4_0
requirements:
    build:
        - cmake 3.17.2 h33f27b4_0
        - vs2015_runtime 14.16.27012 hf0eaf9b_2
        - vs2017_win-64 19.16.27032.1 hb4161e2_2
        - vswhere 2.7.1 h21ff451_0
    host:
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_2
    run:
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    commands:
        - if not exist %LIBRARY_INC%\snappy.h exit 1
        - if not exist %LIBRARY_INC%\snappy-stubs-public.h exit 1
        - if not exist %LIBRARY_LIB%\snappy.lib exit 1
        - if not exist %LIBRARY_BIN%\snappy.dll exit 1
        - if not exist %LIBRARY_LIB%\snappy_static.lib exit 1
about:
    description: 'Snappy is a compression/decompression library. It does not aim for
        maximum

        compression, or compatibility with any other compression library; instead,
        it

        aims for very high speeds and reasonable compression. For instance, compared
        to

        the fastest mode of zlib, Snappy is an order of magnitude faster for most

        inputs, but the resulting compressed files are anywhere from 20% to 100%

        bigger.

        '
    dev_url: https://github.com/google/snappy
    home: https://github.com/google/snappy
    license: BSD 3-clause
    license_family: BSD
    license_file: COPYING
    summary: A fast compressor/decompressor
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - MaxRis
        - dougalsutherland
        - groutr
        - jakirkham
        - wesm
        - xhochy
