# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# C:\ci\containers\00001p8n0qs\tmp\build\80754af9\rsync-recipes\astropy-4.0.2-python_3.7-on-winbuilder, last modified Tue Oct 13 16:09:10 2020
# ------------------------------------------------

package:
    name: astropy
    version: 4.0.2
source:
    sha256: 4014e472cc7d3ca225524bf56bf4087042cc564849cfc528c435414c2f2f4b7e
    url: https://pypi.io/packages/source/a/astropy/astropy-4.0.2.tar.gz
build:
    detect_binary_files_with_prefix: false
    entry_points:
        - fits2bitmap = astropy.visualization.scripts.fits2bitmap:main
        - fitscheck = astropy.io.fits.scripts.fitscheck:main
        - fitsdiff = astropy.io.fits.scripts.fitsdiff:main
        - fitsheader = astropy.io.fits.scripts.fitsheader:main
        - fitsinfo = astropy.io.fits.scripts.fitsinfo:main
        - samp_hub = astropy.samp.hub_script:hub_script
        - volint = astropy.io.votable.volint:main
        - wcslint = astropy.wcs.wcslint:main
    number: '0'
    string: py37he774522_0
requirements:
    build:
        - vs2017_win-64 19.16.27032.1 hb4161e2_3
        - vswhere 2.7.1 h21ff451_0
    host:
        - blas 1.0 mkl
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py37_0
        - cython 0.29.14 py37ha925a31_0
        - icc_rt 2019.0.0 h0cc432a_1
        - intel-openmp 2019.4 245
        - jinja2 2.10.3 py_0
        - markupsafe 1.1.1 py37hfa6e2cd_1
        - mkl 2019.4 245
        - mkl-service 2.3.0 py37hb782905_0
        - mkl_fft 1.0.14 py37h6288b17_0
        - mkl_random 1.0.4 py37h343c172_0
        - numpy 1.16.6 py37h5510c5b_0
        - numpy-base 1.16.6 py37hc3f5095_0
        - openssl 1.1.1h he774522_0
        - pip 20.2.3 py37_0
        - python 3.7.9 h60c2a47_0
        - setuptools 50.3.0 py37h9490d1a_1
        - six 1.15.0 py_0
        - sqlite 3.33.0 h2a8f88b_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - wheel 0.35.1 py_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - numpy >=1.16.6,<2.0a0
        - python >=3.7,<3.8.0a0
        - setuptools
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    commands:
        - fits2bitmap --help
        - fitscheck --help
        - fitsdiff --help
        - fitsheader --help
        - fitsinfo --help
        - samp_hub --help
        - volint --help
        - wcslint --help
    imports:
        - astropy
    requires:
        - pytest-astropy
about:
    description: 'The Astropy Project is a community effort to develop a single package
        for

        Astronomy in Python. It contains core functionality and common tools

        needed for performing astronomy and astrophysics research with Python.

        '
    dev_url: https://github.com/astropy/astropy
    doc_url: http://docs.astropy.org/en/stable/
    home: http://www.astropy.org/
    license: BSD-3-Clause
    license_file: LICENSE.rst
    summary: Community-developed Python Library for Astronomy
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - astrofrog-conda-forge
        - bsipocz
        - mwcraig
