# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Mon Oct  5 15:47:58 2020
# ------------------------------------------------

package:
    name: joblib
    version: 0.17.0
source:
    sha256: 6dd8d75808624ac60434a3c6de4623dc49e4f9f3332501b467c36b0fbfdd54c9
    url: https://github.com/joblib/joblib/archive/0.17.0.tar.gz
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/joblib_1601912903842/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
        -m pip install . -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1h h7b6447c_0
        - pip 20.2.3 py38_0
        - python 3.8.5 h7579374_1
        - readline 8.0 h7b6447c_0
        - setuptools 49.6.0 py38_1
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=3.6
        - setuptools
test:
    commands:
        - pip check
    imports:
        - joblib
        - joblib.externals
    requires:
        - pip
about:
    home: https://pypi.org/project/joblib/
    license: BSD-3-Clause
    license_file: LICENSE.txt
    summary: 'Lightweight pipelining: using Python functions as pipeline jobs.'
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - lesteve
        - ocefpaf
        - ogrisel
        - pierreglaser
        - tomMoral
