CI: azure
c_compiler: vs2017
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: vs2017
extend_keys:
- extend_keys
- pin_run_as_build
- ignore_version
- ignore_build_only_deps
fortran_compiler: gfortran
freetype: 2.9.1
ignore_build_only_deps:
- numpy
- python
jpeg: '9'
liblapacke: 3.8.0 *netlib
libpng: '1.6'
libtiff: 4.1.0
libwebp: '1.1'
lua: '5'
numpy: '1.16'
perl: 5.26.2
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  freetype:
    max_pin: x
  jpeg:
    max_pin: x
  libpng:
    max_pin: x.x
  libtiff:
    max_pin: x
  zlib:
    max_pin: x.x
python: 3.7.* *_cpython
r_base: '3.4'
target_platform: win-64
vc: '14'
zip_keys:
- - numpy
  - python
zlib: '1.2'
