# This file created by conda-build 3.20.3
# ------------------------------------------------

package:
    name: opencv
    version: 4.4.0
source:
    -   fn: opencv-4.4.0.tar.gz
        sha256: 7faa0991c74cda52313ee37ef73f3e451332a47e7aa36c2bb2240b69f5002d27
        url: https://codeload.github.com/opencv/opencv/zip/4.4.0
    -   fn: opencv_contrib-4.4.0.tar.gz
        folder: opencv_contrib
        sha256: a69772f553b32427e09ffbfd0c8d5e5e47f7dab8b3ffc02851ffd7f912b76840
        url: https://codeload.github.com/opencv/opencv_contrib/tar.gz/4.4.0
build:
    noarch: false
    number: '3'
    string: py37_3
requirements:
    run:
        - libopencv 4.4.0 py37_3
        - py-opencv 4.4.0 py37hc6149b9_3
test:
    files:
        - CMakeLists.txt
        - test.cpp
    requires:
        - cmake
        - liblapack * *mkl
        - ninja
        - vs2017_win-64
about:
    home: http://opencv.org/
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Computer vision and machine learning software library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - hajapy
        - hmaarrfk
        - jakirkham
        - msarahan
        - ocefpaf
        - patricksnape
        - zym1010
