# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\000010v2rqt\tmp\build\80754af9\rsync-recipes\scipy-1.5.2-python_3.7-on-winbuilder, last modified Mon Aug 10 20:26:35 2020
# ------------------------------------------------

package:
    name: scipy
    version: 1.5.2
source:
    sha256: f2c055e286a9421135407d3cb3efd3f1f7ae9a465b5edc0be14ac8c5c63f6ea1
    url: https://github.com/scipy/scipy/archive/v1.5.2.tar.gz
build:
    number: '0'
    string: py37h9439919_0
requirements:
    build:
        - intel-fortran_win-64 2019.0.0 hf4e3f46_1
    host:
        - blas 1.0 mkl
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py37_0
        - cython 0.29.21 py37ha925a31_0
        - icc_rt 2019.0.0 h0cc432a_1
        - intel-openmp 2019.4 245
        - mkl 2019.4 245
        - mkl-devel 2019.4 245
        - mkl-include 2019.4 245
        - mkl-service 2.3.0 py37hb782905_0
        - numpy-base 1.14.6 py37hc3f5095_5
        - numpy-devel 1.14.6 py37h4ba5984_5
        - openssl 1.1.1g he774522_1
        - pip 20.2.2 py37_0
        - pybind11 2.5.0 py37h74a9793_0
        - python 3.7.7 h81c818b_4
        - setuptools 49.6.0 py37_0
        - six 1.15.0 py_0
        - sqlite 3.32.3 h2a8f88b_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - wheel 0.34.2 py37_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - blas 1.0 mkl
        - icc_rt >=2019.0.0
        - mkl >=2019.4,<2020.0a0
        - mkl-service >=2,<3.0a0
        - numpy >=1.14.6,<2.0a0
        - python >=3.7,<3.8.0a0
test:
    requires:
        - intel-openmp 2019.*
        - mpmath
        - pytest
        - pytest-xdist
about:
    description: 'SciPy is a Python-based ecosystem of open-source software for mathematics,

        science, and engineering.

        '
    dev_url: https://github.com/scipy/scipy
    doc_url: http://www.scipy.org/docs.html
    home: http://www.scipy.org/
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: Scientific Library for Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - msarahan
        - ocefpaf
        - rgommers
