# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Oct  5 08:07:05 2020
# ------------------------------------------------

package:
    name: win32_setctime
    version: 1.0.3
source:
    sha256: 4e88556c32fdf47f64165a2180ba4552f8bb32c1103a2fafd05723a0bd42bd4b
    url: https://pypi.io/packages/source/w/win32_setctime/win32_setctime-1.0.3.tar.gz
build:
    noarch: python
    number: '0'
    script: '/home/conda/feedstock_root/build_artifacts/win32_setctime_1601885290666/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
        -m pip install . -vv '
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py38h32f6830_0
        - ld_impl_linux-64 2.35 h769bd43_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - ncurses 6.2 he1b5a44_1
        - openssl 1.1.1h h516909a_0
        - pip 20.2.3 py_0
        - python 3.8.5 h1103e12_9_cpython
        - python_abi 3.8 1_cp38
        - readline 8.0 he28a2e2_2
        - setuptools 49.6.0 py38h32f6830_1
        - sqlite 3.33.0 h4cf870e_0
        - tk 8.6.10 hed695b0_0
        - wheel 0.35.1 pyh9f0ad1d_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1009
    run:
        - python >=3.5
test:
    imports:
        - win32_setctime
about:
    home: https://github.com/Delgan/win32-setctime
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: A small Python utility to set file creation time on Windows
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - xhochy
