# This file created by conda-build 3.20.2
# meta.yaml template originally from:
# C:\ci\containers\000015220kt\tmp\build\80754af9\rsync-recipes\numba-0.51.2-python_3.7-on-winbuilder, last modified Tue Sep 15 13:16:02 2020
# ------------------------------------------------

package:
    name: numba
    version: 0.51.2
source:
    sha256: c3385ddea40bcf2edfe405844ef9df97e23e5b8b7f635883a5e987f519e6441b
    url: https://github.com/numba/numba/archive/0.51.2.tar.gz
build:
    entry_points:
        - numba = numba.misc.numba_entry:main
        - pycc = numba.pycc:main
    number: '1'
    script:
        - C:\\ci\\numba_1600189362217\\_h_env\\python.exe setup.py build install --single-version-externally-managed
            --record=record.txt
    string: py37hf9181ef_1
requirements:
    build:
        - vs2017_win-64 19.16.27032.1 hb4161e2_3
        - vswhere 2.7.1 h21ff451_0
    host:
        - blas 1.0 mkl
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py37_0
        - icc_rt 2019.0.0 h0cc432a_1
        - intel-openmp 2020.2 254
        - llvmlite 0.34.0 py37h1a82afc_4
        - mkl 2020.2 256
        - numpy 1.11.3 py37h35d8231_12
        - numpy-base 1.11.3 py37hc3f5095_12
        - openssl 1.1.1g he774522_1
        - pip 20.2.2 py37_0
        - python 3.7.9 h60c2a47_0
        - setuptools 49.6.0 py37_0
        - sqlite 3.33.0 h2a8f88b_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - wheel 0.35.1 py_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - llvmlite >=0.34.0,<0.35
        - numpy >=1.11.3,<2.0a0
        - python >=3.7,<3.8.0a0
        - setuptools
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    imports:
        - numba
        - numba.core.annotations
        - numba.core.datamodel
        - numba.core.rewrites
        - numba.core.runtime
        - numba.core.typeconv
        - numba.core.typing
        - numba.core.unsafe
        - numba.cuda
        - numba.cuda.cudadrv
        - numba.cuda.kernels
        - numba.cuda.simulator
        - numba.cuda.simulator.cudadrv
        - numba.cuda.tests
        - numba.cuda.tests.cudadrv
        - numba.cuda.tests.cudadrv.data
        - numba.cuda.tests.cudapy
        - numba.cuda.tests.cudasim
        - numba.cuda.tests.nocuda
        - numba.experimental.jitclass
        - numba.np.ufunc
        - numba.pycc
        - numba.roc.servicelib
        - numba.scripts
        - numba.testing
        - numba.tests
        - numba.tests.npyufunc
    requires:
        - cffi
        - ipython
        - jinja2
        - numpy >=1.15,<1.19
        - scipy
        - setuptools
about:
    description: 'Numba is an Open Source NumPy-aware optimizing compiler for Python

        sponsored by Anaconda, Inc. It uses the remarkable LLVM compiler

        infrastructure to compile Python syntax to machine code."

        '
    dev_url: https://github.com/numba/numba
    doc_url: http://numba.pydata.org/
    home: http://numba.github.com
    license: BSD-2-Clause
    license_family: BSD
    license_file: LICENSE
    summary: NumPy aware dynamic Python compiler using LLVM
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - henryiii
        - jakirkham
        - marcelotrevisani
        - mbargull
        - souravsingh
        - step21
