# This file created by conda-build 3.20.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Oct 23 15:42:16 2020
# ------------------------------------------------

package:
    name: plotly
    version: 4.12.0
source:
    sha256: 9ec2c9f4cceac7c595ebb77c98cbeb6566a97bef777508584d9bb7d9bcb8854c
    url: https://pypi.io/packages/source/p/plotly/plotly-4.12.0.tar.gz
build:
    noarch: python
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/plotly_1603467793398/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
        -m pip install . --no-deps -vv
    string: pyh9f0ad1d_0
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py36h9880bd3_2
        - ld_impl_linux-64 2.35 h769bd43_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - ncurses 6.2 he1b5a44_2
        - openssl 1.1.1h h516909a_0
        - pip 20.2.4 py_0
        - python 3.6.11 h4d41432_2_cpython
        - python_abi 3.6 1_cp36m
        - readline 8.0 he28a2e2_2
        - setuptools 49.6.0 py36h9880bd3_2
        - sqlite 3.33.0 h4cf870e_1
        - tk 8.6.10 hed695b0_1
        - wheel 0.35.1 pyh9f0ad1d_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1010
    run:
        - python
        - retrying >=1.3.3
        - setuptools
        - six
test:
    commands:
        - pip check
    imports:
        - plotly
    requires:
        - pip
about:
    description: 'Plotly''s Python graphing library makes interactive,

        publication-quality graphs online. Examples of how to make line

        plots, scatter plots, area charts, bar charts, error bars, box plots,

        histograms, heatmaps, subplots, multiple-axes, polar charts and

        bubble charts.

        '
    dev_url: https://github.com/plotly/plotly.py
    doc_url: https://plot.ly/python/
    home: https://plot.ly/python/
    license: MIT
    license_file: /home/conda/recipe_root/LICENSE.txt
    summary: An interactive, browser-based graphing library for Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - chohner
        - moorepants
        - ocefpaf
