# This file created by conda-build 3.20.0
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/pydocstyle-5.1.1-on-linux_64, last modified Mon Aug 31 14:40:52 2020
# ------------------------------------------------

package:
    name: pydocstyle
    version: 5.1.1
source:
    sha256: 19b86fa8617ed916776a11cd8bc0197e5b9856d5433b777f51a3defe13075325
    url: https://pypi.io/packages/source/p/pydocstyle/pydocstyle-5.1.1.tar.gz
build:
    entry_points:
        - pydocstyle = pydocstyle.cli:main
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/pydocstyle_1598885001695/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
        -m pip install . --no-deps -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.2.2 py38_0
        - python 3.8.5 hcff3b4d_0
        - readline 8.0 h7b6447c_0
        - setuptools 49.6.0 py38_0
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=3.5
        - snowballstemmer
test:
    commands:
        - pydocstyle --version
    imports:
        - pydocstyle
about:
    description: 'pydocstyle is a static analysis tool for checking compliance with
        Python

        docstring conventions. pydocstyle supports most of PEP 257 out of the box,

        but it should not be considered a reference implementation.

        The framework for checking docstring style is flexible, and custom checks

        can be easily added, for example to cover NumPy docstring conventions.

        pydocstyle supports Python 3.4, 3.5, 3.6, and 3.7.

        '
    dev_url: https://github.com/PyCQA/pydocstyle
    doc_url: http://pydocstyle.readthedocs.org
    home: https://github.com/PyCQA/pydocstyle
    license: MIT
    license_file: LICENSE-MIT
    summary: Python docstring style checker (formerly pep257)
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - Nurdok
        - dopplershift
        - goanpeca
        - jakirkham
