# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# C:\ci\containers\00002uigoem\tmp\build\80754af9\rsync-recipes\bottleneck-1.3.2-python_3.7-on-winbuilder, last modified Wed Jun 10 04:01:46 2020
# ------------------------------------------------

package:
    name: bottleneck
    version: 1.3.2
source:
    sha256: 20179f0b66359792ea283b69aa16366419132f3b6cf3adadc0c48e2e8118e573
    url: https://pypi.io/packages/source/B/Bottleneck/Bottleneck-1.3.2.tar.gz
build:
    number: '1'
    script: C:\\ci\\bottleneck_1591762129194\\_h_env\\python.exe -m pip install .
        -vv
    string: py37h2a96729_1
requirements:
    build:
        - vs2017_win-64 19.16.27032.1 hb4161e2_2
        - vswhere 2.7.1 h21ff451_0
    host:
        - blas 1.0 mkl
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.1 py37_0
        - icc_rt 2019.0.0 h0cc432a_1
        - intel-openmp 2019.4 245
        - mkl 2019.4 245
        - mkl-service 2.3.0 py37hb782905_0
        - mkl_fft 1.0.14 py37h6288b17_0
        - mkl_random 1.0.4 py37h343c172_0
        - numpy 1.14.6 py37ha06f490_5
        - numpy-base 1.14.6 py37hc3f5095_5
        - openssl 1.1.1g he774522_0
        - pip 20.0.2 py37_3
        - python 3.7.7 h81c818b_4
        - setuptools 47.1.1 py37_0
        - six 1.15.0 py_0
        - sqlite 3.31.1 h2a8f88b_1
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_2
        - wheel 0.34.2 py37_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - numpy >=1.14.6,<2.0a0
        - python >=3.7,<3.8.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    commands:
        - python -c "import bottleneck; bottleneck.test()"
    imports:
        - bottleneck
        - bottleneck.move
        - bottleneck.nonreduce
        - bottleneck.nonreduce_axis
        - bottleneck.reduce
        - bottleneck.slow
        - bottleneck.tests
    requires:
        - pytest
about:
    description: 'Bottleneck is a collection of fast NumPy array functions written
        in

        Cython.

        '
    dev_url: https://github.com/pydata/bottleneck
    doc_url: https://bottleneck.readthedocs.io
    home: https://github.com/pydata/bottleneck
    license: BSD-2-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Fast NumPy array functions written in Cython.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - msarahan
        - ocefpaf
        - qwhelan
        - wesm
