# This file created by conda-build 3.0.30
# meta.yaml template originally from:
# C:\ci\containers\00001dd1g10\tmp\build\80754af9\rsync-recipes\mpir-3.0.0-cxx_compilervs2015python3.6c_compilervs2015-on-winbuilder, last modified Tue Nov 21 11:55:12 2017
# ------------------------------------------------

package:
    name: mpir
    version: 3.0.0
source:
    sha256: 52f63459cf3f9478859de29e00357f004050ead70b45913f2c2269d9708675bb
    url: http://mpir.org/mpir-3.0.0.tar.bz2
build:
    number: '1'
    string: hec2e145_1
requirements:
    build:
        - certifi 2017.7.27.1 py36h043bc9e_0
        - pip 9.0.1 py36h226ae91_4
        - python 3.6.3 h3b118a2_4
        - setuptools 36.5.0 py36h65f9e6e_0
        - vc 14 h2379b0c_2
        - vs2015_runtime 14.0.25123 hd4c4e62_2
        - vs2015_win-64 14.0.25123 hf5d5b87_2
        - wheel 0.30.0 py36h6c3ec14_1
        - wincertstore 0.2 py36h7fe50ca_0
    run:
        - vc 14.*
test:
    commands:
        - if not exist %LIBRARY_INC%\\mpir.h exit 1
        - if not exist %LIBRARY_INC%\\mpirxx.h exit 1
        - if not exist %LIBRARY_INC%\\gmp.h exit 1
        - if not exist %LIBRARY_INC%\\gmpxx.h exit 1
        - if not exist %LIBRARY_LIB%\\mpir.lib exit 1
        - if not exist %LIBRARY_LIB%\\gmp.lib exit 1
        - if not exist %LIBRARY_BIN%\\mpir.dll exit 1
        - if not exist %LIBRARY_BIN%\\gmp.dll exit 1
        - if not exist %LIBRARY_LIB%\\mpir_static.lib exit 1
        - if not exist %LIBRARY_LIB%\\mpirxx_static.lib exit 1
        - if not exist %LIBRARY_LIB%\\gmp_static.lib exit 1
        - if not exist %LIBRARY_LIB%\\gmpxx_static.lib exit 1
    files:
        - test.c
about:
    home: http://mpir.org/
    license: LGPL 3
    license_file: COPYING.LIB
    summary: Multiple Precision Integers and Rationals.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - isuruf
        - jakirkham
