#!/bin/sh
'''exec' /tmp/build/80754af9/qtawesome_1602272867890/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python "$0" "$@"
' '''
# -*- coding: utf-8 -*-
import re
import sys
from qtawesome.icon_browser import run
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(run())
