# This file created by conda-build 3.20.3
# ------------------------------------------------

package:
    name: importlib_metadata
    version: 2.0.0
source:
    sha256: 77a540690e24b0305878c37ffd421785a6f7e53c8b5720d211b211de8d0e95da
    url: https://pypi.io/packages/source/i/importlib_metadata/importlib_metadata-2.0.0.tar.gz
build:
    noarch: generic
    number: 1
    string: '1'
requirements:
    run:
        - importlib-metadata >=2.0.0,<2.0.1.0a0
test:
    imports:
        - importlib_metadata
about:
    home: https://gitlab.com/python-devs/importlib_metadata
    license: Apache-2.0
    license_family: APACHE
    license_file: LICENSE
    summary: A library to access the metadata for a Python package
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - marcelotrevisani
        - nehaljwani
        - nicoddemus
