# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# C:\ci\containers\000016i26mf\tmp\build\80754af9\combined_recipe, last modified Wed Dec  9 11:51:44 2020
# ------------------------------------------------

package:
    name: openssl
    version: 1.1.1i
source:
    fn: openssl-1.1.1i.tar.gz
    patches:
        - 0001-Don-t-use-USE_BCRYPTGENRANDOM-for-VS-older-than-2015.patch
    sha256: e8be6a35fe41d10603c3cc635e93289ed00bf34b79671a3a4de64fcee00d5242
    url: http://www.openssl.org/source/openssl-1.1.1i.tar.gz
build:
    binary_has_prefix_files: null
    detect_binary_files_with_prefix: true
    number: '0'
    run_exports:
        - openssl >=1.1.1i,<1.1.2a
    string: h2bbff1b_0
requirements:
    build:
        - m2-msys2-runtime 2.5.0.17080.65c939c 3
        - m2-patch 2.7.5 2
        - msys2-conda-epoch 20160418 1
        - nasm 2.13.03 h62dcd97_1
        - vs2015_runtime 14.27.29016 h5e58377_2
        - vs2017_win-64 19.16.27032.1 hb4161e2_3
        - vswhere 2.7.1 h21ff451_0
    host:
        - perl 5.26.2.1 h0c8e037_0
        - vc 14.2 h21ff451_1
        - vs2015_runtime 14.27.29016 h5e58377_2
    run:
        - ca-certificates
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    commands:
        - copy NUL checksum.txt
        - openssl sha256 checksum.txt
        - python -c "from six.moves import urllib; urllib.request.urlopen('https://pypi.org')"
    requires:
        - python 3.7.*
        - six
about:
    dev_url: https://github.com/openssl/openssl
    doc_url: https://www.openssl.org/docs/man1.1.1/
    home: http://www.openssl.org/
    license: OpenSSL
    license_family: Apache
    license_file: LICENSE
    summary: OpenSSL is an open-source implementation of the SSL and TLS protocols
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - carlodri
        - chenghlee
        - jakirkham
        - jjhelmus
        - msarahan
        - ocefpaf
        - pelson
