# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00002uigoma\tmp\build\80754af9\pull-recipes-pickleshare\recipe, last modified Fri Jul 10 07:27:01 2020
# ------------------------------------------------

package:
    name: pickleshare
    version: 0.7.5
source:
    sha256: 87683d47965c1da65cdacaf31c8441d12b8044cdec9aca500cd78fc2c683afca
    url: https://pypi.io/packages/source/p/pickleshare/pickleshare-0.7.5.tar.gz
build:
    number: '1001'
    script: C:\ci\pickleshare_1594374056827\_h_env\python.exe -m pip install . --no-deps
        --ignore-installed --no-cache-dir -vvv
    string: py37_1001
requirements:
    host:
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py37_0
        - openssl 1.1.1g he774522_0
        - pip 20.1.1 py37_1
        - python 3.7.7 h81c818b_4
        - setuptools 47.3.1 py37_0
        - sqlite 3.32.3 h2a8f88b_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - wheel 0.34.2 py37_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - pickleshare
about:
    description: 'PickleShare is a small "shelve" like datastore with concurrency
        support.

        Like shelve, a PickleShareDB object acts like a normal dictionary. Unlike

        shelve, many processes can access the database simultaneously. Changing a

        value in database is immediately visible to other processes accessing the

        same database.

        '
    dev_url: https://github.com/pickleshare/pickleshare
    doc_source_url: https://github.com/pickleshare/pickleshare/blob/master/README.md
    doc_url: https://pypi.python.org/pypi/pickleshare
    home: https://github.com/pickleshare/pickleshare/
    license: MIT
    license_file: LICENSE
    summary: Tiny 'shelve'-like database with concurrency support
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
        - pelson
        - takluyver
