# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# Z:\Work\Anaconda\anaconda-depends-metapackage\recipes\win-64\_anaconda_depends-2020.07-py37_0, last modified Thu Jul 23 22:46:04 2020
# ------------------------------------------------

package:
    name: _anaconda_depends
    version: '2020.07'
build:
    ignore_run_exports:
        - '*'
    number: '0'
    string: py37_0
requirements:
    is_meta_pkg:
        - true
    run:
        - alabaster
        - anaconda-client
        - anaconda-project
        - argh
        - asn1crypto
        - astroid
        - astropy
        - atomicwrites
        - attrs
        - autopep8
        - babel
        - backcall
        - backports
        - backports.shutil_get_terminal_size
        - bcrypt
        - beautifulsoup4
        - bitarray
        - bkcharts
        - blas
        - bleach
        - blosc
        - bokeh
        - boto
        - bottleneck
        - brotlipy
        - bzip2
        - ca-certificates
        - certifi
        - cffi
        - chardet
        - click
        - cloudpickle
        - clyent
        - colorama
        - comtypes
        - console_shortcut
        - contextlib2
        - cryptography
        - curl
        - cycler
        - cython
        - cytoolz
        - dask
        - dask-core
        - decorator
        - defusedxml
        - diff-match-patch
        - distributed
        - docutils
        - entrypoints
        - et_xmlfile
        - fastcache
        - filelock
        - flake8
        - flask
        - freetype
        - fsspec
        - future
        - get_terminal_size
        - gevent
        - glob2
        - gmpy2
        - greenlet
        - h5py
        - hdf5
        - heapdict
        - html5lib
        - icc_rt
        - icu
        - idna
        - imageio
        - imagesize
        - importlib-metadata
        - importlib_metadata
        - intel-openmp
        - intervaltree
        - ipykernel
        - ipython
        - ipython_genutils
        - ipywidgets
        - isort
        - itsdangerous
        - jdcal
        - jedi
        - jinja2
        - joblib
        - jpeg
        - json5
        - jsonschema
        - jupyter
        - jupyter_client
        - jupyter_console
        - jupyter_core
        - jupyterlab
        - jupyterlab_server
        - keyring
        - kiwisolver
        - krb5
        - lazy-object-proxy
        - libarchive
        - libcurl
        - libiconv
        - liblief
        - libllvm9
        - libpng
        - libsodium
        - libspatialindex
        - libssh2
        - libtiff
        - libxml2
        - libxslt
        - llvmlite
        - locket
        - lxml
        - lz4-c
        - lzo
        - m2w64-gcc-libgfortran
        - m2w64-gcc-libs
        - m2w64-gcc-libs-core
        - m2w64-gmp
        - m2w64-libwinpthread-git
        - markupsafe
        - matplotlib
        - matplotlib-base
        - mccabe
        - menuinst
        - mistune
        - mkl
        - mkl-service
        - mkl_fft
        - mkl_random
        - mock
        - more-itertools
        - mpc
        - mpfr
        - mpir
        - mpmath
        - msgpack-python
        - msys2-conda-epoch
        - multipledispatch
        - nbconvert
        - nbformat
        - networkx
        - nltk
        - nose
        - notebook
        - numba
        - numexpr
        - numpy
        - numpy-base
        - numpydoc
        - olefile
        - openpyxl
        - openssl
        - packaging
        - pandas
        - pandoc
        - pandocfilters
        - paramiko
        - parso
        - partd
        - path
        - path.py
        - pathlib2
        - pathtools
        - patsy
        - pep8
        - pexpect
        - pickleshare
        - pillow
        - pip
        - pkginfo
        - pluggy
        - ply
        - powershell_shortcut
        - prometheus_client
        - prompt-toolkit
        - prompt_toolkit
        - psutil
        - py
        - py-lief
        - pycodestyle
        - pycosat
        - pycparser
        - pycrypto
        - pycurl
        - pydocstyle
        - pyflakes
        - pygments
        - pylint
        - pynacl
        - pyodbc
        - pyopenssl
        - pyparsing
        - pyqt
        - pyreadline
        - pyrsistent
        - pysocks
        - pytables
        - pytest
        - python 3.7.*
        - python-dateutil
        - python-jsonrpc-server
        - python-language-server
        - python-libarchive-c
        - pytz
        - pywavelets
        - pywin32
        - pywin32-ctypes
        - pywinpty
        - pyyaml
        - pyzmq
        - qdarkstyle
        - qt
        - qtawesome
        - qtconsole
        - qtpy
        - regex
        - requests
        - rope
        - rtree
        - ruamel_yaml
        - scikit-image
        - scikit-learn
        - scipy
        - seaborn
        - send2trash
        - setuptools
        - simplegeneric
        - singledispatch
        - sip
        - six
        - snappy
        - snowballstemmer
        - sortedcollections
        - sortedcontainers
        - soupsieve
        - sphinx
        - sphinxcontrib
        - sphinxcontrib-applehelp
        - sphinxcontrib-devhelp
        - sphinxcontrib-htmlhelp
        - sphinxcontrib-jsmath
        - sphinxcontrib-qthelp
        - sphinxcontrib-serializinghtml
        - sphinxcontrib-websupport
        - spyder
        - spyder-kernels
        - sqlalchemy
        - sqlite
        - statsmodels
        - sympy
        - tbb
        - tblib
        - terminado
        - testpath
        - threadpoolctl
        - tk
        - toml
        - toolz
        - tornado
        - tqdm
        - traitlets
        - typed-ast
        - typing_extensions
        - ujson
        - unicodecsv
        - urllib3
        - vc
        - vs2015_runtime
        - watchdog
        - wcwidth
        - webencodings
        - werkzeug
        - wheel
        - widgetsnbextension
        - win_inet_pton
        - win_unicode_console
        - wincertstore
        - winpty
        - wrapt
        - xlrd
        - xlsxwriter
        - xlwings
        - xlwt
        - xz
        - yaml
        - yapf
        - zeromq
        - zict
        - zipp
        - zlib
        - zope
        - zope.event
        - zope.interface
        - zstd
about:
    description: 'Anaconda is a Python distribution which includes over 400

        Python packages for science, math, engineering, and data analysis.

        '
    dev_url: https://github.com/ContinuumIO/anaconda
    doc_url: https://docs.anaconda.com/anaconda
    home: https://www.anaconda.com/distribution
    license: BSD
    summary: Simplifies package management and deployment of Anaconda
extra:
    copy_test_source_files: true
    final: true
