# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Mon Oct 12 21:47:27 2020
# ------------------------------------------------

package:
    name: libopencv
    version: 4.4.0
source:
    -   fn: opencv-4.4.0.tar.gz
        sha256: 7faa0991c74cda52313ee37ef73f3e451332a47e7aa36c2bb2240b69f5002d27
        url: https://codeload.github.com/opencv/opencv/zip/4.4.0
    -   fn: opencv_contrib-4.4.0.tar.gz
        folder: opencv_contrib
        sha256: a69772f553b32427e09ffbfd0c8d5e5e47f7dab8b3ffc02851ffd7f912b76840
        url: https://codeload.github.com/opencv/opencv_contrib/tar.gz/4.4.0
build:
    number: '3'
    run_exports:
        - libopencv >=4.4.0,<4.4.1.0a0
    string: py37_3
requirements:
    build:
        - cmake 3.18.2 h33f27b4_0
        - m2-msys2-runtime 2.5.0.17080.65c939c 3
        - m2-patch 2.7.5 2
        - msys2-conda-epoch 20160418 1
        - ninja 1.10.1 h7ef1ec2_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - vs2017_win-64 19.16.27038 h2e3bad8_2
        - vswhere 2.7.1 h21ff451_0
    host:
        - ca-certificates 2020.6.20 hecda079_0
        - eigen 3.3.7 he980bc4_1001
        - freetype 2.9.1 h563cfd7_1006
        - icu 64.2 he025d50_1
        - jpeg 9d he774522_0
        - libblas 3.8.0 10_h8933c1f_netlib
        - libcblas 3.8.0 10_h8933c1f_netlib
        - libclang 8.0.1 he980bc4_2
        - liblapack 3.8.0 10_h8933c1f_netlib
        - liblapacke 3.8.0 10_h8933c1f_netlib
        - libpng 1.6.37 ha81a0f5_2
        - libtiff 4.1.0 h885aae3_6
        - libwebp 1.1.0 4
        - libwebp-base 1.1.0 hfa6e2cd_3
        - lz4-c 1.9.2 h62dcd97_2
        - m2w64-gcc-libgfortran 5.3.0 6
        - m2w64-gcc-libs 5.3.0 7
        - m2w64-gcc-libs-core 5.3.0 7
        - m2w64-gmp 6.1.0 2
        - m2w64-libwinpthread-git 5.0.0.4634.697f757 2
        - msys2-conda-epoch 20160418 1
        - numpy 1.16.5 py37hc71023c_0
        - openssl 1.1.1h he774522_0
        - python 3.7.8 h60c2a47_1_cpython
        - python_abi 3.7 1_cp37m
        - qt 5.12.1 h444579a_0
        - sqlite 3.33.0 he774522_1
        - vc 14.1 h869be7e_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - xz 5.2.5 h62dcd97_1
        - zlib 1.2.11 h62dcd97_1009
        - zstd 1.4.5 h1f3a1b7_2
    run:
        - freetype >=2.9.1,<3.0a0
        - freetype >=2.9.1,<3.0a0
        - jpeg >=9d,<10a
        - liblapacke >=3.8.0,<3.9.0a0
        - libpng >=1.6.37,<1.7.0a0
        - libtiff >=4.1.0,<5.0a0
        - libwebp-base >=1.1.0,<2.0a0
        - python_abi 3.7.* *_cp37m
        - qt 5.12.*
        - qt >=5.12.1,<5.13.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - if not exist %PREFIX%\\Library\\bin\\opencv_aruco440.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_bgsegm440.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_calib3d440.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_ccalib440.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_core440.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_datasets440.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_dnn440.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_dpm440.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_face440.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_features2d440.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_flann440.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_fuzzy440.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_highgui440.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_imgcodecs440.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_imgproc440.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_line_descriptor440.dll exit
            1
        - if not exist %PREFIX%\\Library\\bin\\opencv_ml440.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_objdetect440.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_optflow440.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_phase_unwrapping440.dll exit
            1
        - if not exist %PREFIX%\\Library\\bin\\opencv_photo440.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_plot440.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_reg440.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_rgbd440.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_saliency440.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_shape440.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_stereo440.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_stitching440.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_structured_light440.dll exit
            1
        - if not exist %PREFIX%\\Library\\bin\\opencv_superres440.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_surface_matching440.dll exit
            1
        - if not exist %PREFIX%\\Library\\bin\\opencv_text440.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_tracking440.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_video440.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_videoio440.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_videostab440.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_xfeatures2d440.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_ximgproc440.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_xobjdetect440.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_xphoto440.dll exit 1
        - mkdir -p cmake_build_test && pushd cmake_build_test
        - cmake -G "Ninja" ..
        - cmake --build . --config Release
        - popd
    files:
        - CMakeLists.txt
        - test.cpp
    requires:
        - cmake
        - liblapack * *mkl
        - ninja
        - vs2017_win-64
about:
    home: http://opencv.org/
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Computer vision and machine learning software library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - hajapy
        - hmaarrfk
        - jakirkham
        - msarahan
        - ocefpaf
        - patricksnape
        - zym1010
