# This file created by conda-build 3.20.0
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/paramiko-2.7.2-on-linux_64, last modified Mon Aug 31 15:04:18 2020
# ------------------------------------------------

package:
    name: paramiko
    version: 2.7.2
source:
    fn: paramiko-2.7.2.tar.gz
    sha256: 7f36f4ba2c0d81d219f4595e35f70d56cc94f9ac40a6acdf51d6ca210ce65035
    url: https://pypi.io/packages/source/p/paramiko/paramiko-2.7.2.tar.gz
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/paramiko_1598886428689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py36_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.2.2 py36_0
        - python 3.6.10 h7579374_2
        - readline 8.0 h7b6447c_0
        - setuptools 49.6.0 py36_0
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - bcrypt >=3.1.3
        - cryptography >=2.5
        - pynacl >=1.0.1
        - python
test:
    imports:
        - paramiko
about:
    dev_url: https://github.com/paramiko/paramiko/
    doc_url: http://docs.paramiko.org/
    home: http://www.paramiko.org/
    license: LGPL-2.1-or-later
    license_family: LGPL
    license_file: LICENSE
    summary: SSH2 protocol library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - pmlandwehr
        - tschoonj
        - vamega
