# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Sun Aug 16 16:58:44 2020
# ------------------------------------------------

package:
    name: expat
    version: 2.2.9
source:
    sha256: f1063084dc4302a427dabcca499c8312b3a32a29b7d2506653ecc8f950a9a237
    url: https://github.com/libexpat/libexpat/releases/download/R_2_2_9/expat-2.2.9.tar.bz2
build:
    number: '2'
    run_exports:
        - expat >=2.2.9,<3.0a0
    string: h33f27b4_2
requirements:
    build:
        - cmake 3.18.0 h33f27b4_0
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - vs2017_win-64 19.16.27038 h2e3bad8_2
        - vswhere 2.7.1 h21ff451_0
    host:
        - vc 14.1 h869be7e_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
    run:
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012
test:
    commands:
        - xmlwf -h
about:
    home: http://expat.sourceforge.net/
    license: MIT
    license_family: MIT
    license_file: COPYING
    summary: Expat XML parser library in C
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - kwilcox
        - mingwandroid
        - msarahan
        - ocefpaf
        - pelson
        - scopatz
