# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/mock-4.0.2-on-linux_64, last modified Wed Apr 29 14:34:20 2020
# ------------------------------------------------

package:
    name: mock
    version: 4.0.2
source:
    sha256: dd33eb70232b6118298d516bbcecd26704689c386594f0f3c4f13867b2c56f72
    url: https://pypi.python.org/packages/source/m/mock/mock-4.0.2.tar.gz
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/mock_1588171901285/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
        -m pip install . --no-deps -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.1 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_0
        - openssl 1.1.1g h7b6447c_0
        - pip 20.0.2 py38_1
        - python 3.8.2 hcf32534_0
        - readline 8.0 h7b6447c_0
        - setuptools 46.1.3 py38_0
        - sqlite 3.31.1 h62c20be_1
        - tk 8.6.8 hbc83047_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=3.6
test:
    imports:
        - mock
about:
    home: https://github.com/testing-cabal/mock
    license: BSD-2-Clause
    license_file: LICENSE.txt
    summary: A library for testing in Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - ocefpaf
