# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/zict-2.0.0-on-linux_64, last modified Tue Mar 17 15:35:30 2020
# ------------------------------------------------

package:
    name: zict
    version: 2.0.0
source:
    fn: zict-2.0.0.tar.gz
    sha256: 8e2969797627c8a663575c2fc6fcb53a05e37cdb83ee65f341fc6e0c3d0ced16
    url: https://pypi.io/packages/source/z/zict/zict-2.0.0.tar.gz
build:
    noarch: python
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.1.1 0
        - certifi 2019.11.28 py36_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_0
        - openssl 1.1.1d h7b6447c_4
        - python 3.6.10 h0371630_0
        - readline 7.0 h7b6447c_5
        - setuptools 46.0.0 py36_0
        - sqlite 3.31.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - heapdict
        - python
test:
    imports:
        - zict
about:
    home: http://github.com/mrocklin/zict
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: Composable Dictionary Classes
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jrbourbeau
        - mrocklin
