# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00001882e5h\tmp\build\80754af9\rsync-recipes\msgpack-python-1.0.0-python_3.7-on-winbuilder, last modified Tue Mar 24 12:32:39 2020
# ------------------------------------------------

package:
    name: msgpack-python
    version: 1.0.0
source:
    sha256: 9534d5cc480d4aff720233411a1f765be90885750b07df772380b34c10ecb5c0
    url: https://pypi.io/packages/source/m/msgpack/msgpack-1.0.0.tar.gz
build:
    number: '1'
    script: C:\ci\msgpack-python_1585077780439\_h_env\python.exe -m pip install .
        -vv
    string: py37h74a9793_1
requirements:
    build:
        - vs2017_win-64 19.16.27032.1 hb8d98e7_1
        - vswhere 2.7.1 h21ff451_0
    host:
        - ca-certificates 2020.1.1 0
        - certifi 2019.11.28 py37_1
        - cython 0.29.15 py37ha925a31_0
        - openssl 1.1.1e he774522_0
        - pip 20.0.2 py37_1
        - python 3.7.7 h60c2a47_0_cpython
        - setuptools 46.1.1 py37_0
        - sqlite 3.31.1 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
        - wheel 0.34.2 py37_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    imports:
        - msgpack
about:
    description: 'MessagePack lets you exchange data among multiple languages like
        JSON.  But

        it is faster and smaller. Small integers are encoded into a single byte and

        typical short strings require only one extra byte in addition to the

        strings themselves.

        '
    dev_url: https://github.com/msgpack/msgpack
    doc_source_url: https://github.com/msgpack/msgpack-python/blob/master/docs/index.rst
    doc_url: http://msgpack-python.readthedocs.io/
    home: http://msgpack.org/
    license: Apache-2.0
    license_family: Apache
    license_file: COPYING
    summary: MessagePack (de)serializer
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - carlodri
        - jakirkham
        - ocefpaf
        - pmlandwehr
