# This file created by conda-build 3.19.2
# ------------------------------------------------

package:
    name: hdf5
    version: 1.10.6
source:
    patches:
        - patches/test_Makefile.in.patch
        - patches/testpar_Makefile.in.patch
    sha256: 5f9a3ee85db4ea1d3b1fa9159352aebc2af72732fc2f58c96a3f0768dba0e9aa
    url: https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.6/src/hdf5-1.10.6.tar.gz
build:
    number: 101
    run_exports:
        - hdf5 >=1.10.6,<1.10.7.0a0
    string: nompi_he0bbb20_101
requirements:
    build:
        - cmake 3.18.0 h33f27b4_0
        - ninja 1.10.0 h1ad3211_0
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - vs2017_win-64 19.16.27038 h2e3bad8_2
        - vswhere 2.7.1 h21ff451_0
    host:
        - vc 14.1 h869be7e_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - zlib 1.2.11 h2fa13f4_1006
    run:
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - where gif2h5
        - where h52gif
        - where h5copy
        - where h5debug
        - where h5diff
        - where h5dump
        - where h5import
        - where h5jam
        - where h5ls
        - where h5mkgrp
        - where h5repack
        - where h5repart
        - where h5stat
        - where h5unjam
        - if not exist %PREFIX%\\Library\\lib\\hdf5.lib exit 1
        - if not exist %PREFIX%\\Library\\bin\\hdf5.dll exit 1
        - if not exist %PREFIX%\\Library\\lib\\hdf5_cpp.lib exit 1
        - if not exist %PREFIX%\\Library\\bin\\hdf5_cpp.dll exit 1
        - if not exist %PREFIX%\\Library\\lib\\hdf5_hl.lib exit 1
        - if not exist %PREFIX%\\Library\\bin\\hdf5_hl.dll exit 1
        - if not exist %PREFIX%\\Library\\lib\\hdf5_hl_cpp.lib exit 1
        - if not exist %PREFIX%\\Library\\bin\\hdf5_hl_cpp.dll exit 1
    files:
        - compound_fortran2003.f90
        - h5_cmprss.c
        - h5_cmprss.f90
        - h5tutr_cmprss.cpp
    requires:
        - vs2017_win-64
about:
    home: http://www.hdfgroup.org/HDF5/
    license: HDF5
    license_family: BSD
    license_file: COPYING
    summary: HDF5 is a data model, library, and file format for storing and managing
        data
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - SylvainCorlay
        - astrofrog-conda-forge
        - beckermr
        - davidbrochart
        - gillins
        - groutr
        - jakirkham
        - marcelotrevisani
        - marqh
        - ocefpaf
        - scopatz
