# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00002uigp5v\tmp\build\80754af9\rsync-recipes\pylint-2.6.0-python_3.7-on-winbuilder, last modified Fri Aug 28 09:11:15 2020
# ------------------------------------------------

package:
    name: pylint
    version: 2.6.0
source:
    sha256: bb4a908c9dadbc3aac18860550e870f58e1a02c9f2c204fdf5693d73be061210
    url: https://pypi.io/packages/source/p/pylint/pylint-2.6.0.tar.gz
build:
    entry_points:
        - epylint = pylint:run_epylint
        - pylint = pylint:run_pylint
        - pyreverse = pylint:run_pyreverse
        - symilar = pylint:run_symilar
    number: '0'
    script: C:\\ci\\pylint_1598605958085\\_h_env\\python.exe -m pip install . --no-deps
        --ignore-installed --no-cache-dir -vvv
    string: py37_0
requirements:
    host:
        - atomicwrites 1.4.0 py_0
        - attrs 20.1.0 py_0
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py37_0
        - colorama 0.4.3 py_0
        - importlib-metadata 1.7.0 py37_0
        - importlib_metadata 1.7.0 0
        - iniconfig 1.0.1 py_0
        - more-itertools 8.4.0 py_0
        - openssl 1.1.1g he774522_1
        - packaging 20.4 py_0
        - pip 20.2.2 py37_0
        - pluggy 0.13.1 py37_0
        - py 1.9.0 py_0
        - pyparsing 2.4.7 py_0
        - pytest 6.0.1 py37_0
        - pytest-runner 5.2 py_0
        - python 3.7.7 h81c818b_4
        - setuptools 49.6.0 py37_0
        - six 1.15.0 py_0
        - sqlite 3.33.0 h2a8f88b_0
        - toml 0.10.1 py_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - wheel 0.35.1 py_0
        - wincertstore 0.2 py37_0
        - zipp 3.1.0 py_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - astroid >=2.4.0,<=2.5
        - colorama
        - isort >=4.2.5,<6
        - mccabe >=0.6,<0.7
        - python >=3.7,<3.8.0a0
        - toml >=0.7.1
test:
    commands:
        - pylint --help
        - where epylint
        - pyreverse --help
        - symilar --help
    imports:
        - pylint
        - pylint.checkers
        - pylint.extensions
        - pylint.pyreverse
        - pylint.reporters
        - pylint.reporters.ureports
about:
    description: 'Pylint is a tool that checks for errors in Python code, tries to
        enforce a

        coding standard and looks for code smells.

        '
    dev_url: https://github.com/PyCQA/pylint/
    doc_source_url: https://github.com/PyCQA/pylint/blob/master/doc/index.rst
    doc_url: https://pylint.readthedocs.io/en/latest/
    home: http://www.pylint.org/
    license: GPL-2.0-only
    license_file: COPYING
    summary: python code static checker
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - goanpeca
        - jakirkham
        - jjhelmus
        - timleslie
