# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\000037t86d4\tmp\build\80754af9\pull-recipes-path\recipe, last modified Sat Aug  8 18:19:35 2020
# ------------------------------------------------

package:
    name: path
    version: 15.0.0
source:
    sha256: 521aa0632faea3dbf7bc15549524cfc0f5d62b9a311508e562598f65c8dfda92
    url: https://pypi.io/packages/source/p/path/path-15.0.0.tar.gz
build:
    number: '0'
    script: C:\\ci\\path_1596940809557\\_h_env\\python.exe -m pip install . -vv
    string: py37_0
requirements:
    host:
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py37_0
        - openssl 1.1.1g he774522_0
        - pip 20.2.1 py37_0
        - python 3.7.7 h81c818b_4
        - setuptools 49.2.1 py37_0
        - setuptools-scm 4.1.2 py_0
        - setuptools_scm 4.1.2 0
        - sqlite 3.32.3 h2a8f88b_0
        - toml 0.10.1 py_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - wheel 0.34.2 py37_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - importlib_metadata >=0.5
        - python >=3.7,<3.8.0a0
test:
    imports:
        - path
about:
    description: 'path implements a path objects as first-class entities, allowing
        common

        operations on files to be invoked on those path objects directly.

        '
    dev_url: https://github.com/jaraco/path
    doc_source_url: https://github.com/jaraco/path/blob/master/docs/index.rst
    doc_url: https://path.readthedocs.io/en/latest/
    home: https://github.com/jaraco/path
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: A module wrapper for os.path
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jjhelmus
        - nehaljwani
