# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Oct 13 21:26:52 2020
# ------------------------------------------------

package:
    name: strsimpy
    version: 0.1.9
source:
    sha256: 23b4820fad5584ddf1b4701d2e9b82a06b5f4db009ee7f816fd5694901655259
    url: https://pypi.io/packages/source/s/strsimpy/strsimpy-0.1.9.tar.gz
build:
    noarch: python
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/strsimpy_1602624469551/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
        -m pip install . -vv
    string: pyh9f0ad1d_0
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py36h9880bd3_2
        - ld_impl_linux-64 2.35 h769bd43_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - ncurses 6.2 he1b5a44_2
        - openssl 1.1.1h h516909a_0
        - pip 20.2.3 py_0
        - python 3.6.11 h4d41432_2_cpython
        - python_abi 3.6 1_cp36m
        - readline 8.0 he28a2e2_2
        - setuptools 49.6.0 py36h9880bd3_2
        - sqlite 3.33.0 h4cf870e_1
        - tk 8.6.10 hed695b0_1
        - wheel 0.35.1 pyh9f0ad1d_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1009
    run:
        - python
test:
    imports:
        - strsimpy
about:
    description: A library implementing different string similarity and distance measures.
    dev_url: https://github.com/luozhouyang/python-string-similarity
    doc_url: https://github.com/luozhouyang/python-string-similarity
    home: https://github.com/luozhouyang/python-string-similarity
    license: MIT
    license_family: MIT
    license_file: LICENSE.txt
    summary: Python3.x implementation of tdebatty/java-string-similarity
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - aschonfeld
