# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00000tc3oh1\tmp\build\80754af9\rsync-recipes\libssh2-1.9.0-on-winbuilder, last modified Mon Mar  9 17:50:51 2020
# ------------------------------------------------

package:
    name: libssh2
    version: 1.9.0
source:
    patches:
        - 0001-libssh2-1.9.0-CVE-2019-17498.patch
    sha256: d5fb8bd563305fd1074dda90bd053fb2d29fc4bce048d182f96eaa466dfadafd
    url: https://www.libssh2.org/download/libssh2-1.9.0.tar.gz
build:
    number: '1'
    run_exports:
        - libssh2 >=1.9.0,<2.0a0
    string: h7a1dbc1_1
requirements:
    build:
        - cmake-binary 3.9.1 h8f04fe6_1
        - vs2017_win-64 19.16.27032.1 hb8d98e7_1
        - vswhere 2.7.1 h21ff451_0
    host:
        - ca-certificates 2020.1.1 0
        - openssl 1.1.1d he774522_4
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
    run:
        - openssl >=1.1.1d,<1.1.2a
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    commands:
        - if not exist %LIBRARY_INC%\\libssh2.h           exit 1
        - if not exist %LIBRARY_INC%\\libssh2_publickey.h exit 1
        - if not exist %LIBRARY_INC%\\libssh2_sftp.h      exit 1
        - if not exist %LIBRARY_LIB%\\libssh2.lib         exit 1
about:
    description: 'libssh2 is a library implementing the SSH2 protocol, available under
        the revised BSD license.

        '
    dev_url: https://github.com/libssh2/libssh2
    home: https://www.libssh2.org/
    license: BSD-3-Clause
    license_family: BSD
    license_file: COPYING
    summary: the SSH library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - shadowwalkersb
