# This file created by conda-build 3.20.2
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Mon Sep 21 18:24:15 2020
# ------------------------------------------------

package:
    name: traitlets
    version: 5.0.4
source:
    sha256: 86c9351f94f95de9db8a04ad8e892da299a088a64fd283f9f6f18770ae5eae1b
    url: https://pypi.io/packages/source/t/traitlets/traitlets-5.0.4.tar.gz
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/traitlets_1600712679583/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.2.2 py38_0
        - python 3.8.5 h7579374_1
        - readline 8.0 h7b6447c_0
        - setuptools 49.6.0 py38_0
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - ipython_genutils
        - python >=3.7
test:
    imports:
        - traitlets
        - traitlets.config
about:
    description: 'Traitlets is a framework that lets Python classes have attributes
        with

        type checking, dynamically calculated default values, and "on change"

        callbacks.

        '
    dev_url: https://github.com/ipython/traitlets
    doc_source_url: https://github.com/ipython/traitlets/blob/master/docs/source/index.rst
    doc_url: http://traitlets.readthedocs.org/en/stable/
    home: http://traitlets.readthedocs.org/
    license: BSD-3-Clause
    license_file: COPYING.md
    summary: Configuration system for Python applications
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - Carreau
        - SylvainCorlay
        - blink1073
        - jakirkham
        - minrk
        - ocefpaf
        - pelson
        - rmorshea
        - takluyver
        - zsailer
