# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\000033lpka8\tmp\build\80754af9\rsync-recipes\bokeh-2.2.1-python_3.7-on-winbuilder, last modified Mon Aug 31 12:50:15 2020
# ------------------------------------------------

package:
    name: bokeh
    version: 2.2.1
source:
    sha256: a82e9eebd7a1e2ebb7f8fc1ead802fefd10a84daef8ec4bfc986121323948555
    url: https://pypi.io/packages/source/b/bokeh/bokeh-2.2.1.tar.gz
build:
    entry_points:
        - bokeh = bokeh.__main__:main
    number: '0'
    script:
        - C:\\ci\\bokeh_1598885504939\\_h_env\\python.exe -m pip install . -vv
    string: py37_0
requirements:
    host:
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py37_0
        - openssl 1.1.1g he774522_1
        - pip 20.2.2 py37_0
        - python 3.7.7 h81c818b_4
        - setuptools 49.6.0 py37_0
        - sqlite 3.33.0 h2a8f88b_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - wheel 0.35.1 py_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - jinja2 >=2.7
        - numpy >=1.11.3
        - packaging >=16.8
        - pillow >=7.1.0
        - python >=3.7,<3.8.0a0
        - python-dateutil >=2.1
        - pyyaml >=3.10
        - tornado >=5.1
        - typing_extensions >=3.7.4
test:
    commands:
        - pip check
        - bokeh --help
    imports:
        - bokeh
        - bokeh.application
        - bokeh.application.handlers
        - bokeh.client
        - bokeh.command
        - bokeh.command.subcommands
        - bokeh.core
        - bokeh.core.property
        - bokeh.core.validation
        - bokeh.models
        - bokeh.models.widgets
        - bokeh.plotting
        - bokeh.protocol
        - bokeh.protocol.messages
        - bokeh.sampledata
        - bokeh.server
        - bokeh.server.views
        - bokeh.sphinxext
        - bokeh.themes
        - bokeh.util
    requires:
        - pip
about:
    description: 'Bokeh is a Python interactive visualization library that targets

        modern web browsers for presentation. Its goal is to provide elegant,

        concise  construction of novel graphics in the style of D3.js, and to

        extend this capability with high-performance interactivity over very

        large or streaming datasets. Bokeh can help anyone who would like to

        quickly and easily create interactive plots, dashboards, and data

        applications.

        '
    dev_url: http://github.com/bokeh/bokeh
    doc_url: http://bokeh.pydata.org/en/latest/docs/user_guide.html
    home: http://bokeh.pydata.org/
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: Statistical and novel interactive HTML plots for Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - almarklein
        - jakirkham
        - mattpap
        - ocefpaf
        - philippjfr
