# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# C:\Users\builder\conda\aggregate\gmpy2-feedstock\recipe, last modified Thu Aug  2 16:56:27 2018
# ------------------------------------------------

package:
    name: gmpy2
    version: 2.0.8
source:
    fn: gmpy2-2.0.8.zip
    patches:
        - 0001-Do-not-redefine-isnan-isinf.patch
        - 0002-PySlice_GetIndicesEx-is-a-macro.patch
    sha256: dd233e3288b90f21b0bb384bcc7a7e73557bb112ccf0032ad52aa614eb373d3f
    url: https://pypi.io/packages/source/g/gmpy2/gmpy2-2.0.8.zip
build:
    number: '3'
    script:
        - python setup.py build_ext -f --shared=%LIBRARY_PREFIX% -DMSC_USE_DLL=1 install
    string: py37h0964b28_3
requirements:
    build:
        - vs2015_win-64 14.0.25123 h17c34da_3
    host:
        - mpc 1.0.3 h0ca6028_5
        - mpfr 4.0.1 h1e10538_3
        - mpir 3.0.0 hec2e145_1
        - python 3.7.0 hea74fb7_0
        - vc 14.1 h0510ff6_3
        - vs2015_runtime 15.5.2 3
    run:
        - mpc
        - mpfr >=4.0.1,<5.0a0
        - mpir
        - python >=3.7,<3.8.0a0
        - vc 14.*
test:
    imports:
        - gmpy2
about:
    home: https://pypi.python.org/pypi/gmpy2
    license: LGPL 3
    license_file: COPYING.LESSER
    summary: GMP/MPIR, MPFR, and MPC interface to Python 2.6+ and 3.x
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - isuruf
