# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00002t0rnv8\tmp\build\80754af9\rsync-recipes\lzo-2.10-on-winbuilder, last modified Thu Apr 16 07:12:43 2020
# ------------------------------------------------

package:
    name: lzo
    version: '2.10'
source:
    sha256: c0f892943208266f9b6543b3ae308fab6284c5c90e627931446fb49b4221a072
    url: http://www.oberhumer.com/opensource/lzo/download/lzo-2.10.tar.gz
build:
    number: '2'
    run_exports:
        - lzo >=2.10,<3.0a0
    string: he774522_2
requirements:
    build:
        - jom 1.1.2 h3bd88b9_0
        - vs2017_win-64 19.16.27032.1 hb8d98e7_1
        - vswhere 2.7.1 h21ff451_0
    host:
        - ripgrep 11.0.2 0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
    run:
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    commands:
        - if not exist %PREFIX%\\Library\\include\\lzo\\lzoconf.h exit 1
        - if not exist %PREFIX%\\Library\\lib\\lzo2.lib exit 1
        - if not exist %PREFIX%\\Library\\lib\\lzo2_dllimport.lib exit 1
        - if not exist %PREFIX%\\Library\\bin\\lzo2.dll exit 1
about:
    description: 'LZO offers pretty fast compression and extremely fast decompression.

        MiniLZO is a very lightweight subset of the LZO library.

        '
    home: http://www.oberhumer.com/opensource/lzo/
    license: GPL v2+
    license_family: GPL2
    license_file: COPYING
    summary: LZO is a portable lossless data compression library written in ANSI C.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - rmax
