# This file created by conda-build 3.20.3
# ------------------------------------------------

package:
    name: py-opencv
    version: 4.4.0
source:
    -   fn: opencv-4.4.0.tar.gz
        sha256: 7faa0991c74cda52313ee37ef73f3e451332a47e7aa36c2bb2240b69f5002d27
        url: https://codeload.github.com/opencv/opencv/zip/4.4.0
    -   fn: opencv_contrib-4.4.0.tar.gz
        folder: opencv_contrib
        sha256: a69772f553b32427e09ffbfd0c8d5e5e47f7dab8b3ffc02851ffd7f912b76840
        url: https://codeload.github.com/opencv/opencv_contrib/tar.gz/4.4.0
build:
    number: 3
    run_exports:
        - py-opencv >=4.4.0,<5.0a0
    string: py37hc6149b9_3
requirements:
    host:
        - ca-certificates 2020.6.20 hecda079_0
        - intel-openmp 2020.1 216
        - libblas 3.8.0 16_mkl
        - libcblas 3.8.0 16_mkl
        - liblapack 3.8.0 16_mkl
        - mkl 2020.1 216
        - numpy 1.16.5 py37hc71023c_0
        - openssl 1.1.1h he774522_0
        - python 3.7.8 h60c2a47_1_cpython
        - python_abi 3.7 1_cp37m
        - sqlite 3.33.0 he774522_1
        - vc 14.1 h869be7e_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
    run:
        - libopencv 4.4.0 py37_3
        - numpy >=1.16.5,<2.0a0
        - python >=3.7,<3.8.0a0
        - python_abi 3.7.* *_cp37m
test:
    commands:
        - python run_py_test.py
        - python -c "import cv2, re; assert re.search('Lapack:\s+YES', cv2.getBuildInformation())"
    files:
        - color_palette_alpha.png
        - run_py_test.py
        - test_1_c1.jpg
    imports:
        - cv2
        - cv2.xfeatures2d
    requires:
        - liblapack * *mkl
about:
    home: http://opencv.org/
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Computer vision and machine learning software library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - hajapy
        - hmaarrfk
        - jakirkham
        - msarahan
        - ocefpaf
        - patricksnape
        - zym1010
