CI: azure
boost_cpp: 1.72.0
c_compiler: vs2017
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: vs2017
extend_keys:
- pin_run_as_build
- ignore_build_only_deps
- ignore_version
- extend_keys
flann: 1.9.1
fortran_compiler: gfortran
ignore_build_only_deps:
- python
- numpy
lua: '5'
numpy: '1.11'
perl: 5.26.2
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  boost-cpp:
    max_pin: x.x.x
  flann:
    max_pin: x.x.x
python: '3.6'
r_base: '3.4'
target_platform: win-64
vc: '14'
