ignore_build_only_deps:
- python
- numpy
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  libboost:
    max_pin: x.x.x
extend_keys:
- extend_keys
- pin_run_as_build
- ignore_build_only_deps
- ignore_version
hdf5:
- 1.10.6
r_version:
- 3.5.0
numpy:
- '1.16'
r_base:
- '3.5'
cran_mirror:
- https://mran.microsoft.com/snapshot/2018-01-01
icu:
- '58'
apr:
- 1.6.3
libwebp:
- 1.0.0
zlib:
- '1.2'
hdfeos5:
- '5.1'
glib:
- '2'
libkml:
- '1.3'
hdf4:
- '4.2'
cairo:
- '1.14'
boost_cpp:
- '1.73'
libnetcdf:
- '4.6'
pixman:
- '0.34'
python_implementation:
- cpython
freetype:
- '2.10'
python_impl:
- cpython
m2w64_fortran_compiler:
- m2w64-toolchain
qtwebkit:
- 'true'
hdfeos2:
- '2.20'
gmp:
- '6.1'
c_compiler:
- vs2017
channel_targets:
- defaults
xz:
- '5'
sqlite:
- '3'
target_platform:
- win-64
gstreamer:
- '1.14'
openblas:
- 0.3.3
expat:
- '2.2'
VERBOSE_AT:
- V=1
lzo:
- '2'
cpu_optimization_target:
- nocona
fortran_compiler:
- intel-fortran
openssl:
- 1.1.1
libgsasl:
- '1.8'
libgd:
- 2.2.5
proj:
- 6.2.1
blas_impl:
- mkl
libpng:
- '1.6'
bzip2:
- '1.0'
cxx_compiler:
- vs2017
libffi:
- 3.2.1
giflib:
- '5'
noarch_python:
- python
perl:
- '5.26'
r_implementation:
- r-base
- mro-base
libtiff:
- '4.1'
vc:
- '14'
nodejs:
- '8.12'
gnu:
- 2.12.2
macos_min_version:
- '10.9'
mkl:
- '2019'
geos:
- 3.8.0
rust_compiler:
- rust
- rust-gnu
readline:
- '8.0'
python:
- '3.9'
m2w64_c_compiler:
- m2w64-toolchain
tk:
- '8.6'
libxml2:
- '2.9'
VERBOSE_CM:
- VERBOSE=1
serf:
- 1.3.9
dbus:
- '1'
fontconfig:
- '2.13'
lua:
- '5'
gst_plugins_base:
- '1.14'
mpfr:
- '4'
libgdal:
- '3.0'
jpeg:
- '9'
libdap4:
- '3.19'
cyrus_sasl:
- 2.1.26
cross_compiler_target_platform:
- win-32
- win-64
libxslt:
- '1.1'
harfbuzz:
- '2.4'
libprotobuf:
- 3.11.2
m2w64_cxx_compiler:
- m2w64-toolchain
boost:
- '1.73'
llvm_variant:
- llvm
fortran_compiler_version:
- 2019.0.0
proj4:
- 5.2.0
macos_machine:
- x86_64-apple-darwin13.4.0
openjpeg:
- '2.3'
rust_compiler_version:
- 1.46.0
clang_variant:
- clang
g2clib:
- '1.6'
zip_keys: []
