# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# C:\ci\containers\0000160btsn\tmp\build\80754af9\rsync-recipes\blosc-1.20.1-on-winbuilder, last modified Wed Oct 14 13:26:18 2020
# ------------------------------------------------

package:
    name: blosc
    version: 1.20.1
source:
    sha256: 42c4d3fcce52af9f8e2078f8f57681bfc711706a3330cb72b9b39e05ae18a413
    url: https://github.com/Blosc/c-blosc/archive/v1.20.1.tar.gz
build:
    ignore_run_exports:
        - lz4-c
        - snappy
    number: '0'
    run_exports:
        - blosc >=1.20.1,<2.0a0
    string: h7bd577a_0
requirements:
    build:
        - bzip2 1.0.8 he774522_0
        - cmake 3.18.2 hab937c2_0
        - libuv 1.40.0 he774522_0
        - lz4-c 1.9.2 hf4a77e7_3
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - vs2017_win-64 19.16.27032.1 hb4161e2_3
        - vswhere 2.7.1 h21ff451_0
        - xz 5.2.5 h62dcd97_0
        - zlib 1.2.11 h62dcd97_4
        - zstd 1.4.5 h04227a9_0
    host:
        - lz4-c 1.9.2 hf4a77e7_3
        - snappy 1.1.8 h33f27b4_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - xz 5.2.5 h62dcd97_0
        - zlib 1.2.11 h62dcd97_4
        - zstd 1.4.5 h04227a9_0
    run:
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
        - zlib >=1.2.11,<1.3.0a0
        - zstd >=1.4.5,<1.4.6.0a0
test:
    commands:
        - if not exist %LIBRARY_INC%\\blosc.h exit 1
        - if not exist %LIBRARY_INC%\\blosc-export.h exit 1
        - if not exist %LIBRARY_BIN%\\blosc.dll exit 1
        - if not exist %LIBRARY_LIB%\\blosc.lib exit 1
        - if not exist %LIBRARY_LIB%\\libblosc.lib exit 1
about:
    home: https://github.com/Blosc/c-blosc
    license: BSD-3-Clause
    license_file: LICENSES/BLOSC.txt
    summary: A blocking, shuffling and loss-less compression library that can be faster
        than `memcpy()`
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - FrancescElies
        - beckermr
        - danielfrg
        - jakirkham
        - msarahan
