# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# C:\ci\containers\00000iroieg\tmp\build\80754af9\combined_recipe, last modified Fri Oct  9 16:23:19 2020
# ------------------------------------------------

package:
    name: pycurl
    version: 7.43.0.6
source:
    patches:
        - msvc_warnings.patch
    sha256: 8301518689daefa53726b59ded6b48f33751c383cf987b0ccfbbc4ed40281325
    url: https://pypi.io/packages/source/p/pycurl/pycurl-7.43.0.6.tar.gz
build:
    detect_binary_files_with_prefix: false
    number: '0'
    string: py37h7a1dbc1_0
requirements:
    build:
        - ca-certificates 2020.7.22 0
        - openssl 1.1.1h he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - vs2017_win-64 19.16.27032.1 hb4161e2_3
        - vswhere 2.7.1 h21ff451_0
    host:
        - ca-certificates 2020.7.22 0
        - krb5 1.18.2 hc04afaa_0
        - libcurl 7.71.1 h2a8f88b_1
        - libssh2 1.9.0 h7a1dbc1_1
        - openssl 1.1.1h he774522_0
        - python 3.7.9 h60c2a47_0
        - sqlite 3.33.0 h2a8f88b_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - zlib 1.2.11 h62dcd97_4
    run:
        - libcurl >=7.71.1,<8.0a0
        - python >=3.7,<3.8.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    imports:
        - curl
        - pycurl
about:
    description: 'PycURL is a Python interface to libcurl, the multiprotocol file
        transfer library.

        Similarly to the urllib Python module, PycURL can be used to fetch objects
        identified

        by a URL from a Python program.

        '
    dev_url: https://github.com/pycurl/pycurl
    doc_source_url: https://github.com/pycurl/pycurl/blob/master/doc/index.rst
    doc_url: http://pycurl.io/docs/latest/index.html
    home: http://pycurl.sourceforge.net/
    license: LGPL, MIT
    license_family: LGPL
    license_file: COPYING-LGPL
    summary: A Python Interface To The cURL library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - chrisburr
