# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00001hd07mv\tmp\build\80754af9\rsync-recipes\mpc-1.1.0-on-winbuilder, last modified Thu Jun 25 16:06:45 2020
# ------------------------------------------------

package:
    name: mpc
    version: 1.1.0
source:
    fn: mpc-1.1.0.tar.gz
    patches:
        - patches/build-vc14.patch
    sha256: 6985c538143c1208dcb1ac42cedad6ff52e267b47e5f970183a3e75125b43c2e
    url: https://ftp.gnu.org/gnu/mpc/mpc-1.1.0.tar.gz
build:
    number: '1'
    run_exports:
        - mpc >=1.1.0,<2.0a0
    string: h7edee0f_1
requirements:
    build:
        - vs2017_win-64 19.16.27032.1 hb4161e2_2
        - vswhere 2.7.1 h21ff451_0
    host:
        - mpfr 4.0.2 h62dcd97_1
        - mpir 3.0.0 hec2e145_1
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_2
    run:
        - mpfr >=4.0.2,<5.0a0
        - mpir
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    commands:
        - if not exist %LIBRARY_INC%\\mpc.h exit 1
        - if not exist %LIBRARY_LIB%\\mpc.lib exit 1
        - if not exist %LIBRARY_BIN%\\mpc.dll exit 1
        - if not exist %LIBRARY_LIB%\\mpc_static.lib exit 1
about:
    home: http://www.multiprecision.org/
    license: LGPL-3-or-later
    license_file: C:\ci\mpc_1593196419954\work/COPYING.LESSER
    summary: A C library for the arithmetic of complex numbers with arbitrarily high
        precision.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - isuruf
        - jakirkham
        - saraedum
