# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00002uigor6\tmp\build\80754af9\rsync-recipes\zstd-1.4.5-on-winbuilder, last modified Tue Jul 28 14:22:16 2020
# ------------------------------------------------

package:
    name: zstd
    version: 1.4.5
source:
    fn: zstd-1.4.5.tar.gz
    sha256: 98e91c7c6bf162bf90e4e70fdbc41a8188b9fa8de5ad840c401198014406ce9e
    url: https://github.com/facebook/zstd/releases/download/v1.4.5/zstd-1.4.5.tar.gz
build:
    number: '0'
    run_exports:
        - zstd >=1.4.5,<1.4.6.0a0
    string: h04227a9_0
requirements:
    build:
        - ca-certificates 2020.6.24 0
        - cmake 3.17.2 h33f27b4_0
        - ninja 1.9.0 py38h74a9793_0
        - openssl 1.1.1g he774522_0
        - python 3.8.3 he1778fa_2
        - sqlite 3.32.3 h2a8f88b_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - vs2017_win-64 19.16.27032.1 hb4161e2_3
        - vswhere 2.7.1 h21ff451_0
        - zlib 1.2.11 h62dcd97_4
    host:
        - lz4-c 1.9.2 h62dcd97_1
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - xz 5.2.5 h62dcd97_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - lz4-c >=1.9.2,<1.10.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
        - xz >=5.2.5,<6.0a0
        - zlib >=1.2.11,<1.3.0a0
about:
    description: 'Zstandard is a real-time compression algorithm, providing high compression

        ratios. It offers a very wide range of compression / speed trade-off, while

        being backed by a very fast decoder. It also offers a special mode for

        small data, called dictionary compression, and can create dictionaries from

        any sample set. Zstandard library is provided as open source software using

        a BSD license.

        '
    dev_url: https://github.com/facebook/zstd
    doc_url: https://facebook.github.io/zstd/zstd_manual.html
    home: http://www.zstd.net
    license: BSD 3-Clause
    license_file: LICENSE
    summary: Zstandard - Fast real-time compression algorithm
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - msarahan
        - rmax
        - xhochy
