# This file created by conda-build 3.20.0
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/cloudpickle-1.6.0-on-linux_64, last modified Mon Aug 31 14:27:45 2020
# ------------------------------------------------

package:
    name: cloudpickle
    version: 1.6.0
source:
    fn: cloudpickle-1.6.0.tar.gz
    sha256: 9bc994f9e9447593bd0a45371f0e7ac7333710fcf64a4eb9834bf149f4ef2f32
    url: https://pypi.io/packages/source/c/cloudpickle/cloudpickle-1.6.0.tar.gz
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/cloudpickle_1598884132938/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
        -m pip install . --no-deps -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.2.2 py38_0
        - python 3.8.5 hcff3b4d_0
        - readline 8.0 h7b6447c_0
        - setuptools 49.6.0 py38_0
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=3.5
test:
    imports:
        - cloudpickle
about:
    description: 'cloudpickle is extended pickling support for Python objects.

        cloudpickle makes it possible to serialize Python constructs not

        supported by the default pickle module from the Python standard library.

        '
    dev_url: https://github.com/cloudpipe/cloudpickle
    doc_source_url: https://github.com/cloudpipe/cloudpickle/blob/master/README.md
    doc_url: https://pypi.python.org/pypi/cloudpickle/1.6.0
    home: https://github.com/cloudpipe/cloudpickle
    license: BSD-3-Clause
    license_file: LICENSE
    summary: Extended pickling support for Python objects
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mrocklin
        - nehaljwani
        - ogrisel
        - rgbkrk
