# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/iniconfig-1.0.1-on-linux_canary, last modified Fri Aug  7 19:05:19 2020
# ------------------------------------------------

package:
    name: iniconfig
    version: 1.0.1
source:
    sha256: e5f92f89355a67de0595932a6c6c02ab4afddc6fcdc0bfc5becd0d60884d3f69
    url: https://pypi.io/packages/source/i/iniconfig/iniconfig-1.0.1.tar.gz
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/iniconfig_1596827328212/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
        -m pip install . -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py36_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.1.1 py36_1
        - python 3.6.10 h7579374_2
        - readline 8.0 h7b6447c_0
        - setuptools 49.2.0 py36_0
        - setuptools-scm 4.1.2 py_0
        - setuptools_scm 4.1.2 0
        - sqlite 3.32.3 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.34.2 py36_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python
test:
    commands:
        - pip check
    imports:
        - iniconfig
    requires:
        - pip
about:
    home: http://github.com/RonnyPfannschmidt/iniconfig
    license: MIT
    license_file: LICENSE
    summary: 'iniconfig: brain-dead simple config-ini parsing'
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nicoddemus
