# This file created by conda-build 3.19.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Mar 24 01:53:09 2020
# ------------------------------------------------

package:
    name: squarify
    version: 0.4.3
source:
    sha256: 54091f6ad175f7f201f8934574e647ce1b50dedc478c5fd968688eb7d7469f95
    url: https://pypi.io/packages/source/s/squarify/squarify-0.4.3.tar.gz
build:
    noarch: python
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/squarify_1585014835478/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
        -m pip install . -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - ca-certificates 2019.11.28 hecc5488_0
        - certifi 2019.11.28 py38h32f6830_1
        - ld_impl_linux-64 2.34 h53a641e_0
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1e h516909a_0
        - pip 20.0.2 py_2
        - python 3.8.2 h8356626_5_cpython
        - python_abi 3.8 1_cp38
        - readline 8.0 hf8c457e_0
        - setuptools 46.1.1 py38h32f6830_0
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.10 hed695b0_0
        - wheel 0.34.2 py_1
        - xz 5.2.4 h516909a_1002
        - zlib 1.2.11 h516909a_1006
    run:
        - matplotlib-base
        - python >=2.6,<=2.7|>=3.5
test:
    imports:
        - squarify
about:
    description: Pure Python implementation of the squarify treemap layout algorithm.
    dev_url: https://github.com/laserson/squarify
    doc_url: https://github.com/laserson/squarify
    home: https://github.com/laserson/squarify
    license: Apache-2.0
    license_family: APACHE
    license_file: LICENSE.txt
    summary: Pure Python implementation of the squarify treemap layout algorithm.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - aaronmussig
