# This file created by conda-build 3.16.2
# meta.yaml template originally from:
# C:\ci\containers\00000fiuknm\tmp\build\80754af9\rsync-recipes\async_generator-1.10-python_3.7-on-winbuilder, last modified Mon Oct 29 20:03:44 2018
# ------------------------------------------------

package:
    name: async_generator
    version: '1.10'
source:
    sha256: 6ebb3d106c12920aaae42ccb6f787ef5eefdcdd166ea3d628fa8476abe712144
    url: https://pypi.io/packages/source/a/async_generator/async_generator-1.10.tar.gz
build:
    noarch: false
    number: '0'
    script: C:\\ci\\async_generator_1540861706923\\_h_env\\python.exe -m pip install
        --no-deps --ignore-installed .
    string: py37h28b3542_0
requirements:
    host:
        - certifi 2018.10.15 py37_0
        - pip 10.0.1 py37_0
        - python 3.7.1 h33f27b4_4
        - setuptools 40.4.3 py37_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - wheel 0.32.2 py37_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - async_generator
        - async_generator._tests
about:
    description: Python 3.6 added async generators, Python 3.7 adds some more tools
        to make them usable, like contextlib.asynccontextmanager. This library gives
        you all that back to Python 3.5.
    dev_url: https://github.com/python-trio/async_generator
    home: https://github.com/python-trio/async_generator
    license: MIT
    license_family: MIT
    summary: Async generators and context managers for Python 3.5+
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nicoddemus
