# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00000sild7t\tmp\build\80754af9\pull-recipes-pywin32-ctypes\recipe, last modified Fri Jul 10 09:35:20 2020
# ------------------------------------------------

package:
    name: pywin32-ctypes
    version: 0.2.0
source:
    sha256: 24ffc3b341d457d48e8922352130cf2644024a4ff09762a2261fd34c36ee5942
    url: https://pypi.io/packages/source/p/pywin32-ctypes/pywin32-ctypes-0.2.0.tar.gz
build:
    number: '1001'
    script: C:\ci\pywin32-ctypes_1594392691209\_h_env\python.exe -m pip install .
        --no-deps --ignore-installed --no-cache-dir -vvv
    string: py37_1001
requirements:
    host:
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py37_0
        - openssl 1.1.1g he774522_0
        - pip 20.1.1 py37_1
        - python 3.7.7 h81c818b_4
        - setuptools 47.3.1 py37_0
        - sqlite 3.32.3 h2a8f88b_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - wheel 0.34.2 py37_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - win32ctypes
about:
    description: 'A reimplementation of pywin32 that is pure python. The default behaviour

        will try to use cffi (>= 1.3.0), if available, and fall back to using ctypes.

        '
    dev_url: https://github.com/enthought/pywin32-ctypes
    doc_url: http://pywin32-ctypes.readthedocs.io/en/stable/
    home: https://github.com/enthought/pywin32-ctypes
    license: BSD 3 Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: A limited subset of pywin32 re-implemented using ctypes (or cffi)
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
