# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# C:\projects\pthreads-win32-feedstock\recipe, last modified Mon Sep 24 02:15:05 2018
# ------------------------------------------------

package:
    name: pthreads-win32
    version: 2.9.1
source:
    fn: pthreads-w32-2-9-1-release.zip
    md5: a3cb284ba0914c9d26e0954f60341354
    patches:
        - macro_redefined.patch
        - timespec.patch
    url: ftp://sourceware.org/pub/pthreads-win32/pthreads-w32-2-9-1-release.zip
build:
    number: '3'
    string: hfa6e2cd_3
requirements:
    build:
        - vs2015_win-64 14.0.25123 h17c34da_3
    host:
        - vc 14 0
        - vs2015_runtime 14.0.25420 0
    run:
        - vc 14.*
test:
    commands:
        - if not exist %LIBRARY_INC%\pthread.h exit 1
        - if not exist %LIBRARY_BIN%\pthreadVSE2.dll exit 1
        - if not exist %LIBRARY_LIB%\pthreads.lib exit 1
        - if not exist %LIBRARY_LIB%\pthread.lib exit 1
        - if not exist %LIBRARY_LIB%\pthreads_static.lib exit 1
about:
    home: https://www.sourceware.org/pthreads-win32/
    license: LGPL 2
    license_file: pthreads.2/COPYING.LIB
    summary: Open Source POSIX Threads for Win32
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - isuruf
