# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# C:\ci\containers\00001l0eif9\tmp\build\80754af9\combined_recipe, last modified Tue Jan 19 12:41:55 2021
# ------------------------------------------------

package:
  name: ca-certificates
  version: 2021.1.19
source:
  fn: cacert.pem
  sha256: 2782f0f8e89c786f40240fc1916677be660fb8d8e25dede50c9f6f7b0c2c2178
  url: https://curl.haxx.se/ca/cacert-2020-07-22.pem
build:
  commands:
    - /usr/bin/curl --cacert %LIBRARY_PREFIX%\\ssl\\cacert.pem https://www.google.com
    - if not exist %LIBRARY_PREFIX%\\ssl\\cacert.pem exit 1
    - if not exist %LIBRARY_PREFIX%\\ssl\\cert.pem exit 1
  number: '0'
  string: haa95532_0
requirements:
  build: []
  run: []
about:
  home: https://github.com/conda-forge/ca-certificates-feedstock
  license: MPL 2.0
  license_file: LICENSE.txt
  summary: Certificates for use with other packages.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - mwcraig
    - ocefpaf
    - patricksnape
    - pelson
    - scopatz
