# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00000sild7c\tmp\build\80754af9\pull-recipes-nbconvert\recipe, last modified Fri Jul 10 03:26:27 2020
# ------------------------------------------------

package:
    name: nbconvert
    version: 5.6.1
source:
    sha256: 21fb48e700b43e82ba0e3142421a659d7739b65568cc832a13976a77be16b523
    url: https://pypi.io/packages/source/n/nbconvert/nbconvert-5.6.1.tar.gz
build:
    entry_points:
        - jupyter-nbconvert = nbconvert.nbconvertapp:main
    number: '1'
    script: C:\ci\nbconvert_1594372737468\_h_env\python.exe -m pip install . --no-deps
        --ignore-installed --no-cache-dir -vvv
    string: py37_1
requirements:
    host:
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py37_0
        - openssl 1.1.1g he774522_0
        - pip 20.1.1 py37_1
        - python 3.7.7 h81c818b_4
        - setuptools 47.3.1 py37_0
        - sqlite 3.32.3 h2a8f88b_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - wheel 0.34.2 py37_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - bleach
        - defusedxml
        - entrypoints >=0.2.2
        - jinja2
        - jupyter_core
        - mistune >=0.8.1
        - nbformat >=4.4
        - pandoc >=1.12.1
        - pandocfilters >=1.4.1
        - pygments
        - python >=3.7,<3.8.0a0
        - testpath
        - traitlets >=4.2
test:
    commands:
        - jupyter nbconvert --help
        - jupyter nbconvert nbconvert/tests/files/notebook1.ipynb
    imports:
        - nbconvert
        - nbconvert.exporters
        - nbconvert.filters
        - nbconvert.postprocessors
        - nbconvert.preprocessors
        - nbconvert.resources
        - nbconvert.tests
        - nbconvert.utils
        - nbconvert.writers
    source_files:
        - nbconvert/tests/files/notebook1.ipynb
about:
    description: 'The nbconvert tool, jupyter nbconvert, converts notebooks to various
        other

        formats via Jinja templates. The nbconvert tool allows you to convert an

        .ipynb notebook file into various static formats.

        '
    dev_url: https://github.com/jupyter/nbconvert
    doc_url: http://nbconvert.readthedocs.org/
    home: http://jupyter.org
    license: BSD-3-Clause
    license_file: LICENSE
    summary: Converting Jupyter Notebooks
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - blink1073
        - jakirkham
        - minrk
        - mpacer
        - mseal
        - ocefpaf
        - pelson
        - takluyver
