# This file created by conda-build 3.20.4
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Thu Oct 22 05:34:44 2020
# ------------------------------------------------

package:
    name: netgen
    version: 6.2.2006
source:
    git_rev: v6.2.2006
    git_url: https://github.com/NGSolve/netgen
    patches:
        - cmake.patch
build:
    number: '2'
    string: py37h7435507_2
requirements:
    build:
        - cmake 3.18.2 h001a745_0
        - ninja 1.10.1 h587dcfd_2
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - vs2017_win-64 19.16.27038 h2e3bad8_2
        - vswhere 2.7.1 h21ff451_0
    host:
        - bzip2 1.0.8 he774522_3
        - ca-certificates 2020.6.20 hecda079_0
        - colorama 0.4.4 pyh9f0ad1d_0
        - curl 7.71.1 h4b64cdc_8
        - double-conversion 3.1.5 h6538335_2
        - eigen 3.3.7 he980bc4_1001
        - expat 2.2.9 h33f27b4_2
        - ffmpeg 4.3.1 ha925a31_0
        - fontconfig 2.13.1 hdcb13c4_1002
        - freeimage 3.18.0 h33f27b4_0
        - freetype 2.10.4 hd328e21_0
        - gl2ps 1.4.2 h2c487a6_0
        - glew 2.1.0 he025d50_0
        - hdf4 4.2.13 hf8e6fe8_1003
        - hdf5 1.10.6 nompi_h89124ea_1110
        - icu 67.1 h33f27b4_0
        - jpeg 9d he774522_0
        - jsoncpp 1.8.4 h1ad3211_1002
        - krb5 1.17.1 hc04afaa_3
        - libcurl 7.71.1 h4b64cdc_8
        - libiconv 1.16 he774522_0
        - libnetcdf 4.7.4 nompi_h2ee746f_106
        - libogg 1.3.2 hfa6e2cd_1002
        - libpng 1.6.37 ha81a0f5_2
        - libssh2 1.9.0 hb06d900_5
        - libtheora 1.1.1 h62dcd97_1004
        - libtiff 4.1.0 h885aae3_6
        - libxml2 2.9.10 h1006b36_2
        - loguru 0.5.3 py37hc8dfbb8_2
        - lz4-c 1.9.2 h62dcd97_2
        - occt 7.4.0 hd267c4f_8
        - openssl 1.1.1h he774522_0
        - proj 7.1.1 h7d85306_3
        - pugixml 1.10 ha925a31_1
        - pybind11 2.6.0 py37h1fb7aa8_0
        - python 3.7.8 h60c2a47_1_cpython
        - python_abi 3.7 1_cp37m
        - sqlite 3.33.0 he774522_1
        - tbb 2019.9 he980bc4_1
        - tbb-devel 2019.9 he980bc4_1
        - tk 8.6.10 he774522_1
        - utfcpp 3.1.2 0
        - vc 14.1 h869be7e_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - vtk 9.0.1 no_osmesa_py37h047e439_101
        - win32_setctime 1.0.3 py_0
        - xz 5.2.5 h62dcd97_1
        - zlib 1.2.11 h62dcd97_1010
        - zstd 1.4.5 h1f3a1b7_2
    run:
        - occt >=7.4.0,<7.5.0a0
        - python >=3.7,<3.8.0a0
        - python_abi 3.7.* *_cp37m
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - python -c "import sys; print(sys.version); import netgen;"
about:
    description: NETGEN is an automatic 3d tetrahedral mesh generator. It accepts
        input from constructive solid geometry (CSG) or boundary representation (BRep)
        from STL file format. The connection to a geometry kernel allows the handling
        of IGES and STEP files. NETGEN contains modules for mesh optimization and
        hierarchical mesh refinement. Netgen is open source based on the LGPL license.
        It is available for Unix/Linux and Windows.
    dev_url: https://sourceforge.net/projects/netgen-mesher/
    doc_url: http://www.hpfem.jku.at/netgen/
    home: https://sourceforge.net/projects/netgen-mesher/
    license: LGPL2.1
    license_family: LGPL
    license_file: LICENSE
    summary: this is netgen
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - looooo
