# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/decorator-4.4.2-on-linux_64, last modified Thu Mar 12 15:28:14 2020
# ------------------------------------------------

package:
    name: decorator
    version: 4.4.2
source:
    sha256: e3a62f0520172440ca0dcc823749319382e377f37f140a0b99ef45fecb84bfe7
    url: https://pypi.io/packages/source/d/decorator/decorator-4.4.2.tar.gz
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/decorator_1584026986878/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
        -m pip install . --no-deps -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.1.1 0
        - certifi 2019.11.28 py36_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_0
        - openssl 1.1.1d h7b6447c_4
        - pip 20.0.2 py36_1
        - python 3.6.10 h0371630_0
        - readline 7.0 h7b6447c_5
        - setuptools 46.0.0 py36_0
        - sqlite 3.31.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - wheel 0.34.2 py36_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - python
test:
    commands:
        - pip check
    imports:
        - decorator
    requires:
        - pip
about:
    description: 'Preserve the signature of decorated functions in a consistent way

        across Python releases.

        '
    dev_url: https://github.com/micheles/decorator
    doc_source_url: https://github.com/micheles/decorator/tree/master/docs
    doc_url: http://decorator.readthedocs.io/en/stable/
    home: https://github.com/micheles/decorator
    license: BSD-3-Clause
    license_file: LICENSE.txt
    summary: Better living through Python with decorators.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - msarahan
        - ocefpaf
        - pelson
        - scopatz
