# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Thu May  7 13:00:38 2020
# ------------------------------------------------

package:
    name: icu
    version: '67.1'
source:
    -   patches:
            - icu-config.patch
            - icu4c-4_9_1-mingw-w64-mkdir-compatibility.patch
        sha256: 94a80cd6f251a53bd2a997f6f1b5ac6653fe791dfab66e1eb0227740fb86d5dc
        url: https://github.com/unicode-org/icu/releases/download/release-67-1/icu4c-67_1-src.tgz
    -   folder: source/data
        sha256: 7c16a59cc8c06128b7ecc1dc4fc056b36b17349312829b17408b9e67b05c4a7e
        url: https://github.com/unicode-org/icu/releases/download/release-67-1/icu4c-67_1-data.zip
build:
    number: '0'
    run_exports:
        - icu >=67.1,<68.0a0
    string: h33f27b4_0
requirements:
    build:
        - m2-base 1.0.0 3
        - m2-bash 4.3.042 5
        - m2-bash-completion 2.3 2
        - m2-catgets 1.1 3
        - m2-coreutils 8.25 102
        - m2-dash 0.5.8 2
        - m2-file 5.25 2
        - m2-filesystem 2016.04 4
        - m2-findutils 4.6.0 2
        - m2-gawk 4.1.3 2
        - m2-gcc-libs 5.3.0 4
        - m2-gettext 0.19.7 4
        - m2-gmp 6.1.0 3
        - m2-grep 2.22 4
        - m2-gzip 1.7 2
        - m2-inetutils 1.9.2 2
        - m2-info 6.0 2
        - m2-less 481 2
        - m2-libasprintf 0.19.7 4
        - m2-libcatgets 1.1 3
        - m2-libcrypt 1.3 2
        - m2-libgettextpo 0.19.7 4
        - m2-libiconv 1.14 3
        - m2-libintl 0.19.7 4
        - m2-liblzma 5.2.2 2
        - m2-libpcre 8.38 2
        - m2-libreadline 6.3.008 8
        - m2-libutil-linux 2.26.2 2
        - m2-libxml2 2.9.2 3
        - m2-make 4.1 5
        - m2-mintty 1!2.2.3 2
        - m2-mpfr 3.1.4 2
        - m2-msys2-launcher-git 0.3.28.860c495 2
        - m2-msys2-runtime 2.5.0.17080.65c939c 3
        - m2-ncurses 6.0.20160220 2
        - m2-sed 4.2.2 3
        - m2-tftp-hpa 5.2 2
        - m2-time 1.7 2
        - m2-ttyrec 1.0.8 2
        - m2-tzcode 2015.e 2
        - m2-util-linux 2.26.2 2
        - m2-which 2.21 3
        - m2-zlib 1.2.8 4
        - msys2-conda-epoch 20160418 1
        - vs2017_win-64 19.16.27038 h2e3bad8_2
        - vswhere 2.7.1 h21ff451_0
    host:
        - vc 14.1 h869be7e_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
    run:
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012
test:
    commands:
        - genbrk --help
        - gencfu --help
        - gencnval --help
        - gendict --help
        - icuinfo --help
        - makeconv gb-18030-2000.ucm
    files:
        - de.txt
        - gb-18030-2000.ucm
about:
    home: http://site.icu-project.org/
    license: MIT
    license_file: LICENSE
    summary: International Components for Unicode.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - jakirkham
        - msarahan
        - ocefpaf
