# This file created by conda-build 3.20.2
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Mon Sep 28 07:32:52 2020
# ------------------------------------------------

package:
    name: utfcpp
    version: 3.1.2
source:
    fn: v3.1.2.tar.gz
    sha256: fea3bfa39fb8bd7368077ea5e1e0db9a8951f7e6fb6d9400b00ab3d92b807c6d
    url: https://github.com/nemtrif/utfcpp/archive/v3.1.2.tar.gz
build:
    number: '0'
    string: '0'
test:
    commands:
        - if not exist %LIBRARY_INC%\\utf8.h exit 1
        - if not exist %LIBRARY_INC%\\utf8 exit 1
about:
    description: 'UTF-8 with C++ in a Portable Way


        An easily to handle generic library for UTF-8 encoded Unicode strings. For

        anybody used to work with STL algorithms and iterators, it should be easy

        and natural to use.

        '
    dev_url: https://github.com/nemtrif/utfcpp
    doc_url: https://github.com/nemtrif/utfcpp/blob/master/README.md
    home: https://github.com/nemtrif/utfcpp
    license: BSL-1.0
    summary: A simple, portable and lightweight generic library for handling UTF-8
        encoded strings.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - stuertz
