# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/pytz-2020.1-on-linux_canary, last modified Mon May  4 17:15:44 2020
# ------------------------------------------------

package:
    name: pytz
    version: '2020.1'
source:
    sha256: c35965d010ce31b23eeb663ed3cc8c906275d6be1a34393a1d73a41febf4a048
    url: https://pypi.io/packages/source/p/pytz/pytz-2020.1.tar.gz
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/pytz_1588612680038/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
        -m pip install . --no-deps -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.1 py36_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.0.2 py36_1
        - python 3.6.10 hcf32534_1
        - readline 8.0 h7b6447c_0
        - setuptools 46.1.3 py36_0
        - sqlite 3.31.1 h62c20be_1
        - tk 8.6.8 hbc83047_0
        - wheel 0.34.2 py36_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python
test:
    imports:
        - pytz
about:
    description: 'pytz brings the Olson tz database into Python. This library allows

        accurate and cross platform timezone calculations using Python 2.4 or

        higher. It also solves the issue of ambiguous times at the end of daylight

        saving time.

        '
    dev_url: https://github.com/newvem/pytz
    doc_source_url: https://github.com/newvem/pytz/blob/master/README.txt
    doc_url: http://pythonhosted.org/pytz/
    home: http://pythonhosted.org/pytz/
    license: MIT
    license_file: LICENSE.txt
    summary: World timezone definitions, modern and historical.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - msarahan
        - ocefpaf
