# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/pull-recipes-urllib3/recipe, last modified Mon Aug 10 19:09:10 2020
# ------------------------------------------------

package:
    name: urllib3
    version: 1.25.10
source:
    sha256: 91056c15fa70756691db97756772bb1eb9678fa585d9184f24534b100dc60f4a
    url: https://pypi.io/packages/source/u/urllib3/urllib3-1.25.10.tar.gz
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/urllib3_1597086586889/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
        -m pip install . -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.2.1 py38_0
        - python 3.8.5 hcff3b4d_0
        - readline 8.0 h7b6447c_0
        - setuptools 49.2.1 py38_0
        - sqlite 3.32.3 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - brotlipy >=0.6.0
        - certifi
        - cryptography >=1.3.4
        - idna >=2.0.0
        - pyopenssl >=0.14
        - pysocks >=1.5.6,<2.0,!=1.5.7
        - python <4.0
test:
    commands:
        - pip check
    imports:
        - urllib3
        - urllib3.contrib
        - urllib3.packages
        - urllib3.packages.backports
        - urllib3.packages.ssl_match_hostname
        - urllib3.util
    requires:
        - pip
about:
    description: 'urllib3 is a powerful, sanity-friendly HTTP client for Python. Much
        of the

        Python ecosystem already uses urllib3. urllib3 brings many critical features

        that are missing from the Python standard libraries, such as thread safety,

        connection pooling, client side ssl/tls verification, support for gzip and

        deflate encodings, HTTP and SOCKS proxy support, helpers for retrying requests

        and dealing with HTTP redirects.

        '
    dev_url: https://github.com/shazow/urllib3
    doc_source_url: https://github.com/shazow/urllib3/tree/master/docs
    doc_url: https://urllib3.readthedocs.io/
    home: https://urllib3.readthedocs.io/
    license: MIT
    license_family: MIT
    license_file: LICENSE.txt
    summary: HTTP library with thread-safe connection pooling, file post, and more.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
        - pmlandwehr
        - sethmlarson
        - sigmavirus24
