# This file created by conda-build 3.20.1
# meta.yaml template originally from:
# C:\ci\containers\0000029qg9n\tmp\build\80754af9\rsync-recipes\llvmlite-0.34.0-python_3.7-on-winbuilder, last modified Sat Sep  5 17:28:50 2020
# ------------------------------------------------

package:
    name: llvmlite
    version: 0.34.0
source:
    sha256: f03ee0d19bca8f2fe922bb424a909d05c28411983b0c2bc58b020032a0d11f63
    url: https://pypi.io/packages/source/l/llvmlite/llvmlite-0.34.0.tar.gz
build:
    number: '4'
    script_env:
        - PY_VCRUNTIME_REDIST
    string: py37h1a82afc_4
requirements:
    build:
        - cmake 3.17.2 h33f27b4_0
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - vs2017_win-64 19.16.27032.1 hb4161e2_3
        - vswhere 2.7.1 h21ff451_0
    host:
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py37_0
        - libllvm10 10.0.1 h5dfd299_5
        - llvm 10.0.1 h21ff451_5
        - llvm-tools 10.0.1 h5dfd299_5
        - llvmdev 10.0.1 h5dfd299_5
        - openssl 1.1.1g he774522_1
        - pip 20.2.2 py37_0
        - python 3.7.9 h60c2a47_0
        - setuptools 49.6.0 py37_0
        - sqlite 3.33.0 h2a8f88b_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - wheel 0.35.1 py_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - python >=3.7,<3.8.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - python -m llvmlite.tests
    imports:
        - llvmlite
        - llvmlite.binding
about:
    dev_url: https://github.com/numba/llvmlite
    doc_url: http://llvmlite.pydata.org/
    home: http://llvmlite.pydata.org
    license: BSD-2-Clause
    license_file: LICENSE
    summary: A lightweight LLVM python binding for writing JIT compilers.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - marcelotrevisani
        - mbargull
        - souravsingh
        - xhochy
