# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00002i687hb\tmp\build\80754af9\rsync-recipes\pynacl-1.4.0-python_3.7-on-winbuilder, last modified Fri Jul 17 19:03:04 2020
# ------------------------------------------------

package:
    name: pynacl
    version: 1.4.0
source:
    fn: PyNaCl-1.4.0.tar.gz
    patches:
        - 0001-Fix-name-of-static-sodium-lib.patch
    sha256: 54e9a2c849c742006516ad56a88f5c74bf2ce92c9f67435187c3c5953b346505
    url: https://pypi.io/packages/source/P/PyNaCl/PyNaCl-1.4.0.tar.gz
build:
    ignore_run_exports:
        - libsodium
    number: '1'
    string: py37h62dcd97_1
requirements:
    build:
        - m2-msys2-runtime 2.5.0.17080.65c939c 3
        - m2-patch 2.7.5 2
        - msys2-conda-epoch 20160418 1
        - vs2017_win-64 19.16.27032.1 hb4161e2_3
        - vswhere 2.7.1 h21ff451_0
    host:
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py37_0
        - cffi 1.14.0 py37h7a1dbc1_0
        - libsodium 1.0.18 h62dcd97_0
        - openssl 1.1.1g he774522_0
        - pip 20.1.1 py37_1
        - pycparser 2.20 py_2
        - python 3.7.7 h81c818b_4
        - setuptools 49.2.0 py37_0
        - sqlite 3.32.3 h2a8f88b_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - wheel 0.34.2 py37_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - cffi >=1.4.1
        - python >=3.7,<3.8.0a0
        - six
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    commands:
        - pytest
    imports:
        - nacl
        - nacl.bindings
        - nacl.pwhash
    requires:
        - hypothesis >=3.27.0
        - pytest >=3.2.1
    source_files:
        - tests/
about:
    description: 'PyNaCl is a Python binding to the Networking and Cryptography library,
        a crypto library with the stated goal of improving usability, security and
        speed. It supports Python 2.7 and 3.3+ as well as PyPy 2.6+.

        '
    dev_url: https://github.com/pyca/pynacl
    doc_url: https://pynacl.readthedocs.io/en/latest/
    home: https://github.com/pyca/pynacl
    license: Apache-2.0
    license_family: Apache
    license_file: LICENSE
    summary: PyNaCl is a Python binding to the Networking and Cryptography library,
        a crypto library with the stated goal of improving usability, security and
        speed.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - CJ-Wright
