# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00002uigo8j\tmp\build\80754af9\rsync-recipes\mkl_random-1.1.1-python_3.7-on-winbuilder, last modified Tue May 26 17:10:10 2020
# ------------------------------------------------

package:
    name: mkl_random
    version: 1.1.1
source:
    sha256: e57d2d57e2796f408fd64fd723bf14259537965af50dd92be049417edfba8816
    url: https://github.com/IntelPython/mkl_random/archive/v1.1.1.tar.gz
build:
    ignore_run_exports:
        - blas
    number: '0'
    script: C:\ci\mkl_random_1590513383067\_h_env\python.exe -m pip install . --no-deps
        -vv
    string: py37h47e9c7a_0
requirements:
    build:
        - vs2017_win-64 19.16.27032.1 hb4161e2_2
        - vswhere 2.7.1 h21ff451_0
    host:
        - blas 1.0 mkl
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.1 py37_0
        - cython 0.29.17 py37ha925a31_0
        - icc_rt 2019.0.0 h0cc432a_1
        - intel-openmp 2020.1 216
        - mkl 2020.1 216
        - mkl-devel 2020.1 217
        - mkl-include 2020.1 216
        - mkl-service 2.3.0 py37hb782905_0
        - numpy-base 1.14.6 py37hc3f5095_5
        - openssl 1.1.1g he774522_0
        - pip 20.0.2 py37_3
        - python 3.7.7 h81c818b_4
        - setuptools 46.4.0 py37_0
        - six 1.14.0 py37_0
        - sqlite 3.31.1 h2a8f88b_1
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_2
        - wheel 0.34.2 py37_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - mkl >=2020.1,<2021.0a0
        - numpy >=1.14,<2.0a0
        - python >=3.7,<3.8.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    commands:
        - nosetests -v mkl_random
    imports:
        - mkl_random
        - mkl_random.mklrand
    requires:
        - nose
about:
    description: NumPy-based implementation of random number generation sampling using
        Intel (R) Math Kernel Library, mirroring numpy.random, but exposing all choices
        of sampling algorithms available in MKL.
    home: http://github.com/IntelPython/mkl_random
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: Intel (R) MKL-powered package for sampling from common probability distributions
        into NumPy arrays.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - oleksandr-pavlyk
