# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/sortedcontainers-2.2.2-on-linux_64, last modified Tue Jun 16 18:05:32 2020
# ------------------------------------------------

package:
    name: sortedcontainers
    version: 2.2.2
source:
    fn: sortedcontainers-2.2.2.tar.gz
    sha256: 4e73a757831fc3ca4de2859c422564239a31d8213d09a2a666e375807034d2ba
    url: https://pypi.io/packages/source/s/sortedcontainers/sortedcontainers-2.2.2.tar.gz
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/sortedcontainers_1592330825210/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
        -m pip install . --no-deps -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.2 py36_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.3 he6710b0_1
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.0.2 py36_3
        - python 3.6.10 h7579374_2
        - readline 8.0 h7b6447c_0
        - setuptools 47.1.1 py36_0
        - sqlite 3.31.1 h62c20be_1
        - tk 8.6.8 hbc83047_0
        - wheel 0.34.2 py36_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python
test:
    imports:
        - sortedcontainers
about:
    description: 'SortedContainers is a sorted collections library, written in pure-Python

        and fast as C-extensions.

        '
    dev_url: https://github.com/grantjenks/python-sortedcontainers
    doc_source_url: https://github.com/grantjenks/python-sortedcontainers/blob/master/docs/index.rst
    doc_url: http://www.grantjenks.com/docs/sortedcontainers/
    home: http://www.grantjenks.com/docs/sortedcontainers/
    license: Apache-2.0
    license_file: LICENSE
    summary: 'Python Sorted Container Types: SortedList, SortedDict, and SortedSet'
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - grantjenks
        - msarahan
        - nehaljwani
        - richafrank
