# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\0000272ka04\tmp\build\80754af9\pull-recipes-pysocks\recipe, last modified Fri Jul 10 16:21:36 2020
# ------------------------------------------------

package:
    name: pysocks
    version: 1.7.1
source:
    sha256: 3f8804571ebe159c380ac6de37643bb4685970655d3bba243530d6558b799aa0
    url: https://pypi.io/packages/source/P/PySocks/PySocks-1.7.1.tar.gz
build:
    number: '1'
    script: C:\ci\pysocks_1594394709107\_h_env\python.exe -m pip install . --no-deps
        -vv
    string: py37_1
requirements:
    host:
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py37_0
        - openssl 1.1.1g he774522_0
        - pip 20.1.1 py37_1
        - python 3.7.7 h81c818b_4
        - setuptools 47.3.1 py37_0
        - sqlite 3.32.3 h2a8f88b_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - wheel 0.34.2 py37_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - python >=3.7,<3.8.0a0
        - win_inet_pton
test:
    imports:
        - socks
about:
    dev_url: https://github.com/Anorov/PySocks
    doc_url: https://github.com/Anorov/PySocks/blob/master/README.md
    home: https://github.com/Anorov/PySocks
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: A Python SOCKS client module. See https://github.com/Anorov/PySocks for
        more information.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
        - pmlandwehr
