# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Wed Apr 29 01:09:12 2020
# ------------------------------------------------

package:
    name: flann
    version: 1.9.1
source:
    fn: flann-1.9.1.tar.gz
    patches:
        - remove-serializer-workaround.patch
        - src-cpp-fix-cmake-3.11-build.patch
    sha256: b23b5f4e71139faa3bcb39e6bbcc76967fbaf308c4ee9d4f5bfbeceaa76cc5d3
    url: https://github.com/mariusmuja/flann/archive/1.9.1.tar.gz
build:
    number: '1008'
    string: h3a160d9_1008
requirements:
    build:
        - cmake 3.17.0 he025d50_0
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - vs2017_win-64 19.16.27038 h2e3bad8_2
        - vswhere 2.7.1 h21ff451_0
    host:
        - hdf5 1.10.6 nompi_ha405e13_100
        - vc 14.1 h869be7e_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - zlib 1.2.11 h2fa13f4_1006
    run:
        - hdf5 >=1.10.6,<1.10.7.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012
test:
    commands:
        - if not exist %PREFIX%\\Library\\bin\\flann_cpp.dll exit 1
        - if not exist %PREFIX%\\Library\\lib\\flann_cpp.lib exit 1
        - if not exist %PREFIX%\\Library\\lib\\flann_cpp_s.lib exit 1
        - if not exist %PREFIX%\\Library\\bin\\flann.dll exit 1
        - if not exist %PREFIX%\\Library\\lib\\flann.lib exit 1
        - if not exist %PREFIX%\\Library\\lib\\flann_s.lib exit 1
        - if not exist %PREFIX%\\Library\\include\\flann exit 1
about:
    home: http://www.cs.ubc.ca/research/flann/
    license: BSD-3-Clause
    license_file: COPYING
    summary: The Fast Library for Approximate Nearest Neighbors
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dougalsutherland
        - jakevdp
        - jakirkham
        - seanyen
