# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /Users/ezyang/Dev/builder/conda/cpuonly, last modified Tue Aug  6 12:10:00 2019
# ------------------------------------------------

package:
    name: cpuonly
    version: '1.0'
build:
    noarch: generic
    string: '0'
    track_features:
        - cpuonly
extra:
    copy_test_source_files: true
    final: true
