# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00001fa3pbr\tmp\build\80754af9\pull-recipes-pexpect\recipe, last modified Fri Jul 10 13:14:41 2020
# ------------------------------------------------

package:
    name: pexpect
    version: 4.8.0
source:
    sha256: fc65a43959d153d0114afe13997d439c22823a27cefceb5ff35c2178c6784c0c
    url: https://pypi.io/packages/source/p/pexpect/pexpect-4.8.0.tar.gz
build:
    number: '1'
    script: C:\ci\pexpect_1594383465186\_h_env\python.exe -m pip install . --no-deps
        -vv
    string: py37_1
requirements:
    host:
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py37_0
        - openssl 1.1.1g he774522_0
        - pip 20.1.1 py37_1
        - python 3.7.7 h81c818b_4
        - setuptools 47.3.1 py37_0
        - sqlite 3.32.3 h2a8f88b_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - wheel 0.34.2 py37_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - pexpect
about:
    description: 'Pexpect is a pure Python module for spawning child applications;

        controlling them; and responding to expected patterns in their output.

        '
    dev_url: https://github.com/pexpect/pexpect
    doc_source_url: https://github.com/pexpect/pexpect/blob/master/doc/index.rst
    doc_url: http://pexpect.readthedocs.org/
    home: http://pexpect.sourceforge.net/
    license: ISC
    license_family: Other
    license_file: LICENSE
    summary: Pexpect makes Python a better tool for controlling other applications.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jquast
        - ocefpaf
        - pelson
        - takluyver
