# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# C:\ci\containers\00000tq0c1a\tmp\build\80754af9\rsync-recipes\pytest-6.2.2-python_3.7-on-winbuilder, last modified Thu Jan 28 11:29:42 2021
# ------------------------------------------------

package:
  name: pytest
  version: 6.2.2
source:
  sha256: 9d1edf9e7d0b84d72ea3dbcdfd22b35fb543a5e8f2a60092dd578936bf63d7f9
  url: https://pypi.io/packages/source/p/pytest/pytest-6.2.2.tar.gz
build:
  entry_points:
    - py.test = py.test:console_main
    - pytest = py.test:console_main
  number: '2'
  script: C:\\ci\\pytest_1611855487500\\_h_env\\python.exe setup.py install --single-version-externally-managed
    --record record.txt
  string: py37haa95532_2
requirements:
  build: []
  host:
    - ca-certificates 2021.1.19 haa95532_0
    - certifi 2020.12.5 py37haa95532_0
    - openssl 1.1.1i h2bbff1b_0
    - pip 20.3.3 py37haa95532_0
    - python 3.7.9 h60c2a47_0
    - setuptools 52.0.0 py37haa95532_0
    - setuptools-scm 5.0.1 pyhd3eb1b0_1
    - setuptools_scm 5.0.1 hd3eb1b0_1
    - sqlite 3.33.0 h2a8f88b_0
    - toml 0.10.1 py_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.36.2 pyhd3eb1b0_0
    - wincertstore 0.2 py37_0
    - zlib 1.2.11 h62dcd97_4
  run:
    - atomicwrites >=1.0
    - attrs >=19.2.0
    - colorama
    - importlib-metadata >=0.12
    - iniconfig
    - more-itertools >=4.0.0
    - packaging
    - pluggy >=0.12,<1.0.0a1
    - py >=1.8.2
    - python >=3.7,<3.8.0a0
    - toml
  run_constrained:
    - pytest-faulthandler >=2
test:
  commands:
    - pytest -h
  imports:
    - pytest
about:
  description: 'The pytest framework makes it easy to write small tests, yet scales
    to

    support complex functional testing for applications and libraries.

    '
  dev_url: https://github.com/pytest-dev/pytest/
  doc_url: https://docs.pytest.org/en/latest/
  home: https://docs.pytest.org/en/latest/
  license: MIT
  license_file: LICENSE
  summary: Simple and powerful testing with Python.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - flub
    - goanpeca
    - mingwandroid
    - nicoddemus
    - ocefpaf
