# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00002d1mobh\tmp\build\80754af9\rsync-recipes\tornado-6.0.4-python_3.7-on-winbuilder, last modified Thu Mar 12 15:20:07 2020
# ------------------------------------------------

package:
    name: tornado
    version: 6.0.4
source:
    sha256: 0fe2d45ba43b00a41cd73f8be321a44936dc1aba233dee979f17a042b83eb6dc
    url: https://pypi.io/packages/source/t/tornado/tornado-6.0.4.tar.gz
build:
    number: '1'
    script: C:\\ci\\tornado_1584027119495\\_h_env\\python.exe -m pip install . --no-deps
        -vv
    string: py37he774522_1
requirements:
    build:
        - vs2017_win-64 19.16.27032.1 hb8d98e7_1
        - vswhere 2.7.1 h21ff451_0
    host:
        - ca-certificates 2020.1.1 0
        - certifi 2019.11.28 py37_0
        - openssl 1.1.1d he774522_4
        - pip 20.0.2 py37_1
        - python 3.7.6 h60c2a47_2
        - setuptools 46.0.0 py37_0
        - sqlite 3.31.1 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
        - wheel 0.34.2 py37_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    commands:
        - pip check
    imports:
        - tornado
        - tornado.gen
        - tornado.netutil
        - tornado.platform
        - tornado.test
    requires:
        - pip
about:
    description: 'Tornado is a Python web framework and asynchronous networking library.

        By using non-blocking network I/O, Tornado can scale to tens of thousands

        of open connections, making it ideal for long polling, WebSockets, and

        other applications that require a long-lived connection to each user.

        '
    dev_url: https://github.com/tornadoweb/tornado
    doc_source_url: https://github.com/tornadoweb/tornado/blob/stable/docs/index.rst
    doc_url: http://www.tornadoweb.org/en/stable/
    home: http://www.tornadoweb.org/
    license: Apache-2.0
    license_family: Apache
    license_file: LICENSE
    license_url: http://www.apache.org/licenses/LICENSE-2.0
    summary: A Python web framework and asynchronous networking library, originally
        developed at FriendFeed.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - ocefpaf
        - pelson
