# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# C:\ci\containers\00000iroia7\tmp\build\80754af9\combined_recipe, last modified Mon Oct  5 11:19:42 2020
# ------------------------------------------------

package:
    name: nbconvert
    version: 6.0.7
source:
    sha256: cbbc13a86dfbd4d1b5dee106539de0795b4db156c894c2c5dc382062bbc29002
    url: https://pypi.io/packages/source/n/nbconvert/nbconvert-6.0.7.tar.gz
build:
    entry_points:
        - jupyter-nbconvert = nbconvert.nbconvertapp:main
    number: '0'
    script: C:\\ci\\nbconvert_1601914921407\\_h_env\\python.exe -m pip install . --no-deps
        --ignore-installed --no-cache-dir -vvv
    string: py37_0
requirements:
    host:
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py37_0
        - openssl 1.1.1h he774522_0
        - pip 20.2.3 py37_0
        - python 3.7.9 h60c2a47_0
        - setuptools 49.6.0 py37_1
        - sqlite 3.33.0 h2a8f88b_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - wheel 0.35.1 py_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - bleach
        - defusedxml
        - entrypoints >=0.2.2
        - jinja2 >=2.4
        - jupyter_core
        - jupyterlab_pygments
        - mistune >=0.8.1
        - nbclient >=0.5.0,<0.6.0
        - nbformat >=4.4
        - pandoc >=1.12.1
        - pandocfilters >=1.4.1
        - pygments >=2.4.1
        - python >=3.7,<3.8.0a0
        - testpath
        - traitlets >=4.2
    run_constrained:
        - pyppeteer ==0.2.2
test:
    commands:
        - jupyter nbconvert --help
        - jupyter nbconvert nbconvert/tests/files/notebook1.ipynb --to html
    imports:
        - nbconvert
        - nbconvert.exporters
        - nbconvert.filters
        - nbconvert.postprocessors
        - nbconvert.preprocessors
        - nbconvert.resources
        - nbconvert.tests
        - nbconvert.utils
        - nbconvert.writers
    source_files:
        - nbconvert/tests/files/notebook1.ipynb
about:
    description: 'The nbconvert tool, jupyter nbconvert, converts notebooks to various
        other

        formats via Jinja templates. The nbconvert tool allows you to convert an

        .ipynb notebook file into various static formats.

        '
    dev_url: https://github.com/jupyter/nbconvert
    doc_url: http://nbconvert.readthedocs.org/
    home: http://jupyter.org
    license: BSD-3-Clause
    license_file: LICENSE
    summary: Converting Jupyter Notebooks
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - blink1073
        - jakirkham
        - minrk
        - mpacer
        - mseal
        - ocefpaf
        - pelson
        - takluyver
