# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Wed Sep 30 18:22:17 2020
# ------------------------------------------------

package:
    name: ipywidgets
    version: 7.5.1
source:
    sha256: e945f6e02854a74994c596d9db83444a1850c01648f1574adf144fbbabe05c97
    url: https://pypi.io/packages/source/i/ipywidgets/ipywidgets-7.5.1.tar.gz
build:
    noarch: python
    number: '1'
    script: python -m pip install --no-deps .
    string: py_1
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py36_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1h h7b6447c_0
        - pip 20.2.2 py36_0
        - python 3.6.12 hcff3b4d_2
        - readline 8.0 h7b6447c_0
        - setuptools 49.6.0 py36_1
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - ipykernel >=4.5.1
        - ipython >=4.0.0
        - nbformat >=4.2.0
        - python
        - traitlets >=4.3.1,<6.0.0
        - widgetsnbextension >=3.5.0,<3.6.0
test:
    imports:
        - ipywidgets
about:
    description: 'ipywidgets are interactive HTML widgets for Jupyter notebooks and
        the IPython kernel.

        '
    doc_source_url: https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/index.rst
    doc_url: https://ipywidgets.readthedocs.io/en/latest/
    home: https://github.com/ipython/ipywidgets
    license: BSD-3-clause
    license_family: BSD
    license_file: LICENSE
    summary: Jupyter Interactive Widgets
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - SylvainCorlay
        - jakirkham
        - jasongrout
        - maartenbreddels
        - minrk
        - pbugnion
        - pelson
        - willingc
