# This file created by conda-build 3.20.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Sep 11 07:47:40 2020
# ------------------------------------------------

package:
    name: dash-table
    version: 4.10.1
source:
    fn: dash_table-4.10.1.tar.gz
    sha256: 1aa02180faef13434364286b60404d26164d1ce2779c765c9c52e6935991a4e9
    url: https://pypi.io/packages/source/d/dash-table/dash_table-4.10.1.tar.gz
build:
    noarch: python
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/dash-table_1599810523485/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
        -m pip install . --no-deps -vv
    string: pyh9f0ad1d_0
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py36h9f0ad1d_0
        - ld_impl_linux-64 2.34 hc38a660_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h24d8f2e_16
        - libgomp 9.3.0 h24d8f2e_16
        - libstdcxx-ng 9.3.0 hdf63c60_16
        - ncurses 6.2 he1b5a44_1
        - openssl 1.1.1g h516909a_1
        - pip 20.2.3 py_0
        - python 3.6.11 h4d41432_2_cpython
        - python_abi 3.6 1_cp36m
        - readline 8.0 he28a2e2_2
        - setuptools 49.6.0 py36h9f0ad1d_0
        - sqlite 3.33.0 h4cf870e_0
        - tk 8.6.10 hed695b0_0
        - wheel 0.35.1 pyh9f0ad1d_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1009
    run:
        - dash
        - python
test:
    imports:
        - dash_table
about:
    dev_url: https://github.com/plotly/dash-table
    home: https://dash.plot.ly/datatable
    license: MIT
    license_family: MIT
    license_file: /home/conda/recipe_root/LICENSE
    summary: A First-Class Interactive DataTable for Dash
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dkucharc
        - moorepants
