# This file created by conda-build 3.20.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Sep 20 21:43:57 2020
# ------------------------------------------------

package:
    name: xarray
    version: 0.16.1
source:
    sha256: 5e1af056ff834bf62ca57da917159328fab21b1f8c25284f92083016bb2d92a5
    url: https://pypi.io/packages/source/x/xarray/xarray-0.16.1.tar.gz
build:
    noarch: python
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/xarray_1600638299066/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
        -m pip install . --no-deps -vv
    string: py_0
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py38h32f6830_0
        - ld_impl_linux-64 2.35 h769bd43_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h24d8f2e_16
        - libgomp 9.3.0 h24d8f2e_16
        - libstdcxx-ng 9.3.0 hdf63c60_16
        - ncurses 6.2 he1b5a44_1
        - openssl 1.1.1g h516909a_1
        - pip 20.2.3 py_0
        - python 3.8.5 h1103e12_8_cpython
        - python_abi 3.8 1_cp38
        - readline 8.0 he28a2e2_2
        - setuptools 49.6.0 py38h32f6830_1
        - setuptools-scm 4.1.2 pyh9f0ad1d_0
        - setuptools_scm 4.1.2 0
        - sqlite 3.33.0 h4cf870e_0
        - tk 8.6.10 hed695b0_0
        - toml 0.10.1 pyh9f0ad1d_0
        - wheel 0.35.1 pyh9f0ad1d_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1009
    run:
        - numpy >=1.17
        - pandas >=0.25
        - python >=3.6
        - setuptools
test:
    imports:
        - xarray
        - xarray.backends
    requires:
        - pytest
about:
    home: https://github.com/pydata/xarray
    license: Apache-2.0
    license_file: LICENSE
    summary: N-D labeled arrays and datasets in Python.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jhamman
        - ocefpaf
        - shoyer
