# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/diff-match-patch-20200713-on-linux_64, last modified Wed Jul 15 16:37:24 2020
# ------------------------------------------------

package:
    name: diff-match-patch
    version: '20200713'
source:
    sha256: da6f5a01aa586df23dfc89f3827e1cafbb5420be9d87769eeb079ddfd9477a18
    url: https://pypi.io/packages/source/d/diff-match-patch/diff-match-patch-20200713.tar.gz
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/diff-match-patch_1594828741838/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
        -m pip install . -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py36_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.1.1 py36_1
        - python 3.6.10 h7579374_2
        - readline 8.0 h7b6447c_0
        - setuptools 49.2.0 py36_0
        - sqlite 3.32.3 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.34.2 py36_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python
test:
    imports:
        - diff_match_patch
about:
    home: http://code.google.com/p/google-diff-match-patch/
    license: Apache-2.0
    license_file: LICENSE
    summary: Diff Match Patch is a high-performance library in multiple languages
        that manipulates plain text
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - ocefpaf
