# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# C:\ci\containers\00003vfgh0s\tmp\build\80754af9\combined_recipe, last modified Wed Oct  7 17:28:06 2020
# ------------------------------------------------

package:
    name: pandas
    version: 1.1.3
source:
    patches:
        - patches/0001-PKG-No-error-for-osx.patch
    sha256: babbeda2f83b0686c9ad38d93b10516e68cdcd5771007eb80a763e98aaf44613
    url: https://github.com/pandas-dev/pandas/releases/download/v1.1.3/pandas-1.1.3.tar.gz
build:
    number: '0'
    script:
        - C:\\ci\\pandas_1602088205210\\_h_env\\python.exe -m pip install --no-deps
            --ignore-installed .
    string: py37ha925a31_0
requirements:
    build:
        - vs2017_win-64 19.16.27032.1 hb4161e2_3
        - vswhere 2.7.1 h21ff451_0
    host:
        - blas 1.0 mkl
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py37_0
        - cython 0.29.21 py37ha925a31_0
        - icc_rt 2019.0.0 h0cc432a_1
        - intel-openmp 2019.4 245
        - mkl 2019.4 245
        - mkl-service 2.3.0 py37hb782905_0
        - mkl_fft 1.0.14 py37h6288b17_0
        - mkl_random 1.0.4 py37h343c172_0
        - numpy 1.15.4 py37h19fb1c0_0
        - numpy-base 1.15.4 py37hc3f5095_0
        - openssl 1.1.1h he774522_0
        - pip 20.2.3 py37_0
        - python 3.7.9 h60c2a47_0
        - setuptools 50.3.0 py37h9490d1a_1
        - six 1.15.0 py_0
        - sqlite 3.33.0 h2a8f88b_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_3
        - wheel 0.35.1 py_0
        - wincertstore 0.2 py37_0
        - zlib 1.2.11 h62dcd97_4
    run:
        - numpy >=1.15.4,<2.0a0
        - python >=3.7,<3.8.0a0
        - python-dateutil >=2.7.3
        - pytz >=2017.2
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
test:
    imports:
        - pandas
about:
    home: http://pandas.pydata.org
    license: BSD-3-Clause
    license_file: LICENSE
    summary: High-performance, easy-to-use data structures and data analysis tools.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - TomAugspurger
        - WillAyd
        - jorisvandenbossche
        - jreback
        - msarahan
        - ocefpaf
