# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/importlib-metadata-2.0.0-on-linux_64, last modified Fri Oct  9 20:51:50 2020
# ------------------------------------------------

package:
    name: importlib-metadata
    version: 2.0.0
source:
    sha256: 77a540690e24b0305878c37ffd421785a6f7e53c8b5720d211b211de8d0e95da
    url: https://pypi.io/packages/source/i/importlib_metadata/importlib_metadata-2.0.0.tar.gz
build:
    noarch: python
    number: '1'
    string: py_1
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1h h7b6447c_0
        - pip 20.2.3 py38_0
        - python 3.8.5 h7579374_1
        - readline 8.0 h7b6447c_0
        - setuptools 50.3.0 py38hb0f4dca_1
        - setuptools-scm 4.1.2 py_0
        - setuptools_scm 4.1.2 0
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=3
        - zipp >=0.5
about:
    home: https://gitlab.com/python-devs/importlib_metadata
    license: Apache-2.0
    license_family: APACHE
    license_file: LICENSE
    summary: A library to access the metadata for a Python package
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - marcelotrevisani
        - nehaljwani
        - nicoddemus
