# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/pull-recipes-path.py/recipe, last modified Sat Aug  8 17:37:44 2020
# ------------------------------------------------

package:
    name: path.py
    version: 12.5.0
source:
    sha256: 8d885e8b2497aed005703d94e0fd97943401f035e42a136810308bff034529a8
    url: https://pypi.io/packages/source/p/path.py/path.py-12.5.0.tar.gz
build:
    noarch: true
    number: '0'
    string: '0'
requirements:
    run:
        - path
        - python >=3.5
test:
    imports:
        - path
about:
    description: 'path.py implements a path objects as first-class entities, allowing
        common

        operations on files to be invoked on those path objects directly.

        '
    dev_url: https://github.com/jaraco/path.py
    doc_source_url: https://github.com/jaraco/path.py/blob/master/docs/index.rst
    doc_url: https://pathpy.readthedocs.io/en/latest/
    home: https://github.com/jaraco/path.py
    license: MIT
    license_file: LICENSE
    summary: A module wrapper for os.path
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - nehaljwani
