#!/bin/sh
'''exec' /home/conda/feedstock_root/build_artifacts/dash_1602531952329/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python "$0" "$@"
' '''
# -*- coding: utf-8 -*-
import re
import sys
from dash.development.component_generator import cli
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(cli())
