# This file created by conda-build 3.18.8
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Fri Jul 19 13:15:30 2019
# ------------------------------------------------

package:
    name: xerces-c
    version: 3.2.2
source:
    sha256: dd6191f8aa256d3b4686b64b0544eea2b450d98b4254996ffdfe630e0c610413
    url: https://archive.apache.org/dist/xerces/c/3/sources/xerces-c-3.2.2.tar.gz
build:
    number: '1004'
    run_exports:
        - xerces-c >=3.2.2,<3.3.0a0
    string: h6538335_1004
requirements:
    build:
        - cmake 3.14.5 he025d50_0
        - vs2015_runtime 14.15.26706 h3a45250_4
        - vs2015_win-64 14.0.25420 h55c1224_11
    host:
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_4
    run:
        - vc >=14,<15.0a0
about:
    home: http://xerces.apache.org/xerces-c/
    license: Apache 2.0
    license_family: Apache
    license_file: LICENSE
    summary: Xerces-C++ is a validating XML parser written in a portable subset of
        C++
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - gillins
        - groutr
        - ocefpaf
