# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Tue Oct  6 16:39:13 2020
# ------------------------------------------------

package:
    name: zipp
    version: 3.3.0
source:
    patches:
        - use-scm-version.patch
    sha256: 64ad89efee774d1897a58607895d80789c59778ea02185dd846ac38394a8642b
    url: https://pypi.io/packages/source/z/zipp/zipp-3.3.0.tar.gz
build:
    noarch: python
    number: '0'
    script: '/tmp/build/80754af9/zipp_1602002379921/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
        -m pip install . --no-deps --ignore-installed -vv '
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1h h7b6447c_0
        - pip 20.2.3 py38_0
        - python 3.8.5 h7579374_1
        - readline 8.0 h7b6447c_0
        - setuptools 50.3.0 py38hb0f4dca_1
        - setuptools-scm 4.1.2 py_0
        - setuptools_scm 4.1.2 0
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - toml 0.10.1 py_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=3.6
test:
    commands:
        - python -m unittest test_zipp.py
        - pip check
    imports:
        - zipp
    requires:
        - func_timeout
        - importlib_metadata
        - jaraco.itertools
        - pip
    source_files:
        - test_zipp.py
about:
    dev_url: https://github.com/jaraco/zipp
    doc_url: https://zipp.readthedocs.io/en/latest
    home: https://github.com/jaraco/zipp
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: A pathlib-compatible Zipfile object wrapper
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nehaljwani
