# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/pull-recipes-jupyterlab_server/recipe, last modified Tue Jul  7 23:26:17 2020
# ------------------------------------------------

package:
    name: jupyterlab_server
    version: 1.2.0
source:
    fn: jupyterlab_server-1.2.0.tar.gz
    sha256: 5431d9dde96659364b7cc877693d5d21e7b80cea7ae3959ecc2b87518e5f5d8c
    url: https://pypi.io/packages/source/j/jupyterlab_server/jupyterlab_server-1.2.0.tar.gz
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/jupyterlab_server_1594164409481/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h7b6447c_0
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.1.1 py38_1
        - python 3.8.3 hcff3b4d_2
        - readline 8.0 h7b6447c_0
        - setuptools 47.3.1 py38_0
        - sqlite 3.32.3 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - jinja2 >=2.10
        - json5
        - jsonschema >=3.0.1
        - notebook >=4.2.0
        - python >=3.5
        - requests
test:
    commands:
        - python -m pip check
    imports:
        - jupyterlab_server
    requires:
        - pip
about:
    home: https://github.com/jupyterlab/jupyterlab_server
    license: BSD-3-Clause
    license_file: LICENSE
    summary: A set of server components for JupyterLab and JupyterLab like applications.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - SylvainCorlay
        - afshin
        - blink1073
        - bollwyvl
        - jasongrout
